### ISSUE TITLE
Return code 2401, "username or password wrong".

### ISSUE THREAD

**Issue by williamrowell** [tuya/tuya-homebridge#10]
This is probably something simple, but I've checked the username and password a few times already.

Return code 2401, "username or password wrong".  Username and password are correct for [Tuya IoT Platform](https://iot.tuya.com/index/) account associated with accessId/accessKey.

```
TuyaOpenAPI response: {"code":2401,"msg":"username or password wrong","success":false,"t":1621708376633}
```

```json
...,
{
    "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "options": {
        "username": "myemailaddress",
        "password": "mypassword",
        "accessId": "myaccessid",
        "accessKey": "myaccesskey",
        "lang": "en",
        "endPoint": "https://openapi.tuyaus.com"
    }
},
...
```

**Comment by Hanh94** [comment]
Perhaps you used the IoT platform login username and password. you can check the [Tuya IoT Platform Configuration Guide](https://github.com/tuya/tuya-android-iot-app-sdk-sample/blob/activator_tool/Tuya_IoT_Platform_Configuration_Guide.md)  in Step 5. Maybe it will solve your problem.
