### ISSUE TITLE
Blinds/Curtain direction is reversed

### ISSUE THREAD

**Issue by patrickl96** [tuya/tuya-homebridge#102]
I've got Blinds set up in the Tuya Smart app. When the blinds are in 'Open' position in the Tuya Smart app, HomeKit will show them as being in 'Closed' position.

When I tap in the Home app to open the blinds, they will instead close and vice versa.

**Comment by xrust83** [comment]
> I've got Blinds set up in the Tuya Smart app. When the blinds are in 'Open' position in the Tuya Smart app, HomeKit will show them as being in 'Closed' position.
> 
> When I tap in the Home app to open the blinds, they will instead close and vice versa.

downgrade plugin to 1.3.1

**Comment by Hanh94** [comment]
Hi @xrust83 @patrickl96 ,Sorry for the late reply.
We have tried to fix this problem in version 1.4.1, please update to the latest version, if there is any problem, please feedback to us, we will deal with it in the first time. Thanks.

**Comment by cnhx** [comment]
I’m still having the same problem with the latest version plug-in, could you help check?

**Comment by SamMalcolm** [comment]
I'm also still having this problem with the latest version
