### ISSUE TITLE
None of my outlets are showing up in Homebridge.

### ISSUE THREAD

**Issue by bluntiless** [tuya/tuya-homebridge#106]
**Describe the bug**
Tuya SmartLife outlets not being displayed in Homebridge despite following your video tutorial. Everything went as expected and outlets appear as online in my list of devices on Tuya developer website.

**Expected behavior**
Restart Homebridge and see my Tuya outlets appear in HomeKit/Home App.

**Screenshots**

<img width="1088" alt="Screenshot 2021-09-18 at 09 02 55" src="https://user-images.githubusercontent.com/1809627/133881578-89c4afca-9827-4b4b-82ea-a8d15baef3f7.png">

Any help would be appreciated.

**Comment by Hanh94** [comment]
Hi @bluntiless , Sorry for the late reply.
Please turn on the log, and Check whether any errors are reported in the log. and Check the interface **/v1.0/ ioT-01 /associated-users/devices** to see whether device data is returned.
