### ISSUE TITLE
Homebridge connect error

### ISSUE THREAD

**Issue by Blinky122** [tuya/tuya-homebridge#109]
I have IoT connect with my Smart Life app and i see the device in Tuya project. But i have no answer, why i have this issue 
All my Login Data is correct.

I have HB in Docker Container in Synology NAS (DSM 7). Automatik Install

Starting to advertise 'Homebridge 3625 F32F' using bonjour-hap backend!
[9/21/2021, 3:47:36 PM] Homebridge v1.3.4 (Homebridge 3625) is running on port 51047.
TuyaOpenAPI response: {"result":{"access_token":"f3a3e9ebdc08xxxxxxxxxxx","expire_time":7200,"platform_url":"h t openapi.tuyaeu.com","refresh_token":"fa9e77ba7a31397xxxxxxxxxxxxxxx","uid":"eu16319883xxxxxxxxxx"},"success":true,"t":1632232057098} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1632232057260","client_id":"cjwd4peaaxxjt6enlc7u","nonce":"7a4ed300-1ae2-11ec-a5fc-d5c6cf63a671","Signature-Headers":"client_id","sign":"7DD03E7B19E5AA1932F37C88F87F7B8xxxxxxxxxxx","sign_method":"HMAC-SHA256","access_token":"f3a3e9ebdc0803f3e04798bf091cd3e5","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.0"}
TuyaOpenAPI response: {"code":28841101,"msg":"No permissions. This API is not subscribed.","success":false,"t":1632232057383} path = /v1.0/iot-01/associated-users/devices
Failed to get device information. Please check if the config.json is correct.

When i install Homebride on Windows 10, it is the same issue

Config

`    "options": {
                "username": "xxxxx@icloud.com",
                "password": "xxxxxx",
                "accessId": "cjxxxxxxxxxxxxx",
                "accessKey": "bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "lang": "en",
                "projectType": "2",
                "appSchema": "smartlife",
                "countryCode": 49,
                "debug": true
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform"`

sorry for my english.

**Comment by Blinky122** [comment]
Now i have install my devices in Tuya Smart, but the issue is the same...

TuyaOpenAPI response: {"result":{"access_token":"73d6xxxxxxxxxxx","expire_time":7200,"platform_url":"https://openapi.tuyaeu.com","refresh_token":"b11e9cb5c226d4xxxxxxxxxxxxxxx","uid":"eu16xxxxxxxx"},"success":true,"t":1632xxxx} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1632xxxxxxx2","client_id":"cjwd4xxxxxxxx","nonce":"f6xxxxxxxxxxxxxxxxxxxxxxxx","Signature-Headers":"client_id","sign":"26B356423252ED2E1ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","sign_method":"HMAC-SHA256","access_token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.0"}
TuyaOpenAPI response: {"code":28841101,"msg":"No permissions. This API is not subscribed.","success":false,"t":1632243432999} path = /v1.0/iot-01/associated-users/devices
Failed to get device information. Please check if the config.json is correct.

**Comment by Blinky122** [comment]
Now i have this issue....

TuyaOpenAPI response: {"code":2007,"msg":"your ip(xxxxxxxxxxx) cross-region access is not allowed","success":false,"t":1632308811156} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by xrust83** [comment]
https://developer.tuya.com/ droop host

**Comment by Blinky122** [comment]
> https://developer.tuya.com/ droop host

Dont unterstand

**Comment by weirdpattern** [comment]
I'm having the same issue here. getting the cross region access is not allowed error because the API is ignoring the endPoint from my config and connecting to the China Data Center.

**Comment by xrust83** [comment]
> > https://developer.tuya.com/ droop host
> 
> 
> 
> Dont unterstand

the site through which the tuya api plugin is configured did not work all day and morning today.  Because of this, my curtains did not open in the morning and I opened them from the SmartLife application, by the time the curtains closed by themselves.  the site is working now.

**Comment by Blinky122** [comment]
Answer from support:

Hello, I'm sorry, we are urgently repairing HB's Tuya account login problem. It is expected that the repair will be completed in one to two working days. please wait patiently.

**Comment by 0ldF0x** [comment]
I also opened a ticket and suggested them a fix. Support is very responsive :)
Problem is in constructor, which doesn't read the endpoint setting: 
**tuyashopenapi.js**
`
<!DOCTYPE html>

const DEFAULT_ENDPOINT = 'https://openapi.tuyacn.com';
--
6 | class TuyaSHOpenAPI {
… |  
8 | constructor(**accessId**, accessKey, username, password, countryCode, appSchema, log, lang = 'en') {
9 | **this.endpoint = DEFAULT_ENDPOINT;**

`

`api = new TuyaOpenAPI(
        config.options.endPoint,
        config.options.accessId,
        config.options.accessKey,
        this.log,
      );`

**Comment by Blinky122** [comment]
Hello, this problem has been fixed, you can download the latest version of the Master branch and try again.
https://github.com/tuya/tuya-homebridge

**Comment by Hanh94** [comment]
Hi guys, Sorry for the late reply.
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-957266378 & https://github.com/tuya/tuya-homebridge/issues/108#issuecomment-958749710

**Comment by C1ironie** [comment]
Hi team 

I have an error code 1114 with description of my IP adress doesn't have access to this API",
Certainly I missed something... 
Thank for your help
