### ISSUE TITLE
Support for Smoke Detectors

### ISSUE THREAD

**Issue by haukee** [tuya/tuya-homebridge#11]
Please add Support for Smoke Detectors. 

Because of the limitations regarding polling, they are not supported by the other tuya plugins for Homebridge.

**Comment by zlinoliver** [comment]
Hi @haukee , we will support the Smoke Detectors in the Tuya homebridge plugin update within this week. Also, will support "Smart Home" project type and developers can use Tuya Smart app for device pairing directly. Please stay focus on this github repo update.
