### ISSUE TITLE
Can’t control fan rotation speed

### ISSUE THREAD

**Issue by dfizzo** [tuya/tuya-homebridge#111]
**Describe the bug**

Fan speed control for Tuya Treatlife fan controller doesn’t work. 

**Expected behavior**
4-speed fan control between speeds 1,2,3,4. 

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/iot-01/associated-users/devices**

like this:
{
      "active_time": 1623229189,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1560491945,
      "icon": "smart/product_icon/cz.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "30.30286857361191",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "120.0639743842656",
      "model": "",
      "name": "Living Room Socket",
      "online": false,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name": "Switch Product",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2343
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

**Device functions (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/devices/functions**
Same **device Id**, like this:
{
    "category":"cl",
    "devices":[
        "aaaaaaaaaaa"
    ],
    "functions":[
        {
            "code":"control",
            "desc":"control",
            "name":"control",
            "type":"Enum",
            "values":"{\"range\":[\"open\",\"stop\",\"close\"]}"
        },
        {
            "code":"percent_control",
            "desc":"percent control",
            "name":"percent control",
            "type":"Integer",
            "values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
        },
        {
            "code":"control_back",
            "desc":"control back",
            "name":"control back",
            "type":"Boolean",
            "values":"{}"
        }
    ],
    "product_id":"xaabybja"
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by Hanh94** [comment]
Hi @dfizzo , Sorry for the late reply.
Please provide more **"category": "fs"** information

**Comment by dfizzo** [comment]
Hi @Hanh94, can you please let me know what information you need me to provide and where to pull information from? Thanks!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Nov 3, 2021, at 5:12 AM, Hanh94 ***@***.***> wrote:

﻿
Hi @dfizzo , Sorry for the late reply.
Please provide more "category": "fs" information

**Comment by dfizzo** [comment]
Hi @Hanh94: just following up on the below. Please let me know what info I should provide you to further triage the situation. Thanks!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Nov 8, 2021, at 2:12 PM, Daniel Fein ***@***.***> wrote:

﻿Hi @Hanh94, can you please let me know what information you need me to provide and where to pull information from? Thanks!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Nov 3, 2021, at 5:12 AM, Hanh94 ***@***.***> wrote:

﻿
Hi @dfizzo , Sorry for the late reply.
Please provide more "category": "fs" information

**Comment by dfizzo** [comment]
On IoT.tuya.coM website, the fan switch is shown as “Category: fskg”

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Nov 3, 2021, at 5:12 AM, Hanh94 ***@***.***> wrote:

﻿
Hi @dfizzo , Sorry for the late reply.
Please provide more "category": "fs" information
