### ISSUE TITLE
device status not updating

### ISSUE THREAD

**Issue by arturlukosek** [tuya/tuya-homebridge#112]
When light color or brightness is changed in Tuya app or by Alexa, homekit seems to always show the previous data. There is also no way to see the actual color of light as it is always display as white in the home app. 
When some device settings are changed in Home app Tuya app  right away ( Alexa within 5 s) provides with updated data. When color is changed in Tuya app or by Alexa those datas are not updated in homekit.

**Comment by adamnet01** [comment]
Hello, I have the same problem with the status update. Homebridge does not recognize a change in device state. After the Hombridge server reset, the status is up-to-date. 
I have wifi and Tuya zigbee drivers and a Homebridge Tuya Platform plug in the latest version.

**Comment by adamnet01** [comment]
It's already working, I had the "Device Status Notification" api not running.

**Comment by oliverchapple** [comment]
I got the same issue when I say Alexa turn on light it on home app but light does not come 

thanks Oliver

**Comment by Hanh94** [comment]
Hi guys, Sorry for the late reply.
Please see https://github.com/tuya/tuya-homebridge/issues/117#issuecomment-958759411
