### ISSUE TITLE
TuyaOpenAPI response: {"code":28841101,"msg":"No permissions. This API is not subscribed.","success":false,"t":1632568755009}

### ISSUE THREAD

**Issue by telespectadorhd** [tuya/tuya-homebridge#114]
TuyaOpenAPI response: {"code":28841101,"msg":"No permissions. This API is not subscribed.","success":false,"t":1632568755009} path = /v1.0/iot-01/associated-users/devices
Failed to get device information. Please check if the config.json is correct.

Please, i need some help.

**Comment by telespectadorhd** [comment]
<img width="1006" alt="Captura de Tela 2021-09-25 às 08 38 46" src="https://user-images.githubusercontent.com/47015723/134770163-a1fc52c9-de72-40c8-89cd-698a2d987aa1.png">

my api authorized

**Comment by Hanh94** [comment]
Hi @telespectadorhd ,
Please refer to this document: https://github.com/tuya/tuya-homebridge/wiki/Tuya-IoT-Platform-Configuration-Guide-Using-Smart-Home-PaaS?_source=d8fba44feeef4757f7f22a14c2295f3f#create-a-project
Authorization、Data Service API missed

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/108#issuecomment-958749710

**Comment by farverio** [comment]
`Data Service API` doesn't exist in the project, this issue should not have been closed. The info does not resolve the problem. Furthermore, if you're API can't specify the problem in the response to the user, there's no realistic expectation that a user can debug

**Comment by starkprime** [comment]
Following up here, I'm having this issue. But i don't see a fix

**Comment by Geczy** [comment]
i added data dashboard service api and its fixed

![image](https://user-images.githubusercontent.com/1036968/196040163-ea98460e-2bff-4a2c-bf21-8b97c0dbed02.png)

**Comment by DenisBessa** [comment]
I was able to solve the issue by deleting and recreating the Project in the Tuya Developer Platform
