### ISSUE TITLE
devices not showing up on HomeKit

### ISSUE THREAD

**Issue by ileecummins** [tuya/tuya-homebridge#124]
**Describe the bug**
followed the video and setup the plugin via a Mac and configured the setup

**Expected behavior**
Smart Life device's to show on Homekit & Homebridge devices to show 

**Screenshots**
no devices showing on either HomeKit or Homebridge

**Comment by adude007** [comment]
I have the same issue. When I create my project on the Tuya IoT site there is no Smart Home Devices in the API list. Also, the data center options do not look the same as the tutorial. Do you have the same issues @ileecummins?

**Comment by adude007** [comment]
@ileecummins I got mine to work! I had an issue getting an account created on the IoT platform and used a different user name and password than I used in the Tuya Smart app. What worked for me was putting in the user name and password for my Tuya Smart app account and the accessID and accessKey from the cloud project. I enabled debugging in the config file error code 1106 pointed me in the correct direction: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt&_source=f3feb8f41d71c863087f8bc8032c9a4a#title-6-Error%20code%20and%20troubleshooting

**Comment by LoneStar1845** [comment]
I am having a similar issue. I am running the Hoobs Tuya Web Platform and it works almost perfectly. Most of my bulbs and plugs show up, but two have not been found.

**Comment by Scottjutsu** [comment]
I'm seeing the same issue. The devices are listed in the API response, but the plugin never registers them with Homebridge. I am also trying to control diffusers.

**Comment by Scottjutsu** [comment]
In the case of diffusers, it appears that the diffuser `deviceType` of `jsq` [is not supported](https://github.com/tuya/tuya-homebridge/blob/02f2ce330e4b5aa3f7f996a34dd924b03a6d3f2b/index.js#L118). Bummer.
