### ISSUE TITLE
Homekit scenes do not set colors properly

### ISSUE THREAD

**Issue by nchbuser** [tuya/tuya-homebridge#125]
**Describe the bug**
I have a fixture with 4 Tuya bulbs. I create two scenes in Homekit: "Blue" which should set all bulbs to blue, and "white" which should set all bulbs to white. When either scene is run, the bulbs end up in what appears to be random states: some blue, some white, some very dim, some very bright...

**Expected behavior**
When a scene sets a bulb color, the belt should set to that color. If a single scene sets multiple bulbs to a color, all the bulbs should be that color.

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
path = /v1.0/devices/eb8c6231e6461f4035o89w/commands

TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828414} path = /v1.0/devices/ebd84c3a5aa4577f3disak/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828419} path = /v1.0/devices/eb8c6231e6461f4035o89w/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828424} path = /v1.0/devices/ebd84c3a5aa4577f3disak/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828425} path = /v1.0/devices/ebb7e807177d239e840dgv/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828431} path = /v1.0/devices/ebb4d539f899f1d5d6qw1r/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828431} path = /v1.0/devices/eb8c6231e6461f4035o89w/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828457} path = /v1.0/devices/ebb7e807177d239e840dgv/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828540} path = /v1.0/devices/ebd84c3a5aa4577f3disak/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828539} path = /v1.0/devices/ebb4d539f899f1d5d6qw1r/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828546} path = /v1.0/devices/ebb4d539f899f1d5d6qw1r/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828571} path = /v1.0/devices/eb8c6231e6461f4035o89w/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1634161828571} path = /v1.0/devices/ebb7e807177d239e840dgv/commands

**Comment by nchbuser** [comment]
This continues to be a problem. I created a scene called "white" that should set all bulbs to white, and another scene called "blue" that should set all bulbs to blue. The actual color changes appear to be random and unpredictable.

**Comment by nchbuser** [comment]
Interesting observation... if you set up a scene using Alexa, and that scene sets the color on multiple bulbs, it works 90+% of the time. But doing that in a Homekit scene (which requires Homebridge) fails [almost] 100% of the time (I said almost, but I've never seen it work).

**Comment by dev01d** [comment]
Just to add some additional observations. 

I’ve seen it work a few times a month since October so around 15% and sometimes you get really lucky with automations and it gets it first try. It usually takes a few executions of the scene in a row to get the correct color. White is particularly bad with LED strips since the temperature is rarely saved so it ends up a pale blue and I have to “make” the color white again which end up displaying purple in the slider. 

Retiring my Tuya controllers this week because of this. Will check back in a few releases though.

**Comment by dibsies** [comment]
Same issue here. Hopefully, a fix is forthcoming soon.

**Comment by Mike92115** [comment]
Same issue, colors are a roll of the dice as to what it will be when the scene is activated in Homekit

**Comment by NoOneReally2021** [comment]
There is a newer thread, seems its a  hard one to solve 
any update would be appreciated

**Comment by NoOneReally2021** [comment]
> Thank you for your feedback, we will solve this issue soon

6 months have passed, any update ?

**Comment by Mike92115** [comment]
This is not stale, just not touched

**Comment by dibsies** [comment]
This is still not stale, just still not touched

**Comment by renatz76** [comment]
same issue here, any ideas if this will be solved in the future?

**Comment by mrkpkngn** [comment]
not stale, still untouched
