### ISSUE TITLE
Support for Light accessory _v2

### ISSUE THREAD

**Issue by lodev09** [tuya/tuya-homebridge#13]
Please provide support for the following status codes:
```json
[
  {
    "code": "bright_value_v2",
    "value": 1000
  },
  {
    "code": "temp_value_v2",
    "value": 1000
  },
  {
    "code": "colour_data_v2",
    "value": "{\"h\":24,\"s\":1000,\"v\":1000}"
  }
]
```

The new update works (aside from the issue in #12) but the light accessory I'm using returns the above unsupported codes so the homekit status only shows on/off switch.

Thanks!

**Comment by Hanh94** [comment]
@lodev09 We have supported dynamic dp in LightAccessory
