### ISSUE TITLE
Can not login through tuya-homebridge and IFTTT

### ISSUE THREAD

**Issue by TheWojtek** [tuya/tuya-homebridge#131]
**Describe the bug**
The plugin does not allow me to log in. Same goes regarding IFTTT connection.

**Expected behavior**
After filling the plugin setup with username and password (same as on https://iot.tuya.com which works), the "Access ID/Client ID:" from the project, "Access Secret/Client Secret" from the project, selecting the language (PL), "project type" (PaaS), and "PaaS Platform" (Smart Life) the plugin should log in to Tuya Cloud and pass the devices attached to Homebridge.

The error (2406) is obviously a cloud-side issue, as the region is set properly in my project (Central Europe) and plugin (48). BTW the information on https://github.com/tuya/tuya-homebridge/wiki/Tuya-IoT-Platform-Configuration-Guide-Using-Smart-Home-PaaS?_source=d8fba44feeef4757f7f22a14c2295f3f#create-a-project is obsolete and misguiding, as the Smart Life app does not provide a region for Availability Zone (it provides a country) and the list of the country → Availability Zone on the page is far from exhaustive. Also, the API names are completely mismatched in the instructions compared to what can be seen on iot.tuya.com
Eventually I turned on ALL the zones in the project and the plugin still does not log in.

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1634419697461} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/lib/node_modules/homebridge-tuya-platform/index.js:90:19)

** Additional info **

I can use the switches using debug on iot.tuya.com. I can use the switches from Tuya Smart Life app. Homebridge is a no go.

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-957266378
