### ISSUE TITLE
HomeKit scenes do not properly set color or Brightness

### ISSUE THREAD

**Issue by adude007** [tuya/tuya-homebridge#133]
**Describe the bug**
When running a HomeKit scene colors and brightness are inconsistent across multiple bulbs. 

**Expected behavior**
Each bulb should illuminate in the set color and brightness. 

**Actual Behavior**

On first run Scene will change color of me bulb to correct color without adjusting brightness. On second run second bulb will change color and first bulb will change to correct brightness. On third run of scene second bulb adjusts to proper brightness

**Comment by wills721** [comment]
https://github.com/tuya/tuya-homebridge/issues/154

I had the same issue but I found a code fix that I did myself.

**Comment by adude007** [comment]
> #154
> 
> I had the same issue but I found a code fix that I did myself.

Thanks for that information. I actually switched to one of the Tuya Lan control plugins. The control of the light for color and brightness has worked very well since taking the Tuya cloud out of it.

**Comment by Karthiktuli** [comment]
> > #154
> 
> > 
> 
> > I had the same issue but I found a code fix that I did myself.
> 
> 
> 
> Thanks for that information. I actually switched to one of the Tuya Lan control plugins. The control of the light for color and brightness has worked very well since taking the Tuya cloud out of it. 

How can we install the local lan plugin for tuya ..?

**Comment by adude007** [comment]
> > > #154
> > 
> > 
> > > 
> > 
> > 
> > > I had the same issue but I found a code fix that I did myself.
> > 
> > 
> > Thanks for that information. I actually switched to one of the Tuya Lan control plugins. The control of the light for color and brightness has worked very well since taking the Tuya cloud out of it.
> 
> How can we install the local lan plugin for tuya ..?

This is what I used. https://github.com/iRayanKhan/homebridge-tuya
