### ISSUE TITLE
Code 2406 skill id invalid

### ISSUE THREAD

**Issue by jackwburger** [tuya/tuya-homebridge#14]
How to solve:

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1622204992541} path = /v1.0/iot-01/associated-users/actions/authorized-login
(node:28565) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:45:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:128:5)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:58:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:76:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

using: 

tuyaSmart
europe

**Comment by Hanh94** [comment]
@jackwburger Sorry for the bad experience, the server problem has been fixed, please try again

**Comment by lodev09** [comment]
@Hanh94 same here. I'm trying to contribute but I couldn't use my account now after the recent update. Getting "skill is invalid" error -- although this error is now the same with the API explorer when I tried. Could be a timezone issue? I'm in Asia/Manila and using America as the data center.

Please advise. thanks

**Comment by Hanh94** [comment]
Hi，@lodev09  Your cloud project on the [Tuya IoT Platform](https://iot.tuya.com/cloud/) was created after May 25, 2021.  For more information, Please see [Tuya IoT Platform Configuration Guide Using Smart Home PaaS](https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx).

**Comment by lodev09** [comment]
@Hanh94 hmmm, I'm not sure if that's the right documentation. First, that project was created weeks ago already -- I just modified it to match the instructions given to link to homebridge. 2nd, there's no way to delete an existing home paas project and I couldn't create new one as well.

**Comment by zlinoliver** [comment]
Hi @lodev09 , as the new update for Tuya Homebridge plugin only works for new projects created after 25th May, 2021. If your project is created weeks ago, then please recreate a new cloud project of "Smart Home PaaS" type by following the documentation above. If you have exceeded the limit of creating cloud project for free account (Only two projects), please create a new Tuya IoT Platform account and create the cloud project again. Hope this helps!

**Comment by lodev09** [comment]
Yeah I guess I can do that. Anyway, is there a way you can change the country of my other account? I wanted to use an official email of mine for my integration. The email
Is lodev09@gmail.com. I can't find a way to change the region.

**Comment by Hanh94** [comment]
Hi @lodev09 , You can make this request through the [**tickets**](https://service.console.tuya.com)

**Comment by jackwburger** [comment]
> @jackwburger Sorry for the bad experience, the server problem has been fixed, please try again

@Hanh94 I tried again but still the same problem. I created the cloud project a couple of months ago so it seems I need to recreate one. Unfortunately the old project cannot be deleted (Why does it take so long to implement this feature?). Now I need to create a new account which is rather dump. Anyway thanks for the help.

**Comment by lodev09** [comment]
I ended up creating my own plugin lol
https://github.com/lodev09/homebridge-tuya-smarthome

**Comment by Hanh94** [comment]
Hi @lodev09, We already support Lightbulb Dynamic dp

**Comment by codyc1515** [comment]
> Hi @lodev09 , as the new update for Tuya Homebridge plugin only works for new projects created after 25th May, 2021. If your project is created weeks ago, then please recreate a new cloud project of "Smart Home PaaS" type by following the documentation above. If you have exceeded the limit of creating cloud project for free account (Only two projects), please create a new Tuya IoT Platform account and create the cloud project again. Hope this helps!

This seems like the most difficult possible way to do things. Is there no other way?

**Comment by zlinoliver** [comment]
Hi @codyc1515 sorry for the inconvenience, please create a Tuya technical support [ticket](https://service.console.tuya.com/) , we will assistant you to resolve the issue.

**Comment by natanrolnik** [comment]
@zlinoliver can't I delete my existing project? Or my current account? This way I'd have two accounts.

**Comment by Hanh94** [comment]
Hi guys, Since we haven't received your reply for a long time, we think our latest version should have solved your problem. We will close this issue first. If there is any problem, you can contact us at any time.
