### ISSUE TITLE
Error 1106

### ISSUE THREAD

**Issue by ryanlbates01** [tuya/tuya-homebridge#147]
**Describe the bug**
since 4/11/2021 I am no longer able to generate access tokens. my login details have not changed yet i am now getting an 1106 error. I noticed my devices has become unresponsive in the apple home app around 13:00GMT.

I have tried updating the plugin to version 1.5.0 and rolled back to 1.4.2 but I am still getting the 1106 error even after following the troubleshooting steps.

here is the error logs from my homebirdge.

Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":44,"username":"rbates93@virginmedia.com","password":"1a1a9ef8d4204a90f5174cb4fa6d7134","schema":"tuyaSmart"}, headers = {"t":"1636034910674","client_id":"df77g3vfb0qhztuq8f26","nonce":"b0124540-3d78-11ec-a921-2f64890546a5","Signature-Headers":"client_id","sign":"D89B6532ED79F2F9949C7DA7979333349370A322E18999DE74D257A45F5A8941","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.2"}
Preparing Advertiser for 'Homebridge 13DF 8CD8' using bonjour-hap backend!
Setup Payload:
X-HM://0024BMSCC4699
......
                       
Starting to advertise 'Homebridge 13DF 8CD8' using bonjour-hap backend!
[11/4/2021, 2:08:30 PM] Homebridge v1.3.5 (Homebridge 13DF) is running on port 51884.
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1636034910962} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by zlinoliver** [comment]
Sorry for the inconvenience, we have found the cause of the 1106 error, it's related to the Tuya Smart/ Smart Life account password validation. We will fix it ASAP.

**Comment by kirit1193** [comment]
Facing the same issue here.

**Comment by ryanlbates01** [comment]
@zlinoliver thank you for your quick response. do you have an ETA on a fix?

**Comment by Tomaholk1** [comment]
same here ;/

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-961586965

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-961586965
