### ISSUE TITLE
成功接入homebridge，但设备没有出现在列表里

### ISSUE THREAD

**Issue by whenyoucan** [tuya/tuya-homebridge#148]
**Describe the bug**
已经成功接入homebridge，启动日志里已经明确打印出我在涂鸦iot平台里的设备信息（详见后面附上的日志）
但在家庭app中，无法找到这个设备

**Expected behavior**
需要在家庭app中显示和控制

**Screenshots**
以下是详细的debug日志，包含了设备信息和function信息：

TuyaOpenAPI response: {"result":{"access_token":"脱敏","expire_time":7200,"platform_url":"https://openapi.tuyacn.com","refresh_token":"137d148fdd7822044972a6e58d9d3ac2","uid":"脱敏"},"success":true,"t":1636039025533} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1636039025546","client_id":"脱敏","nonce":"44c8dce0-3d82-11ec-bcbb-059b9c151f6d","Signature-Headers":"client_id","sign":"2F150CC92FFBFD867DF5055F003BCFA9F38BA0EC9D2B064A2BFF63E43BA93049","sign_method":"HMAC-SHA256","access_token":"脱敏","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1636033981,"biz_type":0,"category":"kt","create_time":1636033981,"icon":"smart/icon/ay1528212606967MoBaI/a655160513105fc776b53fb2e48eea25.png","id":"18470020e098061f055f","ip":"115.197.139.69","lat":"30.2968","local_key":"f9397c033020d7ae","lon":"120.1090","model":"UACC-A-XX-TW","name":"主卧空调","online":true,"owner_id":"42953431","product_id":"EyZ4jHTX4agiWroA","product_name":"中央空调单内机网关（WiFi）","status":[{"code":"switch","value":false},{"code":"temp_set","value":25},{"code":"temp_current","value":20},{"code":"mode","value":"hot"},{"code":"fan_speed_enum","value":"auto"}],"sub":false,"time_zone":"+08:00","uid":"脱敏","update_time":1636038757,"uuid":"18470020e098061f055f"}],"has_more":false,"last_row_key":"40258D368FA624402AFAE90A7AB1B140","total":1},"success":true,"t":1636039025654} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyacn.com, path = /v1.0/devices/functions, params = {"device_ids":"18470020e098061f055f"}, body = null, headers = {"t":"1636039025660","client_id":"脱敏","nonce":"44c8dce0-3d82-11ec-bcbb-059b9c151f6d","Signature-Headers":"client_id","sign":"134127219C344C2EA0F0A7F9ABC1AE05D12726BD2E4F295F4D241F381BBB34F8","sign_method":"HMAC-SHA256","access_token":"脱敏","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":[{"category":"kt","devices":["18470020e098061f055f"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"fan_speed_enum","desc":"fan speed enum","name":"fan speed enum","type":"Enum","values":"{\"range\":[\"low\",\"mid\",\"high\",\"auto\"]}"},{"code":"temp_set","desc":"temp set","name":"temp set","type":"Integer","values":"{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":32,\"step\":1}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\"]}"}],"product_id":"EyZ4jHTX4agiWroA"}],"success":true,"t":1636039025794} path = /v1.0/devices/functions
Adding: 主卧空调 (kt / 18470020e098061f055f)
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-03/open-hub/access-config, params = null, body = {"uid":"脱敏","link_id":"44d70db0-3d82-11ec-bcbb-059b9c151f6d","link_type":"mqtt","topics":"device","msg_encrypted_version":"1.0"}, headers = {"t":"1636039025801","client_id":"脱敏","nonce":"44c8dce0-3d82-11ec-bcbb-059b9c151f6d","Signature-Headers":"client_id","sign":"13B75287DA498CAF34910BE0F7C04CFFD6388FB52F7351B5B0C38562D24A4CC1","sign_method":"HMAC-SHA256","access_token":"脱敏","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"client_id":"cloud_d6e9ab0cb41b82cd4f48cdf2119cad6b","expire_time":7200,"password":"d33f1bd8110f7b6a594348c6f0cc17c3","sink_topic":{"device":"cloud/token/out/{device_id}"},"source_topic":{"device":"cloud/token/in/7d50fa534cb1049f326e7bfed43e82c5"},"url":"ssl://m1.tuyacn.com:8883","username":"cloud_7d50fa534cb1049f326e7bfed43e82c5"},"success":true,"t":1636039025912} path = /v1.0/iot-03/open-hub/access-config
TuyaOpenMQ connecting: ssl://m1.tuyacn.com:8883
TuyaOpenMQ connected

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/iot-01/associated-users/devices**
结果如下：
{
  "result": {
    "devices": [
      {
        "active_time": 1636033981,
        "biz_type": 0,
        "category": "kt",
        "create_time": 1636033981,
        "icon": "smart/icon/ay1528212606967MoBaI/a655160513105fc776b53fb2e48eea25.png",
        "id": "18470020e098061f055f",
        "ip": "115.197.139.69",
        "lat": "30.2968",
        "local_key": "f9397c033020d7ae",
        "lon": "120.1090",
        "model": "UACC-A-XX-TW",
        "name": "主卧空调",
        "online": true,
        "owner_id": "42953431",
        "product_id": "EyZ4jHTX4agiWroA",
        "product_name": "中央空调单内机网关（WiFi）",
        "status": [
          {
            "code": "switch",
            "value": false
          },
          {
            "code": "temp_set",
            "value": 25
          },
          {
            "code": "temp_current",
            "value": 20
          },
          {
            "code": "mode",
            "value": "hot"
          },
          {
            "code": "fan_speed_enum",
            "value": "auto"
          }
        ],
        "sub": false,
        "time_zone": "+08:00",
        "uid": "脱敏",
        "update_time": 1636038757,
        "uuid": "18470020e098061f055f"
      }
    ],
    "has_more": false,
    "last_row_key": "40258D368FA624402AFAE90A7AB1B140",
    "total": 1
  },
  "success": true,
  "t": 1636039025654
}

**Device functions (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/devices/functions**
结果如下：
{
  "result": [
    {
      "category": "kt",
      "devices": [
        "18470020e098061f055f"
      ],
      "functions": [
        {
          "code": "switch",
          "desc": "switch",
          "name": "switch",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "fan_speed_enum",
          "desc": "fan speed enum",
          "name": "fan speed enum",
          "type": "Enum",
          "values": "{\"range\":[\"low\",\"mid\",\"high\",\"auto\"]}"
        },
        {
          "code": "temp_set",
          "desc": "temp set",
          "name": "temp set",
          "type": "Integer",
          "values": "{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":32,\"step\":1}"
        },
        {
          "code": "mode",
          "desc": "mode",
          "name": "mode",
          "type": "Enum",
          "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\"]}"
        }
      ],
      "product_id": "EyZ4jHTX4agiWroA"
    }
  ],
  "success": true,
  "t": 1636039025794
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by Hanh94** [comment]
Not supported yet
