### ISSUE TITLE
I have the same problem. On the website Tuya api already offer to include some kind of plan for $ 1200 or go to the Trial Edition plan for 1 month. If they want money this will be the last TuYa device I bought.

### ISSUE THREAD

**Issue by bluntiless** [tuya/tuya-homebridge#152]
I have the same problem. On the website Tuya api already offer to include some kind of plan for $ 1200 or go to the Trial Edition plan for 1 month. If they want money this will be the last TuYa device I bought.

__Originally posted by @xrust83 in https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-961986033__

I had it working fine for a day or two and then it started showing the error code 2406. I resolved it by simply adding the correct Data centre code 44. I had it as 0 whilst it was working for a while, but it somehow decided to stop. You can simply change it in your Config.js and restart homebridge.

**Comment by xrust83** [comment]
it worked for me for 3 months, and yesterday or amused how you got error 1109, I went to the site and the developer mode, which was previously enabled, was in an incomprehensible state.  when you try to turn it on, it offers to pay money either for free but for 1 month.  after connecting, still nothing works.

**Comment by bluntiless** [comment]
It seems the Tuya plugin is a bit unstable and very sensitive about the credentials you enter. When creating the Cloud project, I think it is essential also that you choose only the Data centre appropriate to your location, as if you don't it will cause an error.
Not sure what the deal is with the Price plan of $1200, as I am on the Basic version and it is not asking me to upgrade to any other plan
<img width="565" alt="Screenshot 2021-11-06 at 11 25 28" src="https://user-images.githubusercontent.com/1809627/140608159-3b230344-3423-4597-a45f-a159490f9d46.png">
!
