### ISSUE TITLE
This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -2 exceeded minimum of 0

### ISSUE THREAD

**Issue by jeffwongcf** [tuya/tuya-homebridge#159]
Description:
Getting this error "This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -2 exceeded minimum of 0".

Device getting this error: 3x Smart Ceiling Fan Switch-DS02F

Running: homebridge-tuya-platform v1.5.0

[11/15/2021, 5:07:39 AM] [homebridge-tuya-platform] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -2 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[11/15/2021, 5:07:39 AM] [homebridge-tuya-platform] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -2 exceeded minimum of 0. See https://git.io/JtMGR for more info.
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebe0c5e94fe6438634agg3/commands, params = null, body = {"commands":[{"code":"fan_speed","value":100}]}, headers = {"t":"1636952868742","client_id":"srkgf5edaxb3uycykcwk","nonce":"92dde5e0-45d1-11ec-b2d4-570688335a3e","Signature-Headers":"client_id","sign":"B0B23CCD82600762CE9F3F71501DF0614835C4979905112CA2035301CAB7C180","sign_method":"HMAC-SHA256","access_token":"8bf4c82bd8edea34dbe87b69ead6aa7d","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebe0c5e94fe6438634agg3/commands, params = null, body = {"commands":[{"code":"switch_fan","value":true}]}, headers = {"t":"1636952868749","client_id":"srkgf5edaxb3uycykcwk","nonce":"92dde5e0-45d1-11ec-b2d4-570688335a3e","Signature-Headers":"client_id","sign":"39A881302EEB97028E4C4DA7D7E52CEE0B8AF9F0A69F8E21EA1C9BDF9DBFDAF5","sign_method":"HMAC-SHA256","access_token":"8bf4c82bd8edea34dbe87b69ead6aa7d","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1636952869006} path = /v1.0/devices/ebe0c5e94fe6438634agg3/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1636952869008} path = /v1.0/devices/ebe0c5e94fe6438634agg3/commands
TuyaOpenMQ onMessage: topic = cloud/token/in/57661b8db33809aa84ee16fa4ad7c33e, message = {"data":{"dataId":"9cce1510-faf5-40d2-953d-067a38bc12cb","devId":"ebe0c5e94fe6438634agg3","productKey":"tqas5nfwomvgvvhf","status":[{"1":true,"code":"switch_fan","t":"2194","value":true}]},"protocol":4,"pv":"2.0","sign":"a56c7761eaa5deb83f768c09ec77fa60","t":2194}
TuyaOpenMQ onMessage: topic = cloud/token/in/57661b8db33809aa84ee16fa4ad7c33e, message = {"data":{"bizCode":"offline","bizData":{"time":1636952881},"devId":"ebe0c5e94fe6438634agg3","productKey":"tqas5nfwomvgvvhf","ts":0},"protocol":20,"pv":"2.0","sign":"faf5f1ec874bdc4629a4a5f0a94e86e5","t":1636952881}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebe0c5e94fe6438634agg3/commands, params = null, body = {"commands":[{"code":"switch_fan","value":false}]}, headers = {"t":"1636952885326","client_id":"srkgf5edaxb3uycykcwk","nonce":"92dde5e0-45d1-11ec-b2d4-570688335a3e","Signature-Headers":"client_id","sign":"8401CA9FCE62BC7BD54F22A10782E6D756876EA4FB3915F46FA613DD3558AB38","sign_method":"HMAC-SHA256","access_token":"8bf4c82bd8edea34dbe87b69ead6aa7d","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"code":2001,"msg":"device is offline","success":false,"t":1636952885488} path = /v1.0/devices/ebe0c5e94fe6438634agg3/commands

**Comment by wills721** [comment]
Same issue for dimmer characteristics.  Seems like most characteristics are all messed up.
