### ISSUE TITLE
UnhandledPromiseRejectionWarning - ClientID

### ISSUE THREAD

**Issue by krunk84** [tuya/tuya-homebridge#16]
Trying to connect and I keep getting this error. 

(node:5604) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "client_id"

I have "accessID" configured like the the readme says to in the JSON.  Any thoughts?

**Comment by Hanh94** [comment]
You should create a new cloud project of **Smart Home PaaS** on the [Tuya IoT Platform](https://iot.tuya.com/cloud/) and linked devices with this project. For more information, see [Tuya IoT Platform Configuration Guide Using Smart Home PaaS](https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx).  If it still does not solve, please provide more detailed error information.
