### ISSUE TITLE
Homebridge and tuya platform, accesory is not visable

### ISSUE THREAD

**Issue by Smartproblems** [tuya/tuya-homebridge#160]
I tried to link my fan to homekit using homebridge and tuya platform plugin that uses tuya IoT Platform. I setup all how the manual said and homebridge doesn’t see any accesory.

**Comment by Jacko539** [comment]
I have the same issue. I can see that it’s logged in fine in the logs and it sees the device but it’s not showing under Accessories in Homebridge

**Comment by possebon** [comment]
I also has this situation, this is the info on log:

```
Adding: TV Luciane (infrared_tv / ebbxxxxxxxxxxxxxxxxxngr)
Adding: NET (infrared_tv / eb9xxxxxxxxxxxxxxx7e)
Adding: Ar-condicionado (infrared_ac / eb9xxxxxxxxxxt0)
Adding: HDMI (qt / eb1733ef737a850197hfmx)
Adding: TV Suite (infrared_tv / eb2xxxxxxxxxxxxxhk)
```

**Comment by Smartproblems** [comment]
I texted Tuya Support and they asked for device ID, i gave them the virtual ID from Tuya App and thats the answer: 
"Hello, I'm really sorry that this device cannot be used in HB for the time being. We will keep updating to make HB support more devices"

**Comment by Hucksleyy91** [comment]
Might have to use the google plugin to get it from google

**Comment by Smartproblems** [comment]
> Might have to use the google plugin to get it from google 

What do you mean?

**Comment by Hucksleyy91** [comment]
No need to do that I found out how to do it 

here is a video ! https://youtu.be/f8-7Hvrmh3Y

I have mine working I. Home assistant with tuya app about to try it out tonight on homekit

**Comment by Smartproblems** [comment]
> No need to do that I found out how to do it 
> 
> 
> 
> here is a video ! https://youtu.be/f8-7Hvrmh3Y
> 
> 
> 
> I have mine working I. Home assistant with tuya app about to try it out tonight on homekit 

Let me know how it went

**Comment by athew** [comment]
> No need to do that I found out how to do it
> 
> here is a video ! https://youtu.be/f8-7Hvrmh3Y
> 
> I have mine working I. Home assistant with tuya app about to try it out tonight on homekit

Hey Man, how is this video solved this issue for you? This video is showing to you how you can do the same but on HomeAssistant. I did everything the same until the HA install and I have the same issue. I see every devices succesfully added on log, but it's not visible at all on home devices (or on Homebridge accessories)

**Comment by DanAykroyd256** [comment]
Any updates guys? I'm having [a similar issue](https://github.com/tuya/tuya-homebridge/issues/208) with a breaker showing in the logs but not in accesories and I don't know how to add it there.
