### ISSUE TITLE
Can't control speed of TreatLife smart ceiling fan switch

### ISSUE THREAD

**Issue by k3r016** [tuya/tuya-homebridge#164]
**Describe the bug**
The fan speed of the smart ceiling fan switch cannot be controlled using HomeKit.

**Expected behavior**
HomeKit shows speed in percentage while the switch itself has levels 1-4. When turning the speed to 25%, it should be expected to switch to level 1.

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":28}]}, headers = {"t":"1638466209195","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"C5EAD2E0980B9AE64FBC01B54FDFC32ECE226E6DC80590A204B80B1894BBFB31","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"switch_fan","value":true}]}, headers = {"t":"1638466209211","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"1E41C4A8704FEA038265450B9AD9D858E2E7F94F01A919F14D736F8692DAF906","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466209623} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466209698} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":34}]}, headers = {"t":"1638466209840","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"8C99C51535089A1531922E754C31A75DEDBE58B32FF7FF9EE1FC1D09E862C3AD","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenMQ onMessage: topic = cloud/token/in/a74b0e3cf6293fa9e42a78c72147a31f, message = {"data":{"dataId":"6cecb40c-aada-413f-a2ff-d887c14484e1","devId":"ebbf6d3e53bb06e8f2blyv","productKey":"tqas5nfwomvgvvhf","status":[{"1":true,"code":"switch_fan","t":"1638466209","value":true}]},"protocol":4,"pv":"2.0","sign":"870a7f72ad44286a998b3f4421ff26ec","t":1638466209}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466210156} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":69}]}, headers = {"t":"1638466210459","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"04DBF923CA3483D2FF3CC68C8D385BFDFC7F85DC6AAFFBCEEA38D294BB3DC282","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466210848} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":77}]}, headers = {"t":"1638466211085","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"68FC9761C3D2CADCF04AC5C2ECCA379445BBD61725A85AF002C78DA45420913D","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"switch_fan","value":true}]}, headers = {"t":"1638466211101","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"7FC9B717FED96E72768B96E205A92EC9D3455ED24B2CC0B3B237EF9B244DA94F","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466211484} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466211506} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":94}]}, headers = {"t":"1638466211685","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"74928BE671FFED5ADA7A14DA42449339D5D2DB071DE23A96CEBAF071707C2E4C","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenMQ onMessage: topic = cloud/token/in/a74b0e3cf6293fa9e42a78c72147a31f, message = {"data":{"dataId":"780121d9-e2a0-4ac1-9714-68a1be6edf54","devId":"ebbf6d3e53bb06e8f2blyv","productKey":"tqas5nfwomvgvvhf","status":[{"1":true,"code":"switch_fan","t":"1638466211","value":true}]},"protocol":4,"pv":"2.0","sign":"d6769044743947f9d85118b3eb5461b1","t":1638466211}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466212115} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":100}]}, headers = {"t":"1638466212259","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"09BA3737541F62F4E4411543CFDF3779B5BF1FFFD7F8A59AAA9FB361BB705BE9","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466212616} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/command

**Additional context**
Add any other context or logs about the problem here.

**Comment by amrishraje** [comment]
I am also noticing this same issue with my treatlife fan speed control. Looks like this was closed in error without a fix.
