### ISSUE TITLE
Cloud API's are very slow. Please provide local LAN support

### ISSUE THREAD

**Issue by skavinvarnan** [tuya/tuya-homebridge#165]
**Describe the bug**
When the Light is turned off for a very long time(20 hours) and we make a request to turn on, there is a huge delay. After 5-6 on/off the delay is getting reduced.

**Expected behavior**
Please provide LAN support soon, as described here https://github.com/tuya/tuya-homebridge/issues/3#issuecomment-850769317

**Screenshots**

https://user-images.githubusercontent.com/5348524/144580934-44dca81e-7f46-4339-87bd-8bcb310d2662.mp4

**Comment by srapari** [comment]
any news of when the local lan support will be available?
