### ISSUE TITLE
Linking Tuya App account is not working

### ISSUE THREAD

**Issue by jansink** [tuya/tuya-homebridge#168]
**Describe the bug**
No success in adding my devices. Linking Tuya App account is not working for me.
When I scan the QR I always get QR code has expired. 
I'm in the correct data center: Central Europe Data Center

**Expected behavior**
My Tuya app account is linked and I can add my devices.

**Comment by MeesMaas** [comment]
I found this issue which might help you

[Issue](https://github.com/codetheweb/tuyapi/issues/396)

**Comment by jansink** [comment]
> I found this issue which might help you
> 
> [Issue](https://github.com/codetheweb/tuyapi/issues/396)

Thank you, but the suggested solution there is not working for me. I can't seem to add the suggested Smart Home Management.

**Comment by tehKnocker** [comment]
I'm having the exact same issue, so you're not alone! Can't find "Smart Home Management" either, I can however find "Smart Home Content Manage", but that's a $825 subscription!?

**Comment by jansink** [comment]
Yes I saw that subscription too, but I'm not sure if that's what is nessecerry

**Comment by SixEcho420** [comment]
I am having a similar issue as well. I have tired to scan the QR code with the Tuya App as well as the Smart Life App and my iPhone does not pick up the code. I checked and both apps have access to the camera. Not sure why I can't get the app linked to my project.

**Comment by watakushi-info** [comment]
I had a similar problem, but when I changed the data center based on the following text, the QR code worked. I don't know if this is helpful, but I just wanted to share the information.

https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb

> In line with your business needs, you can activate Microsoft Azure cloud services for your OEM apps and make the activation take effect. In this case, the app accounts that are created after the activation are allocated to either Eastern America Data Center or Western Europe Data Center. The app accounts that were created earlier than the activation cannot be used as expected.

> ! Important
> The countries or regions not listed in the following tables are mapped to Western America Data Center.

**Comment by tehKnocker** [comment]
![image](https://user-images.githubusercontent.com/62483335/146147439-daedb98e-edde-4a40-84c2-f44e9083a980.png)
As soon as I scan the QR, this happens. I tried all data centers.

**Comment by jansink** [comment]
> ![image](https://user-images.githubusercontent.com/62483335/146147439-daedb98e-edde-4a40-84c2-f44e9083a980.png) As soon as I scan the QR, this happens. I tried all data centers.

Yes, for me it's the same. Tried every data center.

**Comment by Hello-Huyang** [comment]
![企业微信截图_16399890686160](https://user-images.githubusercontent.com/94681986/146736580-d1bbbf1f-4a1b-4451-9e0d-ed4069021530.png)

**Comment by tehKnocker** [comment]
> ![企业微信截图_16399890686160](https://user-images.githubusercontent.com/94681986/146736580-d1bbbf1f-4a1b-4451-9e0d-ed4069021530.png)

Either way results in an instant "QR code has expired." - I just tried again.

**Comment by mgrrx** [comment]
I had the same issue yesterday. Just delete your OEM app that you used (in my case it was an app from woox), download the Smart Life App, register your devices there and then follow this "Link Tuya App Account" approach. These third party apps are basically not needed if I understand it correctly and they block you from creating this cloud project.

**Comment by jansink** [comment]
I still get that instant "QR code has expired". Thanks for the suggestion, but I don't have any OEM app, so nothing to uninstall there.

**Comment by Hanh94** [comment]
> ![企业微信截图_16399890686160](https://user-images.githubusercontent.com/94681986/146736580-d1bbbf1f-4a1b-4451-9e0d-ed4069021530.png)

Hi guys, This is correct, Please scan the QR code with the Tuya Smart app or Smart Life app And Choose the correct region, Please refer to [Link devices by app account](https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx#title-3-Link%20devices%20by%20app%20account)

**Comment by robinscheurwater** [comment]
I was struggling adding the app to the cloud. Tried all the above. Turns out I was using the wrong app?

There are several apps Nedis Smartlife, Tuya Smart, Smart life - Smart Living etc. They all have the option to scan the qr code. Only one app works tho.

You need com.tuya.smartlife on the playstore and I was using com.nedis.smartlife.

**Comment by VMrenato** [comment]
tuya makes things really complicated right? Why so many tuya apps around? unnecessary overcomplicating stuff
