### ISSUE TITLE
Switch with three buttons show only first button

### ISSUE THREAD

**Issue by henriqueciraolo** [tuya/tuya-homebridge#18]
When I have a Switch with three buttons, the plugin show me only one button and another two buttons is not showing.

**Comment by hwbai** [comment]
having the same issue here. Mine shows only the third switch

**Comment by Hanh94** [comment]
Hi @henriqueciraolo @hwbai , We support multi-switch in the latest version, please update and try again.

**Comment by hwbai** [comment]
I've updated the plug in to the latest version and can confirm on my end it's working perfectly. Thanks so much!

**Comment by henriqueciraolo** [comment]
Same here! Works fine!
