### ISSUE TITLE
Dehumidifiers

### ISSUE THREAD

**Issue by tgeorgiop** [tuya/tuya-homebridge#180]
Hello, are the dehumidifiers supported? Can I add my dehumidifier manually?

When I enable debug logs and restart homebridge, I can see inside homebridge logs the dehumidifier

> TuyaOpenAPI response: {"result":[{"category":"cs","devices":["14433575d8bfcXXXXX"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"fan_speed_enum","desc":"fan speed enum","name":"fan speed enum","type":"Enum","values":"{\"range\":[\"low\",\"mid\",\"high\"]}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"dehumidify\"]}"},{"code":"anion","desc":"anion","name":"anion","type":"Boolean","values":"{}"}],"product_id":"y3o1suysyi4nw96a"}],"success":true,"t":163984XXXXX} path = /v1.0/devices/functions
Adding: Juro-Pro Crystal (cs / 14433575d8bfXXXXXX)

but I cant see it in homebridge accessories or in the homekit app.

**Comment by ashley8bit** [comment]
Also having the same issue. Dehumidifier appears in log but is unavailable in HomeKit
