### ISSUE TITLE
Problem on installation

### ISSUE THREAD

**Issue by dpamping** [tuya/tuya-homebridge#181]
I´m trying to install this in hoobs and everything it's okay until this step:
homebridge -D -U ./config/ -P ./
it gives me this error:
-bash: homebridge: command not found

What should I do?

**Comment by Hanh94** [comment]
Hi @dpamping , Please [install Homebridge](https://github.com/tuya/tuya-homebridge/wiki/How-to-Use-Tuya-Homebridge-Plugin?_source=6a2b624bdb6dce83dd246e014ccd0bcf#prerequisites) first.

**Comment by dpamping** [comment]
But I want to install it on HOOBS, not on homebridge

**Comment by dpamping** [comment]
But I want to install it on HOOBS, not on homebridge
