### ISSUE TITLE
Logs don't comply with Homebridge logging system.

### ISSUE THREAD

**Issue by alangrafu** [tuya/tuya-homebridge#182]
**Describe the bug**
There are no logs for this plugin in Homebdrige, unless one enables debug logging, which seems to be simply a some `print` commands.

Other plugins show a log like

```
[12/19/2021, 7:47:38 PM] [PLUGIN_NAME] Some plugin message.
```

However tuya-homebridge doesn't log any message. When debug mode is enabled, it returns something like

```
TuyaOpenMQ onMessage: topic = cloud/token/in/TOKEN, message = {"data":{"dataId":"XXXXXX","devId":"YYYYY","productKey":"ZZZZZ","status":[{"3":63,"code":"temp_current","t":"1639972216","value":63}]},"protocol":4,"pv":"2.0","sign":"WWWWWWW","t":1639972216}

```

It would be great to have better logging without enabling debug mode, so it is possible to track normal behaviors regarding status, automations, etc.

**Comment by Hanh94** [comment]
Hi @alangrafu , Many users don't care or even want to see complex logs printed on the console. If you want to see logs every time you run a command, just turn debug on.

**Comment by rcoletti116** [comment]
> Many users don't care or even want to see complex logs printed on the console

I think this assumes a lot. Proper logging is important to many users. You don't need them all of the time, but when you do need them having them accessible and formatted properly helps a lot, especially if you run many homebridge plugins.

I do think you should update logging to follow conventional formatting, but leave complex logs under the debug setting (but formatted correctly). If you use the built in Homebridge logger you can easily address this.

**Comment by alangrafu** [comment]
Hi @Hanh94 I don't care about logs most of the time, but I do care about them when something breaks. I think this should be an easy fix, since Homebridge provides (AFAIR) logging capabilities.
