### ISSUE TITLE
3-Gang Light Switch - Enable option to override device type.

### ISSUE THREAD

**Issue by AxelDreemurr** [tuya/tuya-homebridge#186]
**Describe the bug**
The plugin doesn't have an option to override the device type, as is impossible right now to properly assign each gang of the switch to a different room in HomeKit, which would be possible by overriding the device type in the plugin settings, so, for example, you could make a Light Switch (a 3 gang one) show up as 3 individual Lights in HomeKit. 

**Expected behavior**
I'd expect to see an option on the plugin settings to override the device type, allowing me to change the device type from a Switch to a Light.

**Comment by dpamping** [comment]
very much needed please addddd :)
