### ISSUE TITLE
ECONNRESET ErroNo -4077 or incorrect processinf

### ISSUE THREAD

**Issue by Mojinxo** [tuya/tuya-homebridge#190]
Recently setup Tuya IoT app and now get one of two results on restarting the service.

result 1

all devices are dumped in the debug log but the main log in homebridge says it can’t find devices.

results 2 (more common)

I see an ECONNRESET error with an axios connection dump. On examination it’s clear the result json is empty.

in setting this up I’ve experiencing the same issue as others, the video guide and text guides show a different set of services in the Tuya cloud config. Rather than adding device management as a services I’m having to add IoT Core. That service only has a 30 days trial, rather than the q year quoted.

I’m disappointed that the official docs don’t seem to be getting updated to reflect how this should be configured and that there’s nothing more than an axios dump and no meaningful analysis of the response.

**Comment by kot-lex** [comment]
@Mojinxo have you managed to solve the issue? Experiencing something similar at the moment.

**Comment by Mojinxo** [comment]
Sadly Not. I had to just abandon it.DreOn 22 May 2023, at 22:37, Aleksei Chernov ***@***.***> wrote:﻿
@Mojinxo have you managed to solve the issue? Experiencing something similar at the moment.

**Comment by kot-lex** [comment]
Figured it out, it seems like my ISP is blocked by Tuya API for some reason. 
Tried to connect over VPN and it works now.
