### ISSUE TITLE
Any plan to include more product types?

### ISSUE THREAD

**Issue by Aekung** [tuya/tuya-homebridge#2]
Firstly, thank you very much for the official homebridge plugin from tuya developer, the community really appreciates the hard work. 

However, since the current state is only supporting Outlets and Lights, are there any plan to include the covers, pet-feeder, valve, door lock, and all other broad range of products from Tuya? It looks really promising and hopefully it will gain support on more devices the soonest.

If it's getting support on wider range of products, I might really have to consider switching to Tuya Platform on many of my incoming smart home devices.

Thank you.

**Comment by Hanh94** [comment]
Thank you for your feedback. We will support nearly 12 categories of Tuya devices in the next version by the end of May. Please look forward to it.

**Comment by Aekung** [comment]
> Thank you for your feedback. We will support nearly 12 categories of Tuya devices in the next version by the end of May. Please look forward to it.

Any possibility you could review all of those 12 product types that would be available by the end of may?

Thanks.

**Comment by Hanh94** [comment]
It's already on schedule.

**Comment by Hanh94** [comment]
We showed you how to expand Accessory in the README, so if you're interested, you can join us.

**Comment by Stetocasa** [comment]
Any possibility to see blind motor at the end of may?
This plug-in can show also Smart life ?

**Comment by codyc1515** [comment]
> It's already on schedule.

I think the question was which category of devices will be supported in the 12?

**Comment by codyc1515** [comment]
Any update on the new products?

> Any possibility to see blind motor at the end of may?

You can already do this with the other Tuya plugins… but I agree - having an officially supported one would be ideal.

**Comment by zlinoliver** [comment]
Hi @codyc1515 @Aekung @Stetocasa , we have released a new version of Tuya homebridge plugin two days ago, add more products support:

- Light: Supports Tuya Wi-Fi light devices.
- Outlet: Supports Tuya Wi-Fi Outlet devices.
- Smoke Sensor: Supports Tuya smoke sensor devices.
- Switch: Supports Tuya switch devices.
- Heater: Support Tuya heater devices.
- Garage Door: Support Tuya smart garage door devices.
- Fan: Support Tuya fan devices.
- Air Purifier: Support Tuya air purifier devices.

Please check the github repo and try it. You are welcome to help develop more drivers to support more Tuya PBT products by following this tutorial: https://developer.tuya.com/en/demo/tuyahomebrigeplugin, thanks!

**Comment by Stetocasa** [comment]
Thanks for quoting, really appreciated.
Unfortunately for me I just have a blind motor in Tuya.
Awaiting future implementation because Tuya web plug-in has an issue with motor status

**Comment by bosco90** [comment]
Will Oil diffusers/Humidifiers like deviceID: 0216444084f3eb40ba82 (productID: nOtxbOfJNNVSatZD) be supported? 
In the IoT Platform is shown as "Other" product type but HomeKit does support this kind of product as Humidifier.

Thanks!

**Comment by Aekung** [comment]
Great to see the expanded category of accessories. I'm still looking forward to the blind and winder cover type.

Hope it would be added in the next version.

PS. Thanks for mentioning about the update.

**Comment by zlinoliver** [comment]
Hi @bosco90 , thanks for the feedbacks, as the Humidifiers is in our standard instruction set list: https://developer.tuya.com/en/docs/iot/f?id=K9gf45rjel6x5, we will add it to our new product support roadmap. If you are interested, you can follow this tutorial [Use and Develop Tuya Homebridge Plugin](https://developer.tuya.com/en/demo/tuyahomebrigeplugin) to develop the plugin driver together.

Hi @Aekung ，we will also consider to support blind and winder cover type too, thanks for the feedbacks!

**Comment by Hanh94** [comment]
Hi @bosco90 ,We have already supported the Outlet Accessory with the category name of 'cz' , which supports the power off and on.

**Comment by bosco90** [comment]
Thats great, but both of them doesn't show up in HomeKit, I've checked the log file but this tropic is not appropriate for this, I'll open a new issue with the details.

**Comment by Aekung** [comment]
Hi guys,

Are there any plan for the window coverings type? I wish to switch to this plugin but right now I'm still sticking with Tuya Lan and Tuya Web since it offers blinds and window covering type.

Really looking forward to the support of this category.

**Comment by PeterKiwi** [comment]
Hi, are you planning to support WiFi door sensors in the near future?

**Comment by Hanh94** [comment]
> Hi, are you planning to support WiFi door sensors in the near future?

Hi @PeterKiwi ,We already support the Door Window(category:mcs) Sensor in the latest version.

**Comment by PeterKiwi** [comment]
Okay thanks.  I'll take another look at my end

**Comment by eddiedsouza** [comment]
Can you'll please provide an ETA for Tuya Door Locks .... These products are hot selling products in the market. Would appreciate some information.

**Comment by Jens-Wymeersch** [comment]
@zlinoliver to include pet-feeder support ?
