### ISSUE TITLE
Anyway to Disable the Output in Logs?

### ISSUE THREAD

**Issue by kylewhirl** [tuya/tuya-homebridge#20]
Would be nice if it was possible to set an option in the config such as disableLogs: “true” so that the log output would not be shown every 2 seconds

**Comment by gileswells** [comment]
@Hanh94 Using `this.log.debug()` for items that don't always need to be visible is the best way I've found to give control to the users. Unless they launch homebridge with debug enabled those messages will just get discarded.

**Comment by Hanh94** [comment]
> @Hanh94 Using `this.log.debug()` for items that don't always need to be visible is the best way I've found to give control to the users. Unless they launch homebridge with debug enabled those messages will just get discarded.

Hi @gileswells ,Thank you for your feedback.
We will make adjustments in the next release.

**Comment by Hanh94** [comment]
Hi @kylewhirl @gileswells , We already support dynamic logging in v1.1.4, please update the plugin
