### ISSUE TITLE
deviceType gyd is not supported/showing in Homekit

### ISSUE THREAD

**Issue by mamante** [tuya/tuya-homebridge#205]
Created a Tuya IoT platform account and added Tuya Smart App creditentials successfully.

Configured & loaded Tuya plugin into Homebridge successfully.

Can see the device is online via Tuya IoT & can be controlled via Tuya Smart app but nothing is displayed in Homebridge accessories nor within HomeKit dashboard itself.

Product is a Globe Electric-branded Smart Ambient Light with Motion Detection (https://www.homedepot.com/p/Globe-Electric-Wi-Fi-Smart-Ambient-LED-Night-Light-with-Motion-Detection-Multi-Color-Changing-RGB-Tunable-White-50239/318109990)

Log info:

{"category":"gyd","devices":["eb53284fd1452615e4wxjh"], "functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\"]}"},{"code":"bright_value","desc":"bright value","name":"bright value","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value","desc":"temp value","name":"temp value","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"colour_data","desc":"colour data","name":"colour data","type":"Json","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"String","values":"{\"maxlen\":255}"},{"code":"device_mode","desc":"device mode","name":"device mode","type":"Enum","values":"{\"range\":[\"auto\",\"manual\"]}"},{"code":"cds","desc":"cds","name":"cds","type":"Enum","values":"{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}"},{"code":"pir_sensitivity","desc":"pir sensitivity","name":"pir sensitivity","type":"Enum","values":"{\"range\":[\"low\",\"middle\",\"high\"]}"},{"code":"pir_delay","desc":"pir delay","name":"pir delay","type":"Integer","values":"{\"unit\":\"s\",\"min\":5,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"switch_pir","desc":"switch pir","name":"switch pir","type":"Boolean","values":"{}"},{"code":"standby_time","desc":"standby time","name":"standby time","type":"Integer","values":"{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"},{"code":"standby_bright","desc":"standby bright","name":"standby bright","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"}],"product_id":"pqkaolg30iffoqqp"}

**Comment by BillSobel** [comment]
This is still an open issue as of 7/30/22, type gyd doesn't show in Homebridge.

**Comment by mamante** [comment]
@BillSobel is correct. This has not been resolved & should remain open. However, work has been which might move towards resolving it. See the following:

https://github.com/tuya/tuya-homebridge/pull/247

https://github.com/tuya/tuya-homebridge/pull/170

**Comment by mamante** [comment]
> Stale issue. we will close the issue soon. If this issue has not been resolved, please update the issue and contact us in time.

Wondering if there is any progress on this issue. It was marked as closed but some work has been that needs attention. Please see the following:

https://github.com/tuya/tuya-homebridge/pull/247

https://github.com/tuya/tuya-homebridge/pull/170
