### ISSUE TITLE
Doesn't find door sensor

### ISSUE THREAD

**Issue by f-aglins** [tuya/tuya-homebridge#207]
The plugin is working just fine with my other devices, but it doesn't recognize my door sensor. Is there a configuration I can do to add this sensor?

**Comment by jayhabs** [comment]
Any luck getting your door sensor to work.  I am having the same problems.

**Comment by f-aglins** [comment]
Yes. I don't know why, but a couple of days ago I did a reboot on the system and they appeared on my Home app.
