### ISSUE TITLE
Ceiling Lamp issues

### ISSUE THREAD

**Issue by o485** [tuya/tuya-homebridge#21]
I'm having some problems controlling my ceiling lamp. The ceiling light device category "xdd" is not recognized as a light. After overriding the category in the config the color temperature works, however warm and cold are inverted. The brightness is being read out correctly but cannot be adjusted. Homekit simply says "no response" when I try to adjust it and reverts to the old setting.

**Comment by Hanh94** [comment]
Hi @o485 , This is due to the fact that the 'xdd' device was not created 'LightAccessory' instance after the plugin service was started, so as you can see HomeKit says "no response", the category of lights we currently support are: 'dj', 'dd', 'fwd'.   'xdd' will soon be supported

**Comment by o485** [comment]
This is the error when trying to adjust the brightness:
[homebridge-tuya-platform] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside write handler for characteristic: Cannot read property 'max' of undefined. See https://git.io/JtMGR for more info.

**Comment by Hanh94** [comment]
Hi @o485 , Thank you for your feedback.
We have optimized the plugin. Please update and try again.
If you encounter any problems in the process of use, Please timely feedback with us, we will be the first time to respond.

**Comment by o485** [comment]
Okay, I'm on 1.1.6 now still getting the same error and the light temperature is also still inverted. 
Some more info on my lamp:
{"result":{"category":"xdd","functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value","desc":"bright value","name":"bright value","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value","desc":"temp value","name":"temp value","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"scene_data","desc":"scene data","name":"scene data","type":"String","values":"{\"maxlen\":255}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"String","values":"{\"maxlen\":255}"}]},"success":true,"t":1622808072829} path = /v1.0/devices/XXX/functions

**Comment by Hanh94** [comment]
Hi @o485 , We've fixed  **'max' of undefined**
We don't understand this problem about **the light temperature is also still inverted.**, Please open the debuglog, set the light temperature, and check the temperature value in the log is consistent with the performance of the light. 
Like this:
`TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/devices/xxx/commands, params = null, body = {"commands":[{"code":"temp_value_v2","value":977}]}, headers = {"t":"1622821984705","client_id":"xxx","sign":"xxx","sign_method":"HMAC-SHA256","access_token":"xxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.0.6"}
`

**Comment by o485** [comment]
Thank you very much, the brightness works perfectly now. The values in the log correspond with the performance of the light, 1000 being the coldest white and 0 the warmest. However, if I select the warmest white in the apple home app it shows up in the logs as 1000 instead of 0.

**Comment by Hanh94** [comment]
Hi @o485 , Select the corresponding position in the Home App to get the corresponding value, as follows:
**lowest value 0**  
<img src="https://images.tuyacn.com/app/Hanh/lowest.jpg" width="30%"><br>

**highest value 1000**  
<img src="https://images.tuyacn.com/app/Hanh/highest.jpg" width="30%"><br>

**Comment by o485** [comment]
Yeah, the warmest setting in the home app results in a value of 1000 which corresponds to the coldest setting on the actual lamp

**Comment by Hanh94** [comment]
> Yeah, the warmest setting in the home app results in a value of 1000 which corresponds to the coldest setting on the actual lamp

Specific devices may behave differently, depending on the embedded code of your device, if you select the lowest point in the Home app and get the lowest value, and you send the command to the lowest value, then this is correct.

**Comment by o485** [comment]
Okay, but the colours are correct in the Tuya app

**Comment by o485** [comment]
Can someone else with a ceiling lamp confirm that this is an issue with my specific lamp?

**Comment by Hanh94** [comment]
Hi @o485 , Since we haven't received your reply for a long time, we think our latest version should have solved your problem. We will close this issue first. If there is any problem, you can contact us at any time.
