### ISSUE TITLE
Scenes not pulling through 

### ISSUE THREAD

**Issue by MattRoe84** [tuya/tuya-homebridge#210]
**Describe the bug**
In the smart life app i have RGBW lights these have music and scenes as options, these are not available when i open home app. Also as a work around when i create one of the scenes or music events as a tap to run this still does not pull through to the home app  

**Expected Behaviour**
I should have the option in home app to set the scene or music event or at least as a work around beable to pull through the tap to runs that are in the smart life app

**Comment by xyz667** [comment]
Scenes of the Tuya devices (pre-defined by the manufacturer or self-created using the Tuya app) are not available at all via your plugin, so this issue can not be resolved just like that.
The homebridge-tuya-web plugin provides switches to select these Tuya-scenes. Please incorporate something similar to tuya-homebridge. Thanks a lot!

**Comment by MattRoe84** [comment]
Hi does it enable you to be able to do the scenes where it will move through multiple colours etc

Thanks

Matt

On 20 May 2022, at 11:06, xyz667 ***@***.***> wrote:

﻿

Scenes of the Tuya devices (pre-defined by the manufacturer or self-created using the Tuya app) are not available at all via your plugin, so this issue can not be resolved just like that.
The homebridge-tuya-web plugin provides switches to select these Tuya-scenes. Please incorporate something similar to tuya-homebridge. Thanks a lot!

**Comment by xyz667** [comment]
> Hi does it enable you to be able to do the scenes where it will move through multiple colours etc

Yes the (no longer supported?) plug-in homebridge-tuya-web lets you select scenes defined in the Tuya app (somewhat clumsy with switches to enable the scenes). 

tuya-homebridge unfortunately does not seem to have any support for Tuya-device-scenes.

**Comment by UberEclectic** [comment]
Bump.
