### ISSUE TITLE
Tuya devices not showing up in Home App

### ISSUE THREAD

**Issue by freemanuk** [tuya/tuya-homebridge#219]
I have installed the Tuya Platform plugin, configured the IoT Dev platform and scan the QR code to Homekit, but no device is showing up in Home app.

I have double checked that all my devices were listed in the Dev Platform and I can see the bridge added in the Home app under Home settings. However, it is not showing up in Homebridge Log. Is there anything that I have missed out?

**Comment by jurekjure** [comment]
Same issue here ... cannot get tuya platform plugin  - on Hoobs (Hoobs certified plugin) to show any devices. There is no error shown.

**Comment by Anzic23** [comment]
Same issue

**Comment by maaper** [comment]
Same issue, can not see any devices. All parameters are properly configured, but I get no accessories on homebridge.
This is part of the log:

```
[2/13/2022, 12:20:24 AM] Homebridge v1.4.0 (HAP v0.10.0) (TuyaPlatform) is running on port 47848.
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1644708025274} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.
```

Thanks in advance!

**Comment by Anzic23** [comment]
@maaper you have "permission deny" check [here ](https://github.com/tuya/tuya-homebridge#tuya-openapi-login-error-code)

**Comment by GitPuffy** [comment]
> I have installed the Tuya Platform plugin, configured the IoT Dev platform and scan the QR code to Homekit, but no device is showing up in Home app.
> 
> I have double checked that all my devices were listed in the Dev Platform and I can see the bridge added in the Home app under Home settings. However, it is not showing up in Homebridge Log. Is there anything that I have missed out?

When I configured this plugin through Homebridge and provided "US" as my country the plugin failed.  When I went back and configured my country as "1" it worked as expected.  Maybe this is the same issue for you.

**Comment by michelec4gno** [comment]
same issue

**Comment by vmoreno71** [comment]
Same issue. I tried the country code with 34 (Spain). No. problem in Hoobs, but no accessories detracted, neither in hoops or HomeKit

**Comment by Muxxx** [comment]
I just attempted to set this up myself and none of my lights are showing up. It even shows in the homebridge logs that the accessories were supposedly added, but they don't appear as accessories. It just keeps saying that every time I restart my homebridge server.

**Comment by onichan88** [comment]
I'm with the same problem, the logs from tuya shows the device, and the changes of the device when I turn the light on/off, but it doesn't show in the home app.

**Comment by Muxxx** [comment]
I’ve given up on this plug-in, as clearly the devs have too.

**Comment by onichan88** [comment]
> I’ve given up on this plug-in, as clearly the devs have too. 

Have you tried another plugin with success?

**Comment by Muxxx** [comment]
I have moved away from HB specifically because of the lack of Tuya support. Both the Tuya official and Tuya LAN plugins are terrible. I switched to Home Assistant and use the native HomeKit integration (in HA) to present my devices back to my apple ecosystem. I use this plugin specifically with HA - https://github.com/make-all/tuya-local

**Comment by ADCLBA** [comment]
Hello

Same issue for me
I tried to use this plugin in Homebridge, but no accessory created.

I check and every information of the device is visible in the log, I can see :
Adding: Temperature Humidity Sensor (wsdcg / xxxxxxxxxxxxxx)
Adding: Multi-mode Gateway (wg2 / xxxxxxxxxxxxxx)

**Comment by calamarzo** [comment]
@onichan88 please, can you elaborate more on this? I think this is my issue. Where did you add the category details? thanks!


> The main problem is that your device category maybe is not implemented in the code, or is newer and they have to add the accessory to the code. I have a ceiling fan with light, with device category 'fsd' and I had to add it by my own. Is like a 'fs' (ceiling fan without light, already coded) but with minor changes, but if you don't make that changes, it will not show in accessories nor homekit.

**Comment by onichan88** [comment]
Hi @calamarzo in the main file, I added the "fsd" type, and in the file of ceiling fan I made some minor changes. I propose some changes to this github, still waiting acceptance. If you want to try, you cam use my github fork of this github. I also forked another github to use the ceiling fan locally and it worked!

**Comment by rodolvbg** [comment]
> Hi [@calamarzo](https://github.com/calamarzo) in the main file, I added the "fsd" type, and in the file of ceiling fan I made some minor changes. I propose some changes to this github, still waiting acceptance. If you want to try, you cam use my github fork of this github. I also forked another github to use the ceiling fan locally and it worked!

I think your say #192 and #255. Applying these changes in my local tuya-homebridge works for me. I hope those PRs merge soon and get updated

**Comment by cb675** [comment]
> > Hi [@calamarzo](https://github.com/calamarzo) in the main file, I added the "fsd" type, and in the file of ceiling fan I made some minor changes. I propose some changes to this github, still waiting acceptance. If you want to try, you cam use my github fork of this github. I also forked another github to use the ceiling fan locally and it worked!
> 
> I think your say [#192](https://github.com/tuya/tuya-homebridge/pull/192) and [#255](https://github.com/tuya/tuya-homebridge/pull/255). Applying these changes in my local tuya-homebridge works for me. I hope those PRs merge soon and get updated

@onichan88 @rodolvbg , I have Hoobs devices and my fans listed as fsd category. I’m new to this. How do I manually fix my category type so my fans show up?

**Comment by rodolvbg** [comment]
> @onichan88 @rodolvbg , I have Hoobs devices and my fans listed as fsd category. I’m new to this. How do I manually fix my category type so my fans show up?

@cb675 
What worked for me was:
1- Find the installation location of the homebridge-tuya-platform plugin.
2- Access the files changed in the aforementioned PRs (`index.js` and `lib/fanv2_accessory.js`), make the changes specified in those PRs, or download exactly those files from those branches and replace them on your local machine.
3- Restart the homebridge service, and it should now work.
I don't know if the explanation is clear.

**Comment by cb675** [comment]
> > [@onichan88](https://github.com/onichan88) [@rodolvbg](https://github.com/rodolvbg) , I have Hoobs devices and my fans listed as fsd category. I’m new to this. How do I manually fix my category type so my fans show up?
> 
> [@cb675](https://github.com/cb675) What worked for me was: 1- Find the installation location of the homebridge-tuya-platform plugin. 2- Access the files changed in the aforementioned PRs (`index.js` and `lib/fanv2_accessory.js`), make the changes specified in those PRs, or download exactly those files from those branches and replace them on your local machine. 3- Restart the homebridge service, and it should now work. I don't know if the explanation is clear.

Thanks for responding. Sounds like I will have to figure it out. I don’t know if Hoobs device will let me do this since I’m not running HB on my PC directly but the Hoobs bridge. All this is new to me so hopefully I can find a step by step to walk me through it.

**Comment by rodolvbg** [comment]
> Thanks for responding. Sounds like I will have to figure it out. I don’t know if Hoobs device will let me do this since I’m not running HB on my PC directly but the Hoobs bridge. All this is new to me so hopefully I can find a step by step to walk me through it.

If you can access the device remotely, I guess using commands, make the changes using nano directly and that's it. At least that's what I did.

**Comment by cb675** [comment]
> > Thanks for responding. Sounds like I will have to figure it out. I don’t know if Hoobs device will let me do this since I’m not running HB on my PC directly but the Hoobs bridge. All this is new to me so hopefully I can find a step by step to walk me through it.
> 
> If you can access the device remotely, I guess using commands, make the changes using nano directly and that's it. At least that's what I did.

Good thing I’m good at promoting ChatGPT because it walked me step by step on how to do it. I had to make sure the raw PR path was correct and I was able to modify the files on the Hoobs device. Accessories are now in HomeKit. Thank you so much for the inspiration.
