### ISSUE TITLE
The two-button dimmer switch in the Apple Home app is shown as a one-button dimmer switch.

### ISSUE THREAD

**Issue by norbertwalczak** [tuya/tuya-homebridge#221]
**Describe the bug**
The two-button dimmer switch in the Apple Home app is shown as a one-button dimmer switch.
In the Tuya Smart Life app, the switch is shown as a two-button. Two-button dimmer.
In The Tuya IoT Platform Cloud -> Development -> in my project -> Devices -> Device -> Debug: is shown as:

Device Information
Product Name :2CH Zigbee Dimmer Module
Device ID: ***
Product Category: tgkg
Device Status: Online
Activated At: 2022-02-08 18:15:30

JSON Instructions:
[
  {
    "code": "switch_led_1",
    "value": false
  },
  {
    "code": "bright_value_1",
    "value": 301
  },
  {
    "code": "brightness_min_1",
    "value": 10
  },
  {
    "code": "brightness_max_1",
    "value": 1000
  },
  {
    "code": "countdown_1",
    "value": 0
  },
  {
    "code": "switch_led_2",
    "value": false
  },
  {
    "code": "bright_value_2",
    "value": 301
  },
  {
    "code": "brightness_min_2",
    "value": 11
  },
  {
    "code": "brightness_max_2",
    "value": 1000
  },
  {
    "code": "countdown_2",
    "value": 0
  },
  {
    "code": "relay_status",
    "value": "memory"
  }
]

**Expected behavior**
I'd like to see both buttons in the Apple Home app

**Screenshots**
Tuya Smart Life App:
https://share.icloud.com/photos/0e8Sb2hnj7v2utVNgc9TmepmA
https://share.icloud.com/photos/0eeAVzDpvPBnESYp94tyhZSlA

Home App:
https://share.icloud.com/photos/0e1MyJzuCulc7TmfapMszOegA

Homebridge:
https://www.icloud.com/iclouddrive/0ebzUVb580_vXwHDkEKd4jrtg#Zrzut_ekranu_2022-02-8_o_21.04

**Comment by norbertwalczak** [comment]
Hi Again :)

Logs from homebrige:
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1644354363161","client_id":"xxx","nonce":"xxx","Signature-Headers":"client_id","sign":"xxx","sign_method":"HMAC-SHA256","access_token":"xxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1644335111,"biz_type":18,"category":"wfcon","create_time":1644335111,"icon":"smart/icon/ay1562803410690AUgvL/733677b615ea45d953bcf2a0c6d69da5.png","id":"bf30358bd59f46e2cayein","ip":"xxx","lat":"50.1037","local_key":"xxx","lon":"18.5311","model":"JMWZG1","name":"Zigbee Smart Gateway","online":true,"owner_id":"50640510","product_id":"lieerjyy6l4ykjor","product_name":"无线智能小网关（JMWZG1）","status":[],"sub":false,"time_zone":"+01:00","uid":"eu1644334735403XYIin","update_time":1644354124,"uuid":"6fecd6a3f02cd298"},{"active_time":1644340530,"biz_type":18,"category":"tgkg","create_time":1644340530,"icon":"smart/icon/ay1533257659316XGZOd/0ec94b819043620c021b7b0c7747bc78.jpg","id":"xxx","ip":"","lat":"50.1037","local_key":"xxx","lon":"18.5311","model":"ZT3L","name":"**Dimmer2Gang**","node_id":"xxx","online":true,"owner_id":"50640510","product_id":"wdexaypg","product_name":"**2CH Zigbee Dimmer Module**","status":[{"code":"**switch_led_1**","value":true},{"code":"bright_value_1","value":301},{"code":"brightness_min_1","value":10},{"code":"brightness_max_1","value":1000},{"code":"countdown_1","value":0},{"code":"**switch_led_2**","value":true},{"code":"bright_value_2","value":301},{"code":"brightness_min_2","value":11},{"code":"brightness_max_2","value":1000},{"code":"countdown_2","value":0},{"code":"relay_status","value":"memory"}],"sub":true,"time_zone":"+01:00","uid":"xxx","update_time":1644350339,"uuid":"xxx"}],"has_more":false,"last_row_key":"xxx","total":2},"success":true,"t":1644354363517} path = /v1.0/iot-01/associated-users/devices

As you can see, there are two buttons in the logs. But only one in accessories :(

**Comment by norbertwalczak** [comment]
Teh issue has not been resolved.

**Comment by conradgrobbelaar** [comment]
I have the same issue with a Wifi Dimmer Module - 2 (Model: QS-WIFI-D02-TRIAC-2C)
<img width="801" alt="image" src="https://user-images.githubusercontent.com/122429713/211733348-10ab21e3-e331-4bd1-8463-cc6d2853c36e.png">
only displays as one switch in HomeKit

![](https://tuya-smarthome.co.za/wp-content/uploads/2019/10/smart-wifi-dimmer-module-2-gang-tuya-smartlife.jpg)

Could you kindly assist?
Many Thanks
