### ISSUE TITLE
Support for Tuya based gateways but sold by other companies

### ISSUE THREAD

**Issue by AssetBurned** [tuya/tuya-homebridge#222]
it would be great if the plugin would also support gateways/clouds that are sold by other companies, but that are in reality just rebranded Tuya products. Such as the SilverCrest IAN 341809_1910 SGWZ 1 A1 as sold by Lidl in Europe.

**Comment by MrBackbeat** [comment]
The ELESION platform used by Pearl.de would be another one to consider. 

https://www.elesion.com/

**Comment by MrBackbeat** [comment]
This issue has not been solved yet.
To sum it up: In the Tuya plug-in you can choose different PaaS platform, currently Tuya and Smart Life.
The request here is to add more of the third-party platforms based on Tuya like ELESION etc

**Comment by TheBassfly** [comment]
Same for me.

**Comment by MrBackbeat** [comment]
This issue is still not solved. Does anybody work on this plug in at all?
