### ISSUE TITLE
PIR sensor support

### ISSUE THREAD

**Issue by AssetBurned** [tuya/tuya-homebridge#225]
**Describe the bug**
Looking at https://github.com/tuya/tuya-homebridge/wiki/Supported-Tuya-Device-Types?_source=6a1b8046224626e798190c06532c8be2 there is no support for PIR sensors (human motion sensor). 

**Expected behavior**
Having them supported

**Additional context**
General support not just for one very specific model, therefore no details about an individual model.

**Comment by mamante** [comment]
There has been work done to correct this issue but they have not been merged. See the following:

https://github.com/tuya/tuya-homebridge/pull/247

https://github.com/tuya/tuya-homebridge/pull/170
