### ISSUE TITLE
Tuya Wifi Curtain Motor not responding

### ISSUE THREAD

**Issue by patricktws90** [tuya/tuya-homebridge#226]
I have added Tuya Wifi Motor model BCM700D-TY01 into Tuya App. Consequently checked the homebridge accessories page. 

The curtain motor appeared on the homebridge accessories page and also exposed in homekit Home app. 

However, there’s no response on the command to open or close the curtain through the Homebridge web page and also Home app. 

The homebridge webpage shows the Curtain Closing status. And it doesn’t command any action on the actual devices. Same goes for the Home app.

Attached picture below. I have tried restarting raspberry pi 4 and gateway but to no avail. 

On the Tuya App, the command for the curtain is completely fine working 100% as it is. Just not on homebridge and home app. 

I checked the tuya iot platform and the curtain device is online. 

Please advice. 

![7C4416DC-AFCD-4FA3-9267-16820BEC9541](https://user-images.githubusercontent.com/100032205/154804908-cce6c796-41c8-41c3-8041-e7941f27500b.jpeg)

**Comment by Hoobs-User** [comment]
I have the same problem with the Wifi curtain motor model BCM700D WiFi (added in the Smart Life app)
