### ISSUE TITLE
pet feeder not showing

### ISSUE THREAD

**Issue by d4nm0** [tuya/tuya-homebridge#229]
I made the configuration as said in the jar. but my feedeer does not appear on homebridge
I don't see any error in the console
{
    "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "options": {
        "lang": "en",
        "countryCode": 33,
        "username": "dan.xxxxxxxxxxxxxxxxxxxail.com",
        "password": "xxxxxxxxxxxxxxxxxxx",
        "accessId": "t4qkxxxxxxxxxxxxxxlc",
        "accessKey": "xxxxxxxxxxxxxxxxxxx8e",
        "projectType": "2",
        "appSchema": "tuyaSmart",
        "debug": true
    }
}

**Comment by Myth0zz** [comment]
Hello, I have my Petfeeder from Tuya app and I see it. I cannot add it to my hoobs. Can you help?

**Comment by AvivWn** [comment]
Any news about supporting pet feeder?
