### ISSUE TITLE
Heaters not working

### ISSUE THREAD

**Issue by zacharykeeping** [tuya/tuya-homebridge#23]
I have 3 Kogan heaters that I have connected to my Tuya account which are grabbed successfully by this plugin, however all their temperatures show as 0 degrees and can't be controlled at all.

<img width="502" alt="Screen Shot 2021-06-03 at 7 16 33 pm" src="https://user-images.githubusercontent.com/11418832/120620407-4bc5d580-c4a0-11eb-828d-65514083c313.png">
<img width="785" alt="Screen Shot 2021-06-03 at 7 17 01 pm" src="https://user-images.githubusercontent.com/11418832/120620418-4d8f9900-c4a0-11eb-968a-97b1eeb77c90.png">

**Comment by zlinoliver** [comment]
Hi @zacharykeeping sorry for the unpleasant experience of the existing plugin, we have received your feedbacks on the heater driver, will continue to improve it. The existing drivers are mainly developed to attract more developers to try our new plugin, and collaborate with us to improve it, contribute more drivers for PBT products. 

It's not perfect for now, but we believe that with the help of the Homebridge community, it will become more powerful soon :)

**Comment by Hanh94** [comment]
Hi @zacharykeeping ,
We have support for heaters in the latest version.
The following functions are supported: Active, CurrentTemp, Lock, Speed, Swing, TempSet.
Please update and try again. If you encounter any problems during use, please contact us in time.

**Comment by jackwburger** [comment]
Hi,

I have a Silvercrest smart ceramic fan heater which has heating HIGH, LOW and COOL. Also has swing horizontal and vertical. There is NO Temperature setting or reading.

Can this be supported?
https://www.independent.co.uk/extras/indybest/house-garden/household-appliances/lidl-silvercrest-fan-heater-b1804724.html

**Comment by Hanh94** [comment]
> Hi,
> 
> I have a Silvercrest smart ceramic fan heater which has heating HIGH, LOW and COOL. Also has swing horizontal and vertical. There is NO Temperature setting or reading.
> 
> Can this be supported?
> https://www.independent.co.uk/extras/indybest/house-garden/household-appliances/lidl-silvercrest-fan-heater-b1804724.html

Hi @jackwburger ,sorry for the late reply.
Please provide detailed device information so that we can better support this category. You can submit a new device supported issue.
