### ISSUE TITLE
Devices missing

### ISSUE THREAD

**Issue by argandgauss** [tuya/tuya-homebridge#238]
**Describe the bug**
Temperature & Humidity sensors, PIR sensors, flooding sensors, security system

**Expected behavior**
Expose those sensors.

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/iot-01/associated-users/devices**

like this:
{
      "active_time": 1623229189,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1560491945,
      "icon": "smart/product_icon/cz.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "30.30286857361191",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "120.0639743842656",
      "model": "",
      "name": "Living Room Socket",
      "online": false,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name": "Switch Product",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2343
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

**Device functions (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/devices/functions**
Same **device Id**, like this:
{
    "category":"cl",
    "devices":[
        "aaaaaaaaaaa"
    ],
    "functions":[
        {
            "code":"control",
            "desc":"control",
            "name":"control",
            "type":"Enum",
            "values":"{\"range\":[\"open\",\"stop\",\"close\"]}"
        },
        {
            "code":"percent_control",
            "desc":"percent control",
            "name":"percent control",
            "type":"Integer",
            "values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
        },
        {
            "code":"control_back",
            "desc":"control back",
            "name":"control back",
            "type":"Boolean",
            "values":"{}"
        }
    ],
    "product_id":"xaabybja"
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by sadanro100** [comment]
Same problem here... these "Thank you for your feedback, we will solve this issue soon" messages all over this repo are really not making me very hopeful

**Comment by ProgrammingMyLife** [comment]
> Same problem here... these "Thank you for your feedback, we will solve this issue soon" messages all over this repo are really not making me very hopeful

I think I found the issue. I tried using my smart circular lamp to HomeKit using home bridge but it isn't supported. [See supported devices](https://github.com/tuya/tuya-homebridge/wiki/Supported-Tuya-Device-Types?_source=6a1b8046224626e798190c06532c8be2)

My LED strips do work though, and they are supported

**Comment by sadanro100** [comment]
@ProgrammingMyLife that's not the reason... my device (Door sensor) is listed as compatible but not shown in homebridge

**Comment by ashish-tandon** [comment]
Can I please raise this issue or feature request? 
The Temp and Humidity Sensor please include them
