### ISSUE TITLE
Temp reprting - Incorrect

### ISSUE THREAD

**Issue by GucciGuantes** [tuya/tuya-homebridge#239]
Any device that reports Degrees Fahrenheit shows incorrect reading in HomeKit. HomeKit assumes all devices translate Degrees Fahrenheit to Degrees Celsius, so when the device is imported there is no conversion causing a really high temperature reading.
![Heater](https://user-images.githubusercontent.com/103915993/163753507-44ac084a-73fd-4ca7-b55a-d69303732a59.png)

**Comment by enz1ey** [comment]
Still an issue

**Comment by haliccatalin** [comment]
This issue is present, should be reopened

**Comment by GucciGuantes** [comment]
This is indeed still an issue.
