### ISSUE TITLE
Identical devices, different behaviors

### ISSUE THREAD

**Issue by rcoletti116** [tuya/tuya-homebridge#24]
I have 2 bulbs that are identical to each other (same manufacturer, model, came in a pack together). 

These two bulbs load, along with all of my devices in the API response. However the Creating New Accessory has different results for these two identical bulbs.

These two identical bulbs show up with different functions in HomeKit.
One bulb loads as it should with control for Power, Brightness, and Color Temperature. 
```
[03/06/2021, 10:09:31] [TuyaPlatform] Adding: GN-BW231-999 2 (dj / ebfc757038252d0e55kbth)
[03/06/2021, 10:09:31] [TuyaPlatform] Creating New Accessory ebfc757038252d0e55kbth
LightAccessory statusArr. [
  { code: 'switch_led', value: true },
  { code: 'bright_value', value: 202 },
  { code: 'temp_value', value: 102 }
]
LightAccessory functionArr. [
  {
    code: 'switch_led',
    desc: 'switch led',
    name: 'switch led',
    type: 'Boolean',
    values: '{}'
  },
  {
    code: 'bright_value',
    desc: 'bright value',
    name: 'bright value',
    type: 'Integer',
    values: '{"min":25,"scale":0,"unit":"","max":255,"step":1}'
  },
  {
    code: 'temp_value',
    desc: 'temp value',
    name: 'temp value',
    type: 'Integer',
    values: '{"min":0,"scale":0,"unit":"","max":255,"step":1}\t'
  }
]
```

The 2nd only loads with Power (On/Off capability). As you can see in the logs below, this one throws a warning LightAccessory functionArr. undefined and results in an unhandled exception.

```
[03/06/2021, 10:09:31] [TuyaPlatform] Adding: GN-BW231-999 3 (dj / eb40e5c0e95fc073cadhpm)
[03/06/2021, 10:09:31] [TuyaPlatform] Creating New Accessory eb40e5c0e95fc073cadhpm
LightAccessory statusArr. [
  { code: 'switch_led', value: true },
  { code: 'bright_value', value: 43 },
  { code: 'temp_value', value: 56 }
]
LightAccessory functionArr. undefined
(node:5018) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at LightAccessory.getFunction (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/light_accessory.js:212:36)
    at LightAccessory.refreshAccessoryServiceIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/light_accessory.js:53:29)
    at new LightAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/light_accessory.js:30:10)
    at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:125:27)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:84:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:5018) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Hanh94** [comment]
Hi @rcoletti116 ,Thank you very much for your feedback. 
This discovery is very important for us, and we will solve this problem soon.

**Comment by Hanh94** [comment]
Hi @rcoletti116 ,Thank you for your support of our plugin. We have optimized the plugin. Please update and try again.
If you encounter any problems in the process of use, Please timely feedback with us, we will be the first time to respond.

**Comment by rcoletti116** [comment]
No, did not work. In fact, now none of my devices are added.

**Comment by Hanh94** [comment]
> ~No, did not work. In fact, now none of my devices are added.~
> 
> I had to reset everything, but it did work. Steps were unpair the plugin (child bridge), remove devices from Homebridge cache, restart, re-pair.

In general, plugin updates just need reconfiguring the child Bridge, perhaps because previously unavailable plugin cached Tuya devices in HomeBridge, and the Tuya devices were not created when the new plugin service started.

**Comment by rcoletti116** [comment]
> In general, plugin updates just need reconfiguring the child Bridge, perhaps because previously unavailable plugin cached Tuya devices in HomeBridge, and the Tuya devices were not created when the new plugin service started.

I don't exactly agree. The child bridge should only need a restart. There may be some odd caching behavior occurring in the plugin. I'll close this one out though since it is solved.
