### ISSUE TITLE
Plug in no longer works at all for me 

### ISSUE THREAD

**Issue by SCOTTS948** [tuya/tuya-homebridge#246]
**Describe the bug**
Plug in worked flawlessly for almost year. Now it doesn't work at all. Devices respond within Home app and on Homebridge accessory page, but actual devices don't respond. Eventually i uninstalled the plug in and reinstalled and now devices won't show up in Homekit at all. 

**Expected behavior**

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/iot-01/associated-users/devices**

like this:
{
      "active_time": 1623229189,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1560491945,
      "icon": "smart/product_icon/cz.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "30.30286857361191",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "120.0639743842656",
      "model": "",
      "name": "Living Room Socket",
      "online": false,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name": "Switch Product",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2343
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

**Device functions (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/devices/functions**
Same **device Id**, like this:
{
    "category":"cl",
    "devices":[
        "aaaaaaaaaaa"
    ],
    "functions":[
        {
            "code":"control",
            "desc":"control",
            "name":"control",
            "type":"Enum",
            "values":"{\"range\":[\"open\",\"stop\",\"close\"]}"
        },
        {
            "code":"percent_control",
            "desc":"percent control",
            "name":"percent control",
            "type":"Integer",
            "values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
        },
        {
            "code":"control_back",
            "desc":"control back",
            "name":"control back",
            "type":"Boolean",
            "values":"{}"
        }
    ],
    "product_id":"xaabybja"
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by faraz** [comment]
this happens for me as well. its intermittent

**Comment by vietde** [comment]
same problem for me as well

**Comment by damanveen** [comment]
same issue for me as well.

**Comment by 1aranzant** [comment]
same here.

**Comment by xrust83** [comment]
True

**Comment by isthismarvin** [comment]
same problem here... no devices are added, why isnt this fixed already? as of now the plugin is useless.

**Comment by WirthmU** [comment]
Same here - no reaction from the developers.

**Comment by isthismarvin** [comment]
> Same here - no reaction from the developers.

So it does work for me again: 

remove every single device from the tuya app, disconnect the app from Cloud-Developerproject in the App Settings (Account and Security Tab), then add every device again (re-pair), in the iOT add your App Link again by scanning the QR code. Setup Homebridge-Tuya again. It should work!

**Comment by josemmc95** [comment]
Same problem. It doesn’t work and if you have cached devices they do nothing when you turn it on/off.

any solution?

**Comment by VTDARKSIM** [comment]
Same for me. HomeKit automations stopped working weeks ago, so I tried toggling the devices (lights) through the Home app; the status changed in the Home app, but the devices themselves did not change state. I opened the SmartLife app and could turn them on/off from there. A month or so later the plugin is still not working. I went to iot.tuya and verified everything is set up correctly, still no dice. I even tried setting up the HomeBridge plugin as a child bridge. The Home app now sees the Tuya bridge, but there are no devices associated with it in the Home app, and the SmartLife devices have disappeared from the Home app.

**Comment by josemmc95** [comment]
I have fixed it by clearing all child bridges from Homebridge Settings and "Unpair Bridges / Cameras / TVs / External Accessories". I removed all of them and i paired them again, and changing mDNS Advertirse from "Bonjour HAP" to "Avahi".

I don't know how much time it'll continue to work, but it has been working for two days...
