### ISSUE TITLE
Homebridge Verified

### ISSUE THREAD

**Issue by donavanbecker** [tuya/tuya-homebridge#25]
@Hanh94 Would you be interested in applying for [Homebridge Verified](https://github.com/homebridge/verified) Program?

**Comment by zlinoliver** [comment]
Hi @donavanbecker ，yes, we are glad to apply for the Homebridge Verified Program, this tuya-homebridge repo is maintained by our Tuya Developer Team, we will help to add more features and improve this plugin continuously.  Also, we hope more developers can try our new plugin, and collaborate with us to improve it, contribute more drivers for PBT products.

**Comment by zlinoliver** [comment]
Hi @donavanbecker , we have created a issue in Homebridge Verified Github repo, here is the link: https://github.com/homebridge/verified/issues/314
