### ISSUE TITLE
No accessory created

### ISSUE THREAD

**Issue by ADCLBA** [tuya/tuya-homebridge#257]
Hello, 
I tried to use this plugin in Homebridge, but no accessory created.
I check and every information of the device is visible in the log, I can see : 
Adding: Temperature Humidity Sensor (wsdcg / xxxxxxxxxxxxxx)
Adding: Multi-mode Gateway (wg2 / xxxxxxxxxxxxxx)

But after trying to restart Homebridge, no accessory is created on the accessory dashboard.

Could you help me ? 
Other information available on demand

Thank you by advance

Best regards

**Comment by mradulpandey** [comment]
I verified same,the device is not visible in Homebridge Accessories UI(but visible and working in Homekit), seems like a UI issue...
