### ISSUE TITLE
Unable to control BLE devices through Wifi mesh adapter

### ISSUE THREAD

**Issue by realbrianosaurus** [tuya/tuya-homebridge#263]
I have a mix of wifi and BLE lights and switches, and a BLE gateway mesh. I am able to control BLE devices from the Smartlife app. The BLE devices are visible to the Homebridge plugin, but it cannot control them and does not get status updates.

Should I be able to control the BLE devices through the plugin?

**Comment by slawnz** [comment]
I have same issue. When will it be fixed? Is tuya homebridge support abandoned?

**Comment by realbrianosaurus** [comment]
Still wondering if this will be fixed. My tuya bulbs are useless
