### ISSUE TITLE
Handling offline devices

### ISSUE THREAD

**Issue by rcoletti116** [tuya/tuya-homebridge#27]
Requesting you look at how devices are handled when they are offline and unreachable. Roadmap item. 

Right now the plugin renders offline devices as if they are online. Controlling the offline devices in HomeKit appears as if it is working, but it’s not. The status is not accurate. 

I understand you are working on making the plugin more robust, so I’m just making you aware for tracking in your roadmap - not asking for an immediate fix.

**Comment by zlinoliver** [comment]
Hi @rcoletti116 , thank you for your suggestion. We will seriously consider your suggestion and add to our roadmap items. As we have limited R&D resource, you are welcome to cooperate with us to improve the plugin too.
