### ISSUE TITLE
Contact Sensor state change does not show in Homekit

### ISSUE THREAD

**Issue by t829913** [tuya/tuya-homebridge#270]
I have a Tuya Bluetooth hub (branded Grid Connect) with a contact sensor connected to it. This is one of the supported devices. The device itself shows up in Homekit but the state does not change. I also have it linked to Alexa and Alexa DOES receive the state changes almost instantly... it's just Homekit that does not... is this a known issue, when will it be resolved? Thanks.

**Comment by 1aranzant** [comment]
Same issue with a WiFi contact sensor. It is stuck in the "Open" state. 
(issue's only with the homebridge plugin, both on homekit and on the homebridge's UI accessory tab)

**Comment by mmaslen** [comment]
Any update on this issue please?

**Comment by TaylordFed** [comment]
This would be very helpful as I have been experiencing the same problem with no fix.
