### ISSUE TITLE
Ecostrad iQ Ceramic heater not connecting to HomeKit 

### ISSUE THREAD

**Issue by Kl1923** [tuya/tuya-homebridge#271]
**Describe the bug**
I have a Ecostrad iQ ceramic heating device. I see the API returns the two heaters. into the terminal back from API call. but does not show up in HomeKit.. Heating is listed as being supported in HomeKit but does not seem to work for these. 

**Expected behavior**
Should be able to control in HomeKit 

**Screenshots**

**Device info (please complete the following information, which can be found in [

[8/18/2022, 5:27:41 PM] [TuyaPlatform] Launched child bridge with PID 70017
[8/18/2022, 5:27:41 PM] Registering platform 'homebridge-tuya-platform.TuyaPlatform'
[8/18/2022, 5:27:41 PM] [TuyaPlatform] Loaded homebridge-tuya-platform v1.5.0 child bridge successfully
[8/18/2022, 5:27:41 PM] Loaded 0 cached accessories from cachedAccessories.0E90595D530E.
Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":44,"username":"***@icloud.com","password":"****","schema":"smartlife"}, headers = {"t":"1660840061307","client_id":"****","nonce":"ae4eddf1-1f12-11ed-9c67-9bfbf4a181d8","Signature-Headers":"client_id","sign":"2E2A9BDFD8804949E68F80B2211D1E757B796CB6A90476207DF76D1E88DE7D4C","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
[8/18/2022, 5:27:41 PM] Homebridge v1.5.0 (HAP v0.10.2) (TuyaPlatform) is running on port 56790.
TuyaOpenAPI response: {"result":{"access_token":"8503083f6e1d65b452fe9778ec4a1faf","expire_time":7200,"platform_url":"https://openapi.tuyaeu.com","refresh_token":"7655c3d9faab1f022ff8fb671006fef1","uid":"eu1660760501309l3BhG"},"success":true,"t":1660840061503,"tid":"ae6a68f91f1211eda7c7bedb040359fa"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1660840061541","client_id":"s4dwudyynmxtt3u77ksf","nonce":"ae4eddf1-1f12-11ed-9c67-9bfbf4a181d8","Signature-Headers":"client_id","sign":"E076F1942F225100315CD3C28BD424C670A3BBAA1993B4CC7F905C7256D0AD6D","sign_method":"HMAC-SHA256","access_token":"8503083f6e1d65b452fe9778ec4a1faf","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1660761611,"biz_type":18,"category":"wk","create_time":1660761611,"icon":"smart/icon/ay1555980033059u7AZh/ba7583b4e979c101b0188c3dfb65715e.png","id":"bf6aeb815d4882c771qjlu","ip":"185.219.110.38","lat":"52.1934","local_key":"f13f9afd0ed490bf","lon":"0.1332","model":"80J","name":"radiator main room **scholars","online":true,"owner_id":"63714659","product_id":"9pxlzsayjzp4aml3","product_name":"Electric radiator  电暖器","status":[{"code":"switch","value":false},{"code":"mode","value":"person_infrared_ray"},{"code":"temp_set","value":295},{"code":"temp_current","value":230},{"code":"temp_correction","value":0},**{"code":"child_lock","value":false}],"sub":false,"time_zone":"+01:00","uid":"eu1660760501309l3BhG","update_time":1660827150,"uuid":"eebd3241c0d0051b"},{"active_time":1660761934,"biz_type":18,"category":"wk","create_time":1660761934,"icon":"smart/icon/ay1555980033059u7AZh/ba7583b4e979c101b0188c3dfb65715e.png","id":"bf60a55694d09cd840lgw7","ip":"185.219.110.38","lat":"52.1934","local_key":"94e32f43e6ebe382","lon":"0.1332","model":"80J","name":"**Scholars bedroom radiator**  **2","online":true,"owner_id":"63714659","product_id":"9pxlzsayjzp4aml3","product_name":"**Electric radiator  电暖器","status":**[{"code":"switch","value":false},{"code":"mode","value":"hot"},{"code":"temp_set","value":280},**{"code":"temp_current","value":215},{"code":"temp_correction","value":0},{"code":"child_lock","value":false}],"sub":false,"time_zone":"+01:00","uid":"eu1660760501309l3BhG","update_time":1660827145,"uuid":"748df2b3b61936b5"}],"has_more":false,"last_row_key":"6E6C77A3F06C72E00CD39A4BC775E760","total":2},"success":true,"t":1660840061661,"tid":"ae815f8c1f1211ed9ade628099f16ede"} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/functions, params = {"device_ids":"bf6aeb815d4882c771qjlu,bf60a55694d09cd840lgw7"}, body = null, headers = {"t":"1660840061668","client_id":"s4dwudyynmxtt3u77ksf","nonce":"ae4eddf1-1f12-11ed-9c67-9bfbf4a181d8","Signature-Headers":"client_id","sign":"B12961E585BA9F96626314E6C3E6D074FCE1AC26442AA4449B5985643982CEC7","sign_method":"HMAC-SHA256","access_token":"8503083f6e1d65b452fe9778ec4a1faf","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":[{"category":"wk","devices":["bf6aeb815d4882c771qjlu","bf60a55694d09cd840lgw7"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"hot\",\"eco\",\"cold\",\"auto\"]}"},{"code":"temp_set","desc":"temp set","name":"temp set","type":"Integer","values":"{\"unit\":\"℃\",\"min\":70,\"max\":300,\"scale\":1,\"step\":5}"},{"code":"temp_correction","desc":"temp correction","name":"temp correction","type":"Integer","values":"{\"unit\":\"℃\",\"min\":-5,\"max\":5,\"scale\":0,\"step\":1}"},{"code":"child_lock","desc":"child lock","name":"child lock","type":"Boolean","values":"{}"}],"product_id":"9pxlzsayjzp4aml3"}],"success":true,"t":1660840061793,"tid":"ae9635711f1211eda7c7bedb040359fa"} path = /v1.0/devices/functions
**Adding: radiator main room scholars (wk / bf6aeb815d4882c771qjl2)**
**Adding: Scholars bedroom radiator  2 (wk / bf60a55694d09cd840lg27)**
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-03/open-hub/access-config, params = null, body = {"uid":"eu1660760501309l3BhG","link_id":"ae519d10-1f12-11ed-9c67-9bfbf4a181d8","link_type":"mqtt","topics":"device","msg_encrypted_version":"1.0"}, headers = {"t":"1660840061806","client_id":"s4dwudyynmxtt3u77ksf","nonce":"ae4eddf1-1f12-11ed-9c67-9bfbf4a181d8","Signature-Headers":"client_id","sign":"987B0D6DE5CCA71D09432E277E6EE2AB6BE0CCFA9E7E86A1E059A2F2583293AB","sign_method":"HMAC-SHA256","access_token":"8503083f6e1d65b452fe9778ec4a1faf","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"client_id":"cloud_5c7b8c7a199b14cb69d71909f5f9dd31","expire_time":7200,"password":"aac7dcb1e4c74bde9bc5a4ac315c2650","sink_topic":{"device":"cloud/token/out/{device_id}"},"source_topic":{"device":"cloud/token/in/ebe82c7ef1acb77fa26ee0c2e90afa59"},"url":"ssl://m1.tuyaeu.com:8883","username":"cloud_ebe82c7ef1acb77fa26ee0c2e90afa59"},"success":true,"t":1660840061900,"tid":"aeaabda91f1211ed974c8e5328223f65"} path = /v1.0/iot-03/open-hub/access-config
TuyaOpenMQ connecting: ssl://m1.tuyaeu.com:8883
TuyaOpenMQ connected

**Additional context**
Add any other context or logs about the problem here.

**Comment by Kl1923** [comment]
Can someone advise if I am doing something wrong ?   I see the [Ecostrad iQ Ceramic W] is supported on Tuya local app homeassisant.

**Comment by Kl1923** [comment]
Any update even to confirm this is not working ?

**Comment by Kl1923** [comment]
https://github.com/make-all/tuya-local 

Works on Tuya local... Any chance can work on this HomeKit version ?

**Comment by Heckie** [comment]
I’ve also got these heaters. I think the issue is that they are listed in Tuya as thermostats (code WK) rather than heaters. I’ve got them displaying in HomeKit using Tuya Web plugin but they don’t function very well. Would love to see support for WK in the official plugin.

**Comment by Kl1923** [comment]
Thanks for letting me know. Good to know someone else has same issue. I got mine working by setting up home assistant instance then doing a link from home assistant to Homebridge. Works quite well if you need an alternative, but longwinded set up.

**Comment by Heckie** [comment]
Yeah I tried Home Assistant and will likely go back to that for the time being. I got it working with just the Tuya and HomeKit plug-ins. No need for homebridge in the setup and tbh the heaters are the only smart devices I have that aren’t native HomeKit. I’d prefer to use homebridge longer term though so will be keeping an eye on the development of the plugins.

**Comment by Kl1923** [comment]
If you can share how you got the web version working I’d be much obliged, with the heaters.  I’ve had time to play around with the heaters given the drop in temp this week—  noticed the home assistant integration won’t actually turn on the heat. Just change the target temps. Maybe down to the issue you noted is listed as thermostats not heaters.

**Comment by Heckie** [comment]
@Kl1923 you want to get this fork of the plug-in as the dev is working on heater support (at my request) so get involved in testing/debugging the Ecostrad heaters with me
https://github.com/0x5e/homebridge-tuya-platform/discussions/2#discussioncomment-3980335
