### ISSUE TITLE
Could you please add Smoke Detector Alarm Siren as Switch to turn it on/off from homebridge/homekit 

### ISSUE THREAD

**Issue by rionshin** [tuya/tuya-homebridge#273]
Could you please expose the Smoke detector alarm Siren as  Switch , so we can use the Siren for  different automations and turn it on/off. 
There is different Tuya Alarm Sirens - do you plan to add it as supported devices ? 

TuyaOpenAPI response: 
{"result":
{"devices":[{
"active_time":1661250638,
"biz_type":18,
"category":"ywbj",
"create_time":1661250638,
"icon":"smart/icon/ay1493973351453DFfgc/f6064faafdd1682c1d1c6acb16af3333.png","
id":"bfe3d71a9170be0ac6ofap",
"ip":"78.83.12*.*","lat":"42.6372",
"local_key":"*****",
"lon":"23.3326",
"model":"ES63TW5V3",
"name":"Smoke Detector 2",
"online":true,
"owner_id":"60599146",
"product_id":"wbgpn2atrnicvsio",
"product_name":"烟雾探测器V3",
"status":[
{"code":"smoke_sensor_status","value":"normal"},
{"code":"lifecycle","value":true,
{"code":"battery_state","value":"low"},{"code":"muffling","value":false}],
"sub":false,"time_zone":"+03:00",
"uid":"eu1657099313494NJiYp",
"update_time":1661250640,
"uuid":"f1a22763ba745e48"}, 
 

{"result":[
{"category":"ywbj",
"devices":["bfe3d71a9170be0ac6ofap","bfbb9e1ffc5781d7f86gus"],
"functions":[{"code":"muffling","desc":"muffling","name":"muffling","type":"Boolean","values":"{}"}],"product_id":"wbgpn2atrnicvsio"}],"success":true,"t":1661253996794,"tid":"73113ca522d611ed86b7bed3cc205f4d"}

**Comment by mmaslen** [comment]
Any chance of making this available too please?
