### ISSUE TITLE
Treatlife fan speed control does not work via HomeKit

### ISSUE THREAD

**Issue by amrishraje** [tuya/tuya-homebridge#274]
Describe the bug
The fan speed of the smart ceiling fan switch cannot be controlled using HomeKit.

Expected behavior
HomeKit shows speed in percentage while the switch itself has levels 1-4. When turning the speed to 25%, it should be expected to switch to level 1. However, the switch completely ignores all speed control requests coming from Homekit. Just switch ON - OFF functionality works as expected. 

Screenshots

**Device info (please complete the following information, which can be found in [log]
(https://github.com/tuya/tuya-TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":28}]}, headers = {"t":"1638466209195","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"C5EAD2E0980B9AE64FBC01B54FDFC32ECE226E6DC80590A204B80B1894BBFB31","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"switch_fan","value":true}]}, headers = {"t":"1638466209211","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"1E41C4A8704FEA038265450B9AD9D858E2E7F94F01A919F14D736F8692DAF906","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466209623} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466209698} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":34}]}, headers = {"t":"1638466209840","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"8C99C51535089A1531922E754C31A75DEDBE58B32FF7FF9EE1FC1D09E862C3AD","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenMQ onMessage: topic = cloud/token/in/a74b0e3cf6293fa9e42a78c72147a31f, message = {"data":{"dataId":"6cecb40c-aada-413f-a2ff-d887c14484e1","devId":"ebbf6d3e53bb06e8f2blyv","productKey":"tqas5nfwomvgvvhf","status":[{"1":true,"code":"switch_fan","t":"1638466209","value":true}]},"protocol":4,"pv":"2.0","sign":"870a7f72ad44286a998b3f4421ff26ec","t":1638466209}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466210156} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":69}]}, headers = {"t":"1638466210459","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"04DBF923CA3483D2FF3CC68C8D385BFDFC7F85DC6AAFFBCEEA38D294BB3DC282","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466210848} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":77}]}, headers = {"t":"1638466211085","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"68FC9761C3D2CADCF04AC5C2ECCA379445BBD61725A85AF002C78DA45420913D","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"switch_fan","value":true}]}, headers = {"t":"1638466211101","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"7FC9B717FED96E72768B96E205A92EC9D3455ED24B2CC0B3B237EF9B244DA94F","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466211484} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466211506} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":94}]}, headers = {"t":"1638466211685","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"74928BE671FFED5ADA7A14DA42449339D5D2DB071DE23A96CEBAF071707C2E4C","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenMQ onMessage: topic = cloud/token/in/a74b0e3cf6293fa9e42a78c72147a31f, message = {"data":{"dataId":"780121d9-e2a0-4ac1-9714-68a1be6edf54","devId":"ebbf6d3e53bb06e8f2blyv","productKey":"tqas5nfwomvgvvhf","status":[{"1":true,"code":"switch_fan","t":"1638466211","value":true}]},"protocol":4,"pv":"2.0","sign":"d6769044743947f9d85118b3eb5461b1","t":1638466211}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466212115} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com/, path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/commands, params = null, body = {"commands":[{"code":"fan_speed","value":100}]}, headers = {"t":"1638466212259","client_id":"amxqhrvab51bbqh2srgz","nonce":"7169e2c0-5395-11ec-88f2-4bdc3302ebb3","Signature-Headers":"client_id","sign":"09BA3737541F62F4E4411543CFDF3779B5BF1FFFD7F8A59AAA9FB361BB705BE9","sign_method":"HMAC-SHA256","access_token":"c76df42ce352ca2f1d3a09c54ada6e9f","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1638466212616} path = /v1.0/devices/ebbf6d3e53bb06e8f2blyv/command

**Comment by k3r016** [comment]
I have the same issues as well. Please add support for fan speed of Treatlife fan switches. Thanks!

**Comment by CTLuber** [comment]
I've spent the last 3 months trying to figure out how to make it work, and I finally got it. I forked this repository and changed the fan lib so that it will work. In the home app if you change the fan's speed to 25% it goes to fan speed level 1, 50% corresponds to level 2, 75% to level 3, and 100% to level 4. The way I got it to work was uninstalling the Original Tuya plugin, restarting Homebridge, then by clicking the three dots in the top right hand corner I opened terminal and from there do the command "npm add github:ctluber/tuya-homebridge" and install the plugin that way! Let me know if it works for y'all.

**Comment by amrishraje** [comment]
Awesome, thanks for sharing. I did the exact same thing long time ago. Should have posted it here to save your time. Sorry for not posting it sooner. In case you want to look at my code, it’s on my Github. amrishraje/tuya-homebridge: Homebridge custom plugin for controlling Powered by Tuya (PBT) devices in HomeKit. This plugin is officially maintained by the Tuya Developer Team.github.comRegards,AmrishOn Oct 16, 2022, at 8:48 PM, CTLuber ***@***.***> wrote:﻿
I've spent the last 3 months trying to figure out how to make it work, and I finally got it. I forked this repository and changed the fan lib so that it will work. In the home app if you change the fan's speed to 25% it goes to fan speed level 1, 50% corresponds to level 2, 75% to level 3, and 100% to level 4. The way I got it to work was uninstalling the Original Tuya plugin, restarting Homebridge, then by clicking the three dots in the top right hand corner I opened terminal and from there do the command "npm add github:ctluber/tuya-homebridge" and install the plugin that way! Let me know if it works for y'all.

**Comment by CTLuber** [comment]
Use amrishraje's fork instead of mine! I removed switch capabilities from mine for my own convenience.

**Comment by CTLuber** [comment]
Use amrishraje's fork instead of mine, I'm removing switch capabilities for my own convenience!

**Comment by amrishraje** [comment]
Issue hasn’t been resolved yet

**Comment by donjalex2** [comment]
@amrishraje, I tried to install your plugin using: "npm add github:amrishraje/tuya-homebridge" Only 1 out of my 5 treatlife fans gives me the fan "speed to 25% it goes to fan speed level 1, 50% corresponds to level 2, 75% to level 3, and 100% to level 4".  All the other fans are on and off only.  I don't understand.
