### ISSUE TITLE
Adding  WIFI smart CO alarm(

### ISSUE THREAD

**Issue by Kohle81** [tuya/tuya-homebridge#275]
Hi,

it is possible to add these sensor?

Product Category:  cobj

Thanks for this great plugin!

**Comment by 0x5e** [comment]
Added in [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) 1.6.0-beta.8.

**Comment by Kohle81** [comment]
@0x5e 

thanks for this information.

Will this function also be transferred to this plugin?

**Comment by 0x5e** [comment]
@Kohle81 yes, when most functions become stable, it will be merged.
Currently due to the large modification, it need some feedbacks to prove it's stable.

**Comment by Kohle81** [comment]
if I want to test now, does this plugin have to be uninstalled?  So all automations for previous tuya devices would be deleted from Homekit, or how does this work?Am 23.10.2022 um 11:15 schrieb gaosen ***@***.***>:﻿
@Kohle81 yes, when most functions become stable, it will be merged.
Currently due to the large modification, it need some feedbacks to prove it's stable.

**Comment by 0x5e** [comment]
> if I want to test now, does this plugin have to be uninstalled?  So all automations for previous tuya devices would be deleted from Homekit, or how does this work?Am 23.10.2022 um 11:15 schrieb gaosen ***@***.***>:﻿
> @Kohle81 yes, when most functions become stable, it will be merged.
> Currently due to the large modification, it need some feedbacks to prove it's stable.
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Oh I didn't thought about this. Let me try. Maybe it won't be removed.

**Comment by 0x5e** [comment]
@Kohle81 I don't have ipad to setup automation. I tried install official plugin, restart, then uninstall official plugin, and install my fork version, then restart. from the log I can see the accessory cache is still there. I think homebridge won't remove the cache and automations during the reinstall.
