### ISSUE TITLE
Adaptive Lighting

### ISSUE THREAD

**Issue by donavanbecker** [tuya/tuya-homebridge#28]
Are there plans to add adaptive lighting?

[hap-nodejs adaptive lighting](https://developers.homebridge.io/HAP-NodeJS/classes/adaptivelightingcontroller.html)

**Comment by Hanh94** [comment]
Hi @donavanbecker ,Thank you for your suggestion. 
Our team will seriously consider your suggestion and review whether it is really suitable for us.

**Comment by ElphaX** [comment]
Hey @Hanh94 , could you get Leo to check my last correspondence, could assist you in adaptive lighting support in the future. tyty

**Comment by Hanh94** [comment]
> Hey @Hanh94 , could you get Leo to check my last correspondence, could assist you in adaptive lighting support in the future. tyty

OK

**Comment by donavanbecker** [comment]
unstable
