### ISSUE TITLE
Devices added in homekit log but not shown in plugin or home app

### ISSUE THREAD

**Issue by eugenetjw** [tuya/tuya-homebridge#281]
Hello all,

I have a couple of RF hubs from tuya for my outdoor zip tracks. I have the account on iot and have linked my app and I can see the devices on it. Following the id and access key, I can see the devices seemingly added during home bright logs but the devices are not showing up on home app, anyone had similar issues?

TuyaOpenAPI response: {"result":[],"success":true,"t":xxx,"tid":"xxx"} path = /v1.0/devices/functions
Adding: Living room hub (wnykq / xx)
Adding: Master room hub (wnykq / xx)
Adding: Living room zip (rf_roller_blind / xx)
Adding: Service yard (rf_roller_blind / xx)
Adding: Master balcony (rf_roller_blind / xx)

TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-03/open-hub/access-config, params = null, body = {"uid":"xx","link_id":"xx","link_type":"mqtt","topics":"device","msg_encrypted_version":"1.0"}, headers = {"t":"xx","client_id":"xx","nonce":"xx","Signature-Headers":"client_id","sign":"xx","sign_method":"HMAC-SHA256","access_token":"xx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"client_id":"cloud_xx","expire_time":7200,"password":"xx","sink_topic":{"device":"cloud/token/out/{device_id}"},"source_topic":{"device":"cloud/token/in/xx"},"url":"ssl://m1.tuyaeu.com:8883","username":"xx"},"success":true,"t":xx,"tid":"xx"} path = /v1.0/iot-03/open-hub/access-config
TuyaOpenMQ connecting: ssl://m1.tuyaeu.com:8883
TuyaOpenMQ connected

**Comment by dquak** [comment]
Getting the exact same issue

**Comment by asander85** [comment]
I am having the exact same issue w a ceiling fan controller. Homebridge shows the accessory was transferred in the logs, but not accessory was actually discovered. Been pulling my hair out for over a week trying to make heads or tails of the issue, I got nothing. Even tried all the different Tuya plugins, including the web version - nothing.

**Comment by rizanw** [comment]
hi I got same issue here
```
"product_name":"S06ProWB3S带历史记录新界面（S09模块共用）"
```
