### ISSUE TITLE
Garage door change state not synchronized in homeKit (open/close/opening/closing) 

### ISSUE THREAD

**Issue by pacooka** [tuya/tuya-homebridge#287]
When using a garage a door opener controller, PBT, i.e. PBT ZigBee or PBT WiFi garage door opener (https://www.aliexpress.com/item/1005003635582496.html  or  https://www.aliexpress.com/item/1005003222899297.html )
Open /Close state not updating correctly.

Scenario to reproduce the bug:
 1. Install PBT garage door opener, Zigbee or WiFi, make sure to connect correctly the open/close sensor, Bring the sensor closer to simulate a close door state.
 2. Use latest ios16 Tuya app and bind the garage door to the app.
 3. Use Homebridge and install the plugin Homebridge-Tuya-Platform V 1.5.0
 4. Open the HomeKit app in ios16 and verify proper garage door opener display correctly, state closed.
 5. In HomeKit press the garage door icon to open the door, move the sensor away to simulated an open door state.
 6. Bring the sensor back closer to simulate a close door state and watch the HomeKit icon, state stuck on opening/closing instead of "closed" + continues multiple messages from the HomeKit app "door closed", "door open"  - - > BUG

* Sensor works ok in Tuya app, but not in HomeKit which is very weird.

Impact: wrong behavior on HomeKit app garage icon, state unknown
reproduce 1:1 in the described scenario
workaround: press several times on the garage door icon in the HomeKit app
expected results: I have an Athome garage door opener with homeKit firmware native and it works fine. I believe that the plugin might have some issue with the sensor state.

**Comment by 0x5e** [comment]
@pacooka Reimplemented Garage door opener in [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) v1.6.0-beta.10. Tested with virtual device. Hope it can solve your issue.[Obstruction]

`ObstructionDetected` feature not implemented, it can't be tested with virtual device. could you please try the beta version and open the homebridge debug mode, and upload some logs during the door open and clode? I don't know how `countdown_alarm` and `countdown_1` behaves.

**Comment by pacooka** [comment]
> 

Still Reproduce 1:1 in the described scenario, tested on Tuya plugin 1.7 beta 13. with iOS 16.2
Bug still exist, please try to reproduce as described in the  scenario, step 6 will fail, status in HomeKit will be "Opening"

**Comment by 0x5e** [comment]
@pacooka Can you provide some debug logs, and device info json during your control? I don't have real device, and the virtual device can't simulate the opening/closing process.

**Comment by pacooka** [comment]
> @pacooka Can you provide some debug logs, and device info json during your control? I don't have real device, and the virtual device can't simulate the opening/closing process.

Yes, can you advise how can i generate the logs? or where can i find them

**Comment by 0x5e** [comment]
> > @pacooka Can you provide some debug logs, and device info json during your control? I don't have real device, and the virtual device can't simulate the opening/closing process.
> 
> Yes, can you advise how can i generate the logs? or where can i find them

Here it is, please see faq and troubleshooting section.
https://github.com/0x5e/homebridge-tuya-platform#readme

**Comment by pacooka** [comment]
I'll connect it again and send you the logs during the weekend

**Comment by pacooka** [comment]
Hi @0x5e , I have the full debug log ready, where can i send you the debug log? it has some private data within, can you please advise with an email address?

**Comment by 0x5e** [comment]
@pacooka Thanks, the log is good, I will look at it later, sorry recently is always busy...

**Comment by guillochon** [comment]
Not stale

**Comment by OliPetry** [comment]
Same issue still persisting with 1.7 beta. The only way I can get the status to be correct is if I use only the homekit integration to open and close or press the homekit button several times exactly as original poster described.

**Comment by pacooka** [comment]
> Same issue still persisting with 1.7 beta. The only way I can get the status to be correct is if I use only the homekit integration to open and close or press the homekit button several times exactly as original poster described.

I know, I gave up.
Order from the following link, works great with Homekit and only $13 :-)
https://www.aliexpress.com/item/1005005906164250.html
