### ISSUE TITLE
HomeKit not showing security cameras

### ISSUE THREAD

**Issue by abuyah101** [tuya/tuya-homebridge#290]
Hi there,

I have a pair of GRiD Connect security cameras that are connected to the Tuya app without an issue. However, they don't show up in my HomeKit. The lights show up but my camera's, door bell and smart lock don't show up.

What can I do to fix this please?

**Comment by PricklyBramblewood** [comment]
Same here. Please add cameras to supported devices.

**Comment by 0x5e** [comment]
https://github.com/0x5e/homebridge-tuya-platform/issues/48#issuecomment-1304594704
