### ISSUE TITLE
Attention⚠️ ⚠️ ⚠️ ! You get an error! Failed to get device information. Please check if the config.json is correct.

### ISSUE THREAD

**Issue by llllacuna** [tuya/tuya-homebridge#293]
Hi guys I am new here 
my tuya door lock won't show on the Homebridge Accessories
and after turning on the debug logging its shows this error :
Attention⚠️ ⚠️ ⚠️! You get an error! Failed to get device information. Please check if the config.json is correct.

i don't know how to solve this plz help

**Comment by llllacuna** [comment]
this is my config.json : 
note : I'm covering date with # and I'm from Saudi Arabia
{
    "bridge": {
        "name": "Homebridge 589A",
        "username": "0E:13:A5:9E:58:9A",
        "port": 51319,
        "pin": "807-43-061",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "options": {
                "username": "layan####@gmail.com",
                "password": "M123#######n",
                "accessId": "rafycap#####ryp3xnw38stm",
                "accessKey": "8d48#####27173f12fcb2c8",
                "lang": "en",
                "projectType": "2",
                "appSchema": "tuyaSmart",
                "countryCode": 96,
                "debug": true
            },
            "name": "TuyaPlatform",
            "_bridge": {
                "username": "0E:46:CC:08:D8:35",
                "port": 33714
            },
            "platform": "TuyaPlatform"
        }
    ]
}

**Comment by dswarne** [comment]
Same exact issue here, Im suspecting it is related to the API authorization, I have contacted TUYA support will let you know when I receive anything.

If you have come right since, please share

**Comment by djzgfx** [comment]
Same issue here as well. Just started this morning.

**Comment by dswarne** [comment]
Hi All, I’ve looked into and and seem to have resolved the issue. What I did was recreate a project in Tuya IOT making sure to authorize the “device development Notification “ API

**Comment by mmaslen** [comment]
> Hi All, I’ve looked into it and seemed to have resolved the issue. What I did was recreate a project in Tuya IOT making sure to authorize the “device development Notification “ API
> 
> let me know how you get on.

where exactly is that authorised, I couldn't find it

**Comment by dswarne** [comment]
Please follow the below.
![DFC4F149-2BE1-438A-B9CD-52D573A591DA](https://user-images.githubusercontent.com/68950975/195807164-d0735ff0-bcb6-4db2-8b6d-9e6e0caf4b95.jpeg)
![ABE9AD63-81B5-43CD-8773-02CD308D236B](https://user-images.githubusercontent.com/68950975/195807198-8f52e872-add0-4e87-bbea-710f27f89752.jpeg)
![C5871CF6-676D-4DA1-9966-0145E7EF290C](https://user-images.githubusercontent.com/68950975/195807210-081a18c7-b399-4fe4-ba02-b86d6bd4de6b.jpeg)
![E8F23FB5-9939-4683-B794-6A39643BB328](https://user-images.githubusercontent.com/68950975/195807223-0a8f4596-b723-4911-87b8-10081d2d4424.jpeg)

**Comment by mmaslen** [comment]
> Please follow the below.
> 
Thank you for your help, I followed your instructions - problem remains

**Comment by mmaslen** [comment]
Tuya are now asking me to extend my trial period - is that normal?

**Comment by coolweb** [comment]
For the IoT Core wass expired, I extend the trial and it is working.
