### ISSUE TITLE
issue with fan light switch

### ISSUE THREAD

**Issue by fercho2903** [tuya/tuya-homebridge#295]
Hello i have an issue with the tuya ds3 in hoobs, the switch controls light on/off and fan on/off and  speed up to four speeds 
In hoobs only apears the fan switch it does not appear for the light switch and when i try to
Set it up on homekit it does the same thing how can i fix that thanks for your help

**Comment by iGageit** [comment]
I recently installed a ceiling fan controller and got it in my smart life app and that is connected to Homebridge.. but the fan will not appear.
