### ISSUE TITLE
Code 2406 - after running smoothly for ages

### ISSUE THREAD

**Issue by JaimeSLS** [tuya/tuya-homebridge#298]
After using the plugins for ages now and everything running really smooth, I've got this error code now. 
I checked all the connections… I cant the error here. Didnt change a thing. 

Can smb help?

Cheers
Jaime

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1665661964448,"tid":"8c8e356f4aed11eda7a4d2b5cc5248de"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!

**Comment by tne7laa** [comment]
+1. Same here. Tried rebooting, restarting. Can login in Tuya API site. Hope it is something simple.

**Comment by Azukovskij** [comment]
Tried another countries, VPN, nothing helped. Implemented workaround using different API  https://github.com/Azukovskij/tuya-homebridge/commit/5eaa7e46543954c3ac991ea88e35eb4bbdd4f698

**Comment by mmaslen** [comment]
Same error here

**Comment by aljorhythm** [comment]
Same here

**Comment by leo150** [comment]
I wish someone would implement a local tuya server. Window blinds to connect to a remote server is such a nonsense proven by this "suddenly" appeared error

**Comment by antonkrall** [comment]
Same issue here...today no longer working with homebridge

**Comment by boris-dimitrov** [comment]
> Tried different countries, VPN, nothing helped. Implemented workaround using different API [Azukovskij@5eaa7e4](https://github.com/Azukovskij/tuya-homebridge/commit/5eaa7e46543954c3ac991ea88e35eb4bbdd4f698) to retrieve access_token.

Thank you for this workaround, it solved the problem for me.

**Comment by mmaslen** [comment]
> > Tried different countries, VPN, nothing helped. Implemented workaround using different API [Azukovskij@5eaa7e4](https://github.com/Azukovskij/tuya-homebridge/commit/5eaa7e46543954c3ac991ea88e35eb4bbdd4f698) to retrieve access_token.
> 
> Thank you for this workaround, it solved the problem for me.

tried this workaround, only works with a subset of my devices - power points (yes), contact sensors (no)

**Comment by Azukovskij** [comment]
> > > Tried different countries, VPN, nothing helped. Implemented workaround using different API [Azukovskij@5eaa7e4](https://github.com/Azukovskij/tuya-homebridge/commit/5eaa7e46543954c3ac991ea88e35eb4bbdd4f698) to retrieve access_token.
> > 
> > 
> > Thank you for this workaround, it solved the problem for me.
> 
> tried this workaround, only works with a subset of my devices - power points (yes), contact sensors (no)

@mmaslen , can you check debug logs for errors?

**Comment by JaimeSLS** [comment]
I can agree the workaround from @Azukovskij  is working fine. 

Open ssh and navigate to 
`nano /usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js`

Edit the file as mentioned by @Azukovskij@5eaa7e4 

Restart homebridge. 
Done

**Comment by bkessels** [comment]
Same problem here, tuya homebridge devices stopped working as of oct 13th.

The workaround from @Azukovskij fixed the problem for me.

Thanks for providing this.
