### ISSUE TITLE
Local API

### ISSUE THREAD

**Issue by cemilbrowne** [tuya/tuya-homebridge#3]
Please support local API. The biggest reason folks flash devices is to reduce the inevitable latency issues with going to cloud endpoint and back. 

Can we make this truly local, LAN protocol?

**Comment by Hanh94** [comment]
Thank you for your feedback. Currently Tuya-HomeBridge does not support Local API.

**Comment by xoniq** [comment]
+1

And not just because of the latency standpoint, also from the privacy side.

**Comment by zlinoliver** [comment]
@cemilbrowne @xoniq thanks for the feedbacks! Understand the existing pain point of inevitable latency issues, the new tuya-homebridge plugin use Tuya Open APIs with better server support, could you help to try on it and let us know if the latency issue still exist?

**Comment by PixelBurstHD** [comment]
> @cemilbrowne @xoniq thanks for the feedbacks! Understand the existing pain point of inevitable latency issues, the new tuya-homebridge plugin use Tuya Open APIs with better server support, could you help to try on it and let us know if the latency issue still exist?

If internet goes down, local access is needed. This is my #1 reason for flashing devices

**Comment by cemilbrowne** [comment]
@zlinoliver - Thanks for the recommendation.  What I don't understand is the resistance.  You have an army of folks who want to use your product, but don't want cloud integration.  We're not advocating for completely removing cloud access, but just have a switch to disable it, and allow local LAN commands.  

The resistance makes it seem like that there is something to hide, which I doubt!

I flash my Tuya devices with Tasmota so that I don't have to worry about the internet going down, or that someone's cloud service is down, or the latency to and from anywhere.  I wouldn't flash if the Tuya firmware just supported this natively.  Please reconsider supporting this - you'd sell a lot more devices...

**Comment by codyc1515** [comment]
You can use them locally. Tuya just doesn’t expose the keys easily and this seems to be deliberate, in the face of any other reasoning.

**Comment by zlinoliver** [comment]
Thanks for the feedbacks! @cemilbrowne @xoniq @PixelBurstHD @codyc1515 , we will provide local control support for the Tuya homebridge plugin soon, the technical solution is still under development. You don't need to flash Tuya devices to achieve local control anymore :)

**Comment by cemilbrowne** [comment]
That is *really* good news.  If you can publish some of those docs, then the Home Assistant team can build in local Tuya control, and you guys will sell a _ton_ of devices.  I’m now tempted to buy a bunch of devices that I didn’t want to before.

**Comment by xoniq** [comment]
> Thanks for the feedbacks! @cemilbrowne @xoniq @PixelBurstHD @codyc1515 , we will provide local control support for the Tuya homebridge plugin soon, the technical solution is still under development. You don't need to flash Tuya devices to achieve local control anymore :)

That's great to hear! Looking forward for updates. Will it also work more straight forward instead having to wireshark the connection to find the local keys and such?

**Comment by rcoletti116** [comment]
I see this was closed due to inactivity. I’m curious if there’s any update and a way to keep it open until local support is provided?

**Comment by alangrafu** [comment]
Agreed, this is an important feature, especially for people without a good internet connection.

**Comment by ElphaX** [comment]
Will update fellow users and devs; I've been in calls and close contact with the official Tuna dev team and it is not the biggest priority for them at the moment, whilst they have said they are looking to provide limited local control in the future they are much more focused on Cloud stability. I wouldn't keep our hopes up too high.
