### ISSUE TITLE
Ceiling fan controller in smart life app not appearing in Homebridge

### ISSUE THREAD

**Issue by iGageit** [tuya/tuya-homebridge#300]
I recently installed a ceiling fan controller and got it in my smart life app and that is connected to Homebridge.. but the fan will not appear. I connected a smart bulb just to make sure my connection was good and it is. for some reason my fan controller that make my dumb fan smart will not appear in Homebridge. thank you for looking at this and hope you find a fix.

**Comment by 0x5e** [comment]
Please try https://github.com/0x5e/homebridge-tuya-platform and provide some logs about your device (without sensitive data)

**Comment by iGageit** [comment]
The fan I was using is this by the way: https://amzn.to/3TgxLfX

**Comment by 0x5e** [comment]
Hi @iGageit , please provide plugin logs then we can see where the problem happend.

**Comment by iGageit** [comment]
I can see the smart fan in the logs but it won't appear in HomeKit. Here is the log when I turn on the light from the smart life app. 
TuyaOpenMQ onMessage: topic = cloud/token/in/{my device}, message = {"data":{"dataId":"myid-2ef4-4c1e-8e0b-976d16a85143","devId":"{my device}","productKey":"{mikes}","status":[{"20":false,"code":"switch_led","t":"1666626685","value":false}]},"protocol":4,"pv":"2.0","sign":"ddd174645c9fb5a4a75875735416bc5255","t":1666626685}

**Comment by iGageit** [comment]
When I turn on the fan on or off, I can see that Homebridge can see the state of change, But I does not appear in the accessories tab of Homebridge or in HomeKit.

**Comment by iGageit** [comment]
update: when I use yours https://github.com/0x5e/homebridge-tuya-platform it now will appear in HomeKit, but HomeKit says "Not supported"

**Comment by 0x5e** [comment]
OK. I will fix this later.

**Comment by iGageit** [comment]
any progress on this bug? any log info you need to help debug?

**Comment by 0x5e** [comment]
I will fix next week, sorry for the late. No info need currently.

**Comment by B-double-U** [comment]
Hi,
I have the same issue with a Thermostat. The device is connected in the Tuya platform and I can see in the Homebridge logs that changing values, like the temperature, are received in Homebridge. However the device is not showing up in the accessories overview and not in Homekit.

**Comment by iGageit** [comment]
I just noticed that the fan controls is always defaulting to 2% speed in the Home app settings.. not an urgent deal but just so it's on your radar. @0x5e

**Comment by 0x5e** [comment]
> I just noticed that the fan controls is always defaulting to 2% speed in the Home app settings.. not an urgent deal but just so it's on your radar. @0x5e 
> 
> 

Ok I will see this later, thanks :)

**Comment by 0x5e** [comment]
@iGageit how many fan levels do you have? off/low/medium/high ?
Can you provide TuyaDeviceList.json like this:
https://github.com/0x5e/homebridge-tuya-platform/issues/44
