### ISSUE TITLE
Tuya power switches and sensors not longer responding

### ISSUE THREAD

**Issue by mmaslen** [tuya/tuya-homebridge#301]
**Describe the bug**
Tuya power switches and sensors not longer responding - the the devices still work ok with the native tuya app

**Expected behavior**
Tuya power switches and sensors respond to events via homebridge

**Screenshots**
This is the error in the homebridge log i get:

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1665699368670,"tid":"a336f09d4b4411edb8a1ca0f69d78a9e"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/usr/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by mmaslen** [comment]
my config and the devices and the plug-in have been working well since i purchased the devices back in May-2022

If there is any other info I need to provide please let me know

**Comment by TaylordFed** [comment]
> my config and the devices and the plug-in have been working well since i purchased the devices back in May-2022
> 
> If there is any other info I need to provide please let me know

Which devices did you get? Were they contact sensors?

**Comment by mmaslen** [comment]
Correct the contact sensors no longer workOn 15 Oct 2022, at 12:23 pm, TaylordFed ***@***.***> wrote:﻿

my config and the devices and the plug-in have been working well since i purchased the devices back in May-2022
If there is any other info I need to provide please let me know

Which devices did you get? Were they contact sensors?

**Comment by TaylordFed** [comment]
Yes, just yesterday I got contact sensors and in homebridge the state of the contact sensors remain as closed. Same for the homebridge UI

**Comment by TaylordFed** [comment]
Was there anything that you did to make the sensors work?


>

**Comment by preethaml7** [comment]
Happened to me today. All I did was unlink the app from the tuya cloud website, and re-link it again by scanning the QR code shown on tuya cloud with the tuya app. (provide read and write permission to devices in the tuya cloud prompt after scanning the QR code)
Reload the integration in Homebridge and voilà, everything should be working as before.
If you are still facing issues, go to home bridge settings Remove All Cached Accessories and try the above step hopefully you should get it working too.

**Comment by mmaslen** [comment]
> Happened to me today. All I did was unlink the app from the tuya cloud website, and re-link it again by scanning the QR 

did that, still broken

**Comment by TaylordFed** [comment]
Ive already done that before it was even a problem for me.

**Comment by 0x5e** [comment]
Config validation and login success check added on [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) 1.6.0-beta. Please try if it solves this issue.
