### ISSUE TITLE
Contact sensor not working

### ISSUE THREAD

**Issue by TaylordFed** [tuya/tuya-homebridge#302]
**Describe the bug**
In the supported devices it shows that contact sensors are supported. I cannot get the contact sensors working
**Expected behavior**
It is supposed to update in the Home app and the Homebridge UI, but it doesn't. It works fine in the Tuya app.
**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
In the console it will just show that the status is being updated. This is what happens when I the contact sensor is open then closed, but it won't show in the UI.

When opened: TuyaOpenMQ onMessage: topic = cloud/token/in/6c2079eaa10eb2c557b02522cbd8ae38, message = {"data":{"bizCode":"online","bizData":{"time":1665780139},"devId":"53434106a4e57c13aa55","productKey":"4m7uzaxtbqp0khyn","ts":0},"protocol":20,"pv":"2.0","sign":"123656b6800f807fd3ac192e25b92082","t":1665780139}
TuyaOpenMQ onMessage: topic = cloud/token/in/6c2079eaa10eb2c557b02522cbd8ae38, message = {"data":{"dataId":"d02f6e70-841d-48b1-9e63-454c4394f77a","devId":"53434106a4e57c13aa55","productKey":"4m7uzaxtbqp0khyn","status":[{"1":"open","code":"doorcontact_state","t":"2","value":"true"}]},"protocol":4,"pv":"2.0","sign":"61070200f0b6afee147bdf7430a782c4","t":2}
TuyaOpenMQ onMessage: topic = cloud/token/in/6c2079eaa10eb2c557b02522cbd8ae38, message = {"data":{"dataId":"914d2d84-5ace-436e-a8ea-6ebbca6cc189","devId":"53434106a4e57c13aa55","productKey":"4m7uzaxtbqp0khyn","status":[{"102":"0x01"}]},"protocol":4,"pv":"2.0","sign":"201f7384b12a3123ed0e9557101931f2","t":2}

When closed: TuyaOpenMQ onMessage: topic = cloud/token/in/6c2079eaa10eb2c557b02522cbd8ae38, message = {"data":{"dataId":"10047d4c-854e-4a28-aab7-a24118d0dc85","devId":"53434106a4e57c13aa55","productKey":"4m7uzaxtbqp0khyn","status":[{"1":"closed","code":"doorcontact_state","t":"2","value":"false"}]},"protocol":4,"pv":"2.0","sign":"eb8c8b1472013cc9ab50f309d2f664c8","t":2}
TuyaOpenMQ onMessage: topic = cloud/token/in/6c2079eaa10eb2c557b02522cbd8ae38, message = {"data":{"dataId":"c92175b0-12d2-4eec-80fd-beda9de52677","devId":"53434106a4e57c13aa55","productKey":"4m7uzaxtbqp0khyn","status":[{"102":"0x01"}]},"protocol":4,"pv":"2.0","sign":"faddf3b1a1bb1b082ad4f8f5f76b101b","t":2}

**Comment by mmaslen** [comment]
Having same issue

**Comment by mmaslen** [comment]
ok, it's finally working for me with the standard plug-in - I ended up changing and ensuring that the iOS app password, the IOT platform password and the plugin password were all identical

**Comment by 0x5e** [comment]
Contact sensor reimplemented in [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) 1.6.0-beta.8. Tested on virtual device, please try if it solves you problem.
