### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by richgrios** [tuya/tuya-homebridge#303]
Nothing is working through the homekit app but works on smart life app with no issues....please share how to fix!!!

**Comment by preethaml7** [comment]
Happened to me today. All I did was unlink the app from the tuya cloud website, and re-link it again by scanning the QR code shown on tuya cloud with the tuya app. (provide read and write permission to devices in the tuya cloud prompt after scanning the QR code)
Reload the integration in Homebridge and voilà, everything should be working as before.
If you are still facing issues, go to home bridge settings Remove All Cached Accessories and try the above step hopefully you should get it working too.

**Comment by Jonny11** [comment]
Experiencing same issue since a few days ago, still unresolved

**Comment by edzdamangere** [comment]
I thought it was something I did, but I haven't changed anything in the config files or on Tuya iot. All devices in Homekit non operational.

**Comment by bottlebug** [comment]
> Happened to me today. All I did was unlink the app from the tuya cloud website, and re-link it again by scanning the QR code shown on tuya cloud with the tuya app. (provide read and write permission to devices in the tuya cloud prompt after scanning the QR code)
> Reload the integration in Homebridge and voilà, everything should be working as before.
> If you are still facing issues, go to home bridge settings Remove All Cached Accessories and try the above step hopefully you should get it working too.

Happened to me. Re-linked and started working again. Hope this doesn't happen again.

**Comment by Kohle81** [comment]
I have done nothing, but in morning all devices are working through homekit 👍

**Comment by mmaslen** [comment]
ok, it's finally working for me with the standard plug-in - I ended up changing the iOS app password, the IOT platform password and the plugin password were all identical

**Comment by Protodjango** [comment]
I have reinstalled the plugin, done all steps (unlink from project, tried with a new project, complete new Installation of the Homebridge UI etc... , but I still dont see Devices in Homebridge. In SmartLife App everything is fine. Is there something new with subscriptions in IoT Platform?

**Comment by richgrios** [comment]
I switch to this plugin now "Tuya Web"..... works great and easier to setup. Just username and password from your Tuya or smart life app

**Comment by Protodjango** [comment]
> I switch to this plugin now "Tuya Web"..... works great and easier to setup. Just username and password from your Tuya or smart life app

Thank you for your feedback. I tried this and run into the next error :( My ceiling lights are not compatible with this Web Plugin. https://github.com/milo526/homebridge-tuya-web/issues/175

**Comment by Protodjango** [comment]
Today i registered a new Tuya IoT Account, made a new SmartLife Account and used the same settings like in my old Accounts. Now it works like it should.

**Comment by 0x5e** [comment]
Hi, please try [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform) fork, If still not working, please provide some logs.

**Comment by tablatronix** [comment]
I see it try to get the devices, but debug shows nothing after that, and no devices get added.

**Comment by 0x5e** [comment]
We need API logs to see which step the plugin goes wrong. No devices has many possibilities, login failure, api subscribe expired, app account not linked, token expired...

**Comment by ux-lic** [comment]
Try going to **IoT Core** under **Cloud services** on [iot.tuya.com](iot.tuya.com) and check to see if your trial has expired. There's a little button to extend the trial.
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/22139628/211449708-ea01ef06-834a-4199-96ea-5f1452ef4e54.png">
