### ISSUE TITLE
Fan icon

### ISSUE THREAD

**Issue by roberkane212** [tuya/tuya-homebridge#304]
This isn’t a big issue. However I was wondering if it would be possible to have more options for the fan icon in HomeKit. I have a ceiling fan and would hope to use the crawling fan icon in HomeKit. Thanks if possible

**Comment by 0x5e** [comment]
Hi, the icon is provided by Apple. We can't help this.

**Comment by 0x5e** [comment]
Finally this can be solved, See this: [0x5e/homebridge-tuya-platform#131](https://github.com/0x5e/homebridge-tuya-platform/pull/131)

**Comment by roberkane212** [comment]
@0x5e thank you so much, I will try again when I get home today
