### ISSUE TITLE
Device not showing up in Homekit

### ISSUE THREAD

**Issue by Marcus235** [tuya/tuya-homebridge#306]
I've got two devices which shows in the Tuya IoT devices but they don't show up in Homekit. 
This is one of the devices. It concerns floor heaters. 
Device Information

Product Name
HY08WE最新通用型
Device ID
8600225224a1603461db
Product Category
wk
Device Status
Online
Activated At
2021-04-03 17:40:44

**Comment by 0x5e** [comment]
See https://github.com/0x5e/homebridge-tuya-platform/discussions/2 .
Currently in beta test [@0x5e/homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform)
