### ISSUE TITLE
Air Purifier discovered but not working

### ISSUE THREAD

**Issue by bosco90** [tuya/tuya-homebridge#31]
Hello,
I've added all my accessories in the Home App (see #22 ) but the Air Purifier is not working (it's added but becomes unresponsive).

Here are some details that might be helpful:

AIR PURIFIER:
Brand: Bimar
Model: VK-6070A
Type: PA98

LOGS:
(node:1091288) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'values' of undefined
    at AirPurifierAccessory.getSpeedFunction (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/air_purifier_accessory.js:162:40)
    at new AirPurifierAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/air_purifier_accessory.js:25:37)
    at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:107:27)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:86:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1091288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1091288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

IMAGES:
![bimar](https://user-images.githubusercontent.com/78073930/120970777-266cec00-c76c-11eb-8976-53ccfc8c287d.jpeg)

Thanks for your hard work!

**Comment by Hanh94** [comment]
Hi @bosco90 ,We have received your feedback.
Normally, a valid data structure would contain the "values" key at this point, as shown below:
```
[
  {
    code: 'switch',
    desc: 'switch',
    name: 'switch',
    type: 'Boolean',
    values: '{}'
  },
  {
    code: 'speed',
    desc: 'speed',
    name: 'speed',
    type: 'Enum',
    values: '{"range":["1","2","3"]}'
  },
  {
    code: 'filter_reset',
    desc: 'filter reset',
    name: 'filter reset',
    type: 'Boolean',
    values: '{}'
  },
  {
    code: 'countdown',
    desc: 'countdown',
    name: 'countdown',
    type: 'Enum',
    values: '{"range":["1","2"]}'
  }
]
```

this error seems to indicate an illegal data structure. Please show us the deviceID of the device so that we can check the problem.

**Comment by bosco90** [comment]
Thanks,
the deviceID should be this one: 87120855dc4f227af75e

On the Log I've found this, hopefully will help you:

"product_id":"2nuwDqbTZIAV7JW6"},{"category":"kj","devices":["87120855dc4f227af75e"],"functions":[{"code":"filter_reset","desc":"filter reset","name":"filter reset","type":"Boolean","values":"{}"},{"code":"anion","desc":"anion","name":"anion","type":"Boolean","values":"{}"},{"code":"fan_speed_enum","desc":"fan speed enum","name":"fan speed enum","type":"Enum","values":"{\"range\":[\"low\",\"mid\",\"high\"]}"},{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"}]

**Comment by Hanh94** [comment]
Hi @bosco90 ,Thank you for your feedback.
We already support "fan_speed_enum" in the latest version, please update and try again.

**Comment by bosco90** [comment]
YES! It's working perfectly!!! Thanks a lot :D
