### ISSUE TITLE
Errors appearing in log when viewing device, seems related to incorrect temperature display units in HomeKit

### ISSUE THREAD

**Issue by enz1ey** [tuya/tuya-homebridge#310]
I have a HeatStorm wall heater in the Tuya Smart app, and it is set to show Fahrenheit. However, in HomeKit, while it also says the unit is set to Fahrenheit, it is showing 140 degrees as the set point instead of 60F.

The relevant HomeBridge log entries are as follows:

`[10/20/2022, 9:02:04 AM] [homebridge-tuya-platform] This plugin threw an error from the characteristic 'Temperature Display Units': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://homebridge.io/w/JtMGR for more info.
[10/20/2022, 9:02:04 AM] [homebridge-tuya-platform] Error: This callback function has already been called by someone else; it can only be called one time.
    at TemperatureDisplayUnits.<anonymous> (/homebridge/node_modules/homebridge-tuya-platform/lib/heater_accessory.js:114:11)`

`[10/20/2022, 9:02:04 AM] [homebridge-tuya-platform] This plugin threw an error from the characteristic 'Heating Threshold Temperature': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://homebridge.io/w/JtMGR for more info.`

`[10/20/2022, 9:02:04 AM] [homebridge-tuya-platform] Error: This callback function has already been called by someone else; it can only be called one time.
    at HeatingThresholdTemperature.<anonymous> (/homebridge/node_modules/homebridge-tuya-platform/lib/heater_accessory.js:114:11)`

`[10/20/2022, 9:02:04 AM] [homebridge-tuya-platform] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://homebridge.io/w/JtMGR for more info.`

`[10/20/2022, 9:02:04 AM] [homebridge-tuya-platform] Error: This callback function has already been called by someone else; it can only be called one time.
    at CurrentTemperature.<anonymous> (/homebridge/node_modules/homebridge-tuya-platform/lib/heater_accessory.js:114:11)`

**Comment by 0x5e** [comment]
If you want to change the temperature unit for HomeKit, please go to System setting -> General -> Language and Region -> Temperature Unit.

And for the error logs in homebridge, please try my beta version: https://github.com/0x5e/homebridge-tuya-platform

**Comment by enz1ey** [comment]
> If you want to change the temperature unit for HomeKit, please go to System setting -> General -> Language and Region -> Temperature Unit.
> 
> And for the error logs in homebridge, please try my beta version: https://github.com/0x5e/homebridge-tuya-platform

You’re talking about changing the temperature unit globally on the entire phone here? My temperature units are already set there to Fahrenheit. This Tuya device is the only device in HomeKit using Celsius.

**Comment by 0x5e** [comment]
Currently there's no people maintaining the 1.5.0 version. Heater has been reimplemented in 1.6.0 beta. Please try if it solves your problem.
