### ISSUE TITLE
Possibility to display Power consumption in HomeKit for smart outlet

### ISSUE THREAD

**Issue by baumph** [tuya/tuya-homebridge#319]
I have a tuya smart power outlet with power consumption monitoring. It is displayed in the Tuya app, but not in HomeKit. 
Is it possible to add this functionality to HomeKit?

**Comment by 0x5e** [comment]
HomeKit doesn't support displaying power consumption.

**Comment by baumph** [comment]
Not in the „Home“ App, but other apps like „Eve for HomeKit“ do support displaying power consumption. And i also have another outlet that already does display power consumption in Eve.

**Comment by 0x5e** [comment]
Do you know how to integrate with Eve ? I couldn't find any technical documentations. Thanks.

**Comment by 0x5e** [comment]
What's the brand of your another outlet that supports Eve?

**Comment by baumph** [comment]
Its a TP-Link HS110 power point. It is also not natively supported in eve/HomeKit and is added with the Homebridge-Tplink-Smarthome plugin.
