### ISSUE TITLE
API subscription expired. Please renew the API subscription at Tuya IoT Platform.

### ISSUE THREAD

**Issue by bimusiek** [tuya/tuya-homebridge#321]
**Describe the bug**
I just finished installing all Tuya enabled smart home devices and when tried to test it out I have got an error:
```
API subscription expired. Please renew the API subscription at Tuya IoT Platform.
```

As far as I understand, the pricing is 25 000$/year for basic subscription? Is this correct?
To use the tuya-homebridge app I have to pay this much? Then I would rather redo all Tuya integrations at my home which will be 1/10th of this cost.

Is there any other subscription or any other way to make the bridge work without subscription?

**Comment by bimusiek** [comment]
So, my Trial has been extended 
<img width="370" alt="CleanShot%202022-11-12%20at%2011 51 41@2x" src="https://user-images.githubusercontent.com/1025588/201471042-f52be932-871e-4a29-9fac-29ff0aa824dd.png">
however Homebridge still shows the error.
<img width="1085" alt="CleanShot 2022-11-12 at 12 02 48@2x" src="https://user-images.githubusercontent.com/1025588/201471064-ba0245ef-b7c9-44e2-91ae-e0d01097ada6.png">

**Comment by 0x5e** [comment]
If the error code still returned, please submit the ticket to tuya. https://service.console.tuya.com/

**Comment by bimusiek** [comment]
Thank you, opening up the support ticket helped.

**Comment by 0x5e** [comment]
How did you solved the issue, just the ticket and don't need you to do anything?

**Comment by bimusiek** [comment]
Before opening the ticket I removed app integration from Cloud project and added it again. When this did not help, I have opened support ticket and it started working again after some time.

**Comment by four43** [comment]
It seems this library may be a better alternative. It seems to operate locally completely cutting out Tuya and their nonsense.

https://github.com/iRayanKhan/homebridge-tuya
