### ISSUE TITLE
Qlima indoor dehumidifier not showing up as accessoires in Homebridge

### ISSUE THREAD

**Issue by SterkeYerke** [tuya/tuya-homebridge#322]
**Describe the bug**
Qlima indoor dehumidifier not showing up as accessoires in Homebridge.

**Expected behavior**
Showing accessoires for humidity and ond/of switch in Homebridge .

**Screenshots**
This is a screenshot of the Homebridge logging. This shows the Tuya project etc are created succesfully and the the the plugin is notified of the existing device

TuyaOpenMQ onMessage: topic = cloud/token/in/1e8ce1f38805471f5cc5e882e51d6c68, message = {"data":{"dataId":"d0866502-736a-4b21-ab9a-8a9a3acec18e","devId":"035755003c6105c5c259","productKey":"YDvSMhQz8HsphjrJ","status":[{"3":68,"code":"humidity_indoor","t":"1668532728","value":68}]},"protocol":4,"pv":"2.0","sign":"66d02e03a435acd9f2d11c022559b08f","t":1668532728}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":31,"username":"henk@xxxxxxxxxxxxxxxx.nl","password":"xxxxxxxxxxxxxxxxxxxxxxxxx","schema":"tuyaSmart"}, headers = {"t":"1668532760249","client_id":"psnfy5tpb620a6810lxy","nonce":"bf5f2680-5fa5-11ed-a6b9-e760f9efc003","Signature-Headers":"client_id","sign":"796349CDBBC8F296E9DC385B9FD6A64870C7025194325C63751C3D9D7B90CE7E","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"access_token":"d57c4a1a595c94708fc86c47d95e0ad0","expire_time":7200,"platform_url":"https://openapi.tuyaeu.com","refresh_token":"6d6bce457e4725d8227e3174e17cb2f4","uid":"eu1637863778250od4ob"},"success":true,"t":1668532760437,"tid":"a446f814650911ed81e28ec426404b74"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-03/open-hub/access-config, params = null, body = {"uid":"eu1637863778250od4ob","link_id":"bf7594b0-5fa5-11ed-a6b9-e760f9efc003","link_type":"mqtt","topics":"device","msg_encrypted_version":"1.0"}, headers = {"t":"1668532760450","client_id":"psnfy5tpb620a6810lxy","nonce":"bf5f2680-5fa5-11ed-a6b9-e760f9efc003","Signature-Headers":"client_id","sign":"3CDBC5A8A6E2B5CCE096C825AD80C044AB609661F3346BC2C7AD6C5165F7EF7E","sign_method":"HMAC-SHA256","access_token":"d57c4a1a595c94708fc86c47d95e0ad0","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"client_id":"cloud_a57c3def95fb71979be072e7e2b54bb4","expire_time":7200,"password":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","sink_topic":{"device":"cloud/token/out/{device_id}"},"source_topic":{"device":"cloud/token/in/1e8ce1f38805471f5cc5e882e51d6c68"},"url":"ssl://m1.tuyaeu.com:8883","username":"cloud_1e8ce1f38805471f5cc5e882e51d6c68"},"success":true,"t":1668532760573,"tid":"a460963d650911ed805432ed7f2eb8a3"} path = /v1.0/iot-03/open-hub/access-config
TuyaOpenMQ connecting: ssl://m1.tuyaeu.com:8883
TuyaOpenMQ end
TuyaOpenMQ connected

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-    "product_id":"035755003c6105c5c259","productKey":"YDvSMhQz8HsphjrJ"

**Additional context**
I tried Home assistent. This plugin is working fine. Why would it nog work in Homebridge?
I tried IfTTT with IfTTT plugin in Homebridge. I had to create two scenes. One for switching of and one for switching on the device. This works as well.

**Comment by 0x5e** [comment]
Dehumidifier is not supported yet. If you could try the fork version and provide your device info json, I will support it in the next minor version.
https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by SterkeYerke** [comment]
Hi,

I've installed the fork. Please find below the contents of homebridge/persist/TuyaDeviceList.xx

[
  {
    "active_time": 1637878830,
    "biz_type": 0,
    "category": "cs",
    "create_time": 1637864159,
    "icon": "smart/product_icon/cs.png",
    "id": "035755003c6105c5c259",
    "ip": "xx.xx.xx.xxx",
    "lat": "xx.xxxx",
    "local_key": "xxxxxxxxxxxxx",
    "lon": "x.xxxxx",
    "model": "D008A.02.012.001",
    "name": "Ontvochtiger badkamer",
    "online": true,
    "owner_id": "42870528",
    "product_id": "YDvSMhQz8HsphjrJ",
    "product_name": "DEHUMIDIFIER",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "humidity_indoor",
        "value": 79
      },
      {
        "code": "dehumidify_set_value",
        "value": 50
      },
      {
        "code": "fan_speed_enum",
        "value": "high"
      },
      {
        "code": "child_lock",
        "value": false
      },
      {
        "code": "swing",
        "value": true
      },
      {
        "code": "temp_indoor",
        "value": 21
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "xxxxxxxxxxxxxxxxx",
    "update_time": 1640727723,
    "uuid": "xxxxxxxxxxxxxxxxxx",
    "schema": [
      {
        "code": "temp_indoor",
        "mode": "ro",
        "type": "Integer",
        "property": {
          "unit": "℃",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "swing",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "child_lock",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "fan_speed_enum",
        "mode": "rw",
        "type": "Enum",
        "property": {
          "range": [
            "low",
            "high"
          ]
        }
      },
      {
        "code": "dehumidify_set_value",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "unit": "%",
          "min": 35,
          "max": 80,
          "scale": 0,
          "step": 5
        }
      },
      {
        "code": "humidity_indoor",
        "mode": "ro",
        "type": "Integer",
        "property": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "switch",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      }
    ]
  }

**Comment by 0x5e** [comment]
@SterkeYerke Thanks for the information. I will update when I'm free.

**Comment by 0x5e** [comment]
I will native support the dehumidifier because it has the exactly related accessory in the homekit. Sorry for the late, there's too much categories need to be supported, and a big change for device overriding configs, I will support dehumidifier these days, maybe this weekend.

**Comment by 0x5e** [comment]
@SterkeYerke please try 1.7.0-beta.4.

**Comment by SterkeYerke** [comment]
> @SterkeYerke please try 1.7.0-beta.4.

@0x5e : Thank you very much. It works. Ik can switch the device on and off and I can set the desired humidity. Actual temperature is also shown. Any change you can add the other properties like actual humidity, swivel, fan speed and timer? 
Would be very nice, but I'm really happy with what we have now.

**Comment by 0x5e** [comment]
@SterkeYerke The humidity, fan speed, swing, child lock is in the dehumidifier's setting page. The timer I haven't decided how to support this, because homekit don't have timepicker.

**Comment by SterkeYerke** [comment]
> @SterkeYerke The humidity, fan speed, swing, child lock is in the dehumidifier's setting page. The timer I haven't decided how to support this, because homekit don't have timepicker.
<img width="499" alt="Schermafbeelding 2022-12-10 om 17 17 43" src="https://user-images.githubusercontent.com/47066997/206864835-c0e62b77-43dd-4f75-90ac-69342ac25097.png">
<img width="510" alt="Schermafbeelding 2022-12-10 om 17 18 09" src="https://user-images.githubusercontent.com/47066997/206864836-8ec64045-bf65-4a11-8c3c-088d866fe8e7.png">

@0x5e Either something is going wrong, or I'm doing something wrong, but I can only see 2 child accessories, 1 for temperature and 1 for on/off. I've included 2 screen prints. They are in dutch, but I think it speaks for it self.

**Comment by 0x5e** [comment]
It's in the dehumidifier subaccessory's setting page, not accessory's setting page. I want to move it out but didn't find a way.

**Comment by SterkeYerke** [comment]
Thanks, I found it. Would be nice if you could move them out to the accessory's setting page.
