### ISSUE TITLE
code:2406

### ISSUE THREAD

**Issue by Networkwilliams** [tuya/tuya-homebridge#325]
I get the following error when trying to use this plugin 

The code 2406 I've checked and the username and password is right and the API details is right but still get the error

Can anyone help please 

[11/29/2022, 9:06:25 PM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge EEA6) is running on port 53027.
TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1669755985655,"tid":"af5914d2702911edac99da3a06eee480"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by luic** [comment]
@Networkwilliams , You may have a malformed config.json, I would try starting from a fresh config.json file. You could also mask your config.json private credentials and post it here, so we can check if there are issues.

**Comment by jaichandra** [comment]
Im also running into same error on homebridge. Below is my plugin config.json.

```
{
    "options": {
        "username": "xxxxxx",
        "password": "xxxxxxxx",
        "accessId": "xxxxxxxx",
        "accessKey": "xxxxxxxxxxx",
        "lang": "en",
        "projectType": "2",
        "appSchema": "tuyaSmart",
        "countryCode": 1,
        "debug": true
    },
    "name": "Jai Langoju",
    "platform": "TuyaPlatformFeitShopLight"
}
```

**Comment by luic** [comment]
@jaichandra, the json formatting seems fine. Yours is a different `appSchema` from mine so I can't say for sure, but the content seems reasonable.

A few ideas...
- updating the plugin? Try the beta?
- start anew, redoing the config
- regenerate any accesskeys/id's that you can, and input those into your config and test it
- looking at other threads to see how people addressed the issue/similar issues
