### ISSUE TITLE
Support Aroma Diffuser

### ISSUE THREAD

**Issue by fadelguy** [tuya/tuya-homebridge#326]
Please add this Arma Diffuser device.

Info:
{
  "result": {
    "active_time": 1669909612,
    "category": "xxj",
    "category_name": "Diffuser",
    "create_time": 1669909612,
    "gateway_id": "",
    "icon": "smart/icon/ay1525833075368tsInS/d90b58d9cba10f1ae4a79badd27d8551.png",
    "id": "bfdb5cf6ea52d73678vy5w",
    "model": "",
    "name": "YX316WIFI",
    "online": true,
    "owner_id": "9371705",
    "product_id": "arkdxfhlkpdyof9x",
    "product_name": "YX316WIFI",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1669933697,
  },

Functions:

 "result": {
    "category": "xxj",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_sound",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Sound",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_led",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_v2",
        "lang_config": {
          "unit": ""
        },
        "name": "Brightness",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_mode",
        "lang_config": {
          "colour": "Colour",
          "colourful1": "Colourful",
          "white": "White"
        },
        "name": "Led Mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "colour_data_hsv",
        "lang_config": {
          "unit": ""
        },
        "name": "Color",
        "type": "Json",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_sound",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Sound",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_led",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_v2",
        "lang_config": {
          "unit": ""
        },
        "name": "Brightness",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_mode",
        "lang_config": {
          "colour": "Colour",
          "colourful1": "Colourful",
          "white": "White"
        },
        "name": "Led Mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "colour_data_hsv",
        "lang_config": {
          "unit": ""
        },
        "name": "Color",
        "type": "Json",
        "values": "{}"
      }
    ]
  },

**Comment by antonioreyna** [comment]
i need this too i hope you can get it work soon thanks!
