### ISSUE TITLE
Support Fingerbot bluetooth devics connected via the BLE mesh gateway Wifi

### ISSUE THREAD

**Issue by fadelguy** [tuya/tuya-homebridge#327]
Please support Fingerbot

Info:

  "result": {
    "active_time": 1669914168,
    "category": "szjqr",
    "category_name": "Finger robot",
    "create_time": 1669914168,
    "gateway_id": "bfcf31e998ae2e74d3eoqc",
    "icon": "smart/icon/ay1550298204274iXb1I/ce28b24ac1bf8f9b1beba4fadc37ee90.png",
    "id": "bfb99c1d8b2f7b3e05mqli",
    "ip": "",
    "model": "ADFB0301",
    "name": "Fingerbot Plus",
    "node_id": "tuya6285d40be643",
    "online": false,
    "owner_id": "9371705",
    "product_id": "yiihr7zh",
    "product_name": "Fingerbot Plus",
    "sub": true,
    "time_zone": "+02:00",
    "update_time": 1669914168,
  },

Functions:
  "result": {
    "category": "szjqr",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "Off",
          "true": "On"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "lang_config": {
          "click": "Click",
          "switch": "Switch"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"switch\"]}"
      },
      {
        "code": "arm_down_percent",
        "lang_config": {
          "unit": "%"
        },
        "name": "Down Movement",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":51,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "click_sustain_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "Sustain Time",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":10,\"scale\":0,\"step\":1}"
      },
      {
        "code": "arm_up_percent",
        "lang_config": {
          "unit": "%"
        },
        "name": "Up Movement",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "tap_enable",
        "lang_config": {
          "false": "Off",
          "true": "On"
        },
        "name": "Touch Control",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "lang_config": {
          "false": "Off",
          "true": "On"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "lang_config": {
          "click": "Click",
          "switch": "Switch"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"switch\"]}"
      },
      {
        "code": "arm_down_percent",
        "lang_config": {
          "unit": "%"
        },
        "name": "Down Movement",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":51,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "click_sustain_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "Sustain Time",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":10,\"scale\":0,\"step\":1}"
      },
      {
        "code": "battery_percentage",
        "lang_config": {
          "unit": "%"
        },
        "name": "Battery Level",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "arm_up_percent",
        "lang_config": {
          "unit": "%"
        },
        "name": "Up Movement",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "tap_enable",
        "lang_config": {
          "false": "Off",
          "true": "On"
        },
        "name": "Touch Control",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },

**Comment by arvin8** [comment]
+1
