### ISSUE TITLE
Unlink app from cloud projects

### ISSUE THREAD

**Issue by Sledneck54** [tuya/tuya-homebridge#329]
Completely lost.
I followed an instructional video on YouTube. Everything worked fine but I wanted to start fresh. I probably missed something in the original setup. I had a rogue device I couldn’t remove from the configuration. 
I’m using the Tuya app. All my devices are setup in the app. I think the problem is I used an older version of Tuya for Homebridge.
I installed the latest Tuya plug-in. Problem I have is my app is already linked to two cloud projects. “The upper limit” I’ve spent hours trying to figure out how to unlink the app from current cloud projects.
I’ve searched every menu in the app and iot/Tuya webpage and come up with nothing. It shows I have two connections but no devices show up in either cloud configuration. Yes, my data center is correct. 
How do you remove the current linked projects from the app or wherever it’s done. I know you can’t delete projects. I just want my devices to show up so I can add them HomeKit.

Side note, I was able to add two of my devices virtually but they are under a child bridge according to the Homebridge log on startup and still don’t show up in HomeKit. 
If the only way to correct this is to change to the Smart life app but I think I’ve used the two permissions there also. I do know changing to a new email doesn’t work either. The app still knows it’s using two. 

Please help

**Comment by Sledneck54** [comment]
Maybe I've asked my question in the wrong place? Someone has to know how to do it.

**Comment by AndySymons** [comment]
I have a similar issue, I think. I had a setup that linked my Smart Life account to a Tuya IoT account. Then I changed my mind and linked it to a different Tuya account (after I realised I only needed a separate project for each home not a separate account). I unlinked from the old account in the app. Mostly this was fine but five devices behaved erratically - sometimes working and sometimes not - and I got the  error "1106 authentication denied" in the Tuya integration of Home Assistant.  

On investigation I found that although I had unlinked the app from the old IoT account, somehow the account still had five devices linked! These are of course precisely the five devices that are causing the issues. It seems the old account got into a corrupted state. 

To solve the issue, I went into the Smart Life app and deleted the five devices. In HA I still had to delete the Tuya integration and reinstate it. I then went through the tedious process of relinking all the devices with their automations, scripts and exposure to Alexa. 

I would be most grateful if Tuya would 
a) fix the bug that devices can be left linked when the app is unlinked 
b) provide manual unlinking of devices as a fallback 
c) provide deletion of projects (with erasure of all associated data) 
d) provide deletion of user account (with erasure of all associated data)

<img width="1440" alt="Screen Shot 2022-12-24 at 20 37 14" src="https://user-images.githubusercontent.com/14819812/209450910-529d1c54-d715-47a8-8fa3-9259cc74a3e3.png">
<img width="1440" alt="Screen Shot 2022-12-24 at 20 37 29" src="https://user-images.githubusercontent.com/14819812/209450911-69315b3a-ec2b-414f-861b-1fa6fe9cb258.png">
<img width="1440" alt="Screen Shot 2022-12-24 at 20 37 59" src="https://user-images.githubusercontent.com/14819812/209450912-04f65763-ed6b-4f93-9cea-d4b65310da60.png">

**Comment by thannerfabian** [comment]
Hello,
my issue seems to be related to this. I added my account and everything works fine. Thanks for that btw. Then i unlinked some devices in the "linked app settings" in the tuya plattform. But these devices are still available from Homebridge and the Apple Home App, which shouldn´t be.

**Comment by AdrianSmartHome** [comment]
Hello,

I had the same problem.  What does Tuya say:
"Currently, a created project cannot be deleted. If your project is going to the end of service, and you want to remove the smart devices that have been linked with the project, you can unlink the devices."

I solved it in the following way: in the old cloud project/service API I revoked Authorization of all servises.
I made a new project and everything started working.

After that I didn't get the message anymore:
(The number of projects linked with this Tuya Smart App account has reached the upper limit of 2. Unlink the account from existing projects and try again.). 

The second way is as in the picture, but I did not find the wizard.

![4](https://user-images.githubusercontent.com/124533548/217527817-b606109c-bdcd-4cd9-adc0-ed47b99385e0.png)

**Comment by Sledneck54** [comment]
There's no way to do it other than sign up with another email account. Either unlink your current devices from the old account or hard reset them. Create a new profile in Tuya and add them. Could be a pain if you have many devices.

**Comment by MickMake** [comment]
This frustrated the heck out of me for a few hours. So posting this here to ensure it doesn't do the same for others...

From: https://www.reddit.com/r/smartlife/comments/tidgls/comment/iet9qrw/?utm_source=share&utm_medium=web3x

1. In the smart home app click the `me button` on the bottom right
2. `settings icon` top right
3. `account and security`
4. `cloud development project`
5. when you click it and ok the `unlink`, it will remove the link to the project

Note: Make sure you are connected to the correct datacentre, (see here: https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb), otherwise you'll see a `SERVER_BUSY` error.

Hope this helps.

**Comment by Henniebrandweer** [comment]
> This frustrated the heck out of me for a few hours. So posting this here to ensure it doesn't do the same for others...
> 
> From: https://www.reddit.com/r/smartlife/comments/tidgls/comment/iet9qrw/?utm_source=share&utm_medium=web3x
> 
> 1. In the smart home app click the `me button` on the bottom right
> 2. `settings icon` top right
> 3. `account and security`
> 4. `cloud development project`
> 5. when you click it and ok the `unlink`, it will remove the link to the project
> 
> Note: Make sure you are connected to the correct datacentre, (see here: https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb), otherwise you'll see a `SERVER_BUSY` error.
> 
> Hope this helps.

There is also no "Cloud developmet project" option in my app. im stuck

**Comment by Guidosmeyers** [comment]
The same problem for me: no 'cloud development project'-option...
