### ISSUE TITLE
Human Presence sensor

### ISSUE THREAD

**Issue by user82767303** [tuya/tuya-homebridge#341]
Hi, is there any plans to start supporting human presence sensor any time soon? I can add it   with some tuya plugins as a wrong type of device but then it doesn't work correctly in the HomeKit. Thanks already!

**Comment by bFollon** [comment]
There is a PR for the Human Presence sensor: [check it here](https://github.com/tuya/tuya-homebridge/pull/247)
Maybe you can install the branch on your system until it is officially merged.

**Comment by bFollon** [comment]
@user82767303 check out this fork of the project:
https://github.com/0x5e/homebridge-tuya-platform

It is maintained and has PIR support.
