### ISSUE TITLE
Smart Heater temperature display issues

### ISSUE THREAD

**Issue by leftbrake** [tuya/tuya-homebridge#345]
**Describe the bug**
SmartHeater XL (C) dispalys correct temperatures (current and desired) in tuya smart app, but not in Homebrigde/HomeKit

**Expected behavior**
Dispaly correct vaules

**Screenshots**
![Homebridge](https://user-images.githubusercontent.com/28144937/222234914-a18b17c5-4885-4818-b7f4-8b2e0bc31028.png)
![tuya](https://user-images.githubusercontent.com/28144937/222235328-f7fedc06-69e6-4790-96ee-c3bd87989e27.jpeg)
![homekit](https://user-images.githubusercontent.com/28144937/222235342-f97defe5-73ab-471f-a3e8-7393c6249d87.jpeg)

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
[homebridge-tuya-platform] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 230 exceeded maximum of 122. See https://homebridge.io/w/JtMGR for more info.

**Comment by Josje92** [comment]
Exactly the same issue here 👋  - so, tagging along!
Think it has something to do with F / C difference..

**Comment by Josje92** [comment]
Made a [PR](https://github.com/tuya/tuya-homebridge/pull/351) for this.

**Comment by leftbrake** [comment]
This is still an issue
