### ISSUE TITLE
How do I add my devices?

### ISSUE THREAD

**Issue by AnonymousPea** [tuya/tuya-homebridge#35]
So I think I have managed to add this to my homebridge system, and then I had added all the details to the config, under home bridge. But it is not working nothing shows up in my home-kit.

**Comment by Hanh94** [comment]
Hi @AnonymousPea , You have configured **config.json** correctly and started the plugin successfully, If you do not see any errors in logs.
Please pair with Homebridge by scanning the QR code printed in the step of starting the plugin, or entering the 8-digit PIN code. You can find the PIN code in the config.json file.
Please try again.

**Comment by AnonymousPea** [comment]
Yep I tried that it still doesn't work. never mind ending up switching back to an old plugin
