### ISSUE TITLE
The current temperature is stuck

### ISSUE THREAD

**Issue by Twisi** [tuya/tuya-homebridge#356]
Hello, the current temperature on the thermostat started to get stuck. It only updates when the bridge is restarted. The temperature is updated, but it immediately gets stuck and no longer shows the current one. You can set the temperature normally. Other Tuya devices work perfectly.

**Comment by Twisi** [comment]
hi, still not working. Any chance of a fix?

**Comment by joshuamio** [comment]
Same here, thanks!

**Comment by Twisi** [comment]
will there be a fix for this problem or not? Thanks

**Comment by Twisi** [comment]
still not working

**Comment by joshuamio** [comment]
Hello, any update about this? Thanks a lot.

**Comment by Twisi** [comment]
hello, unfortunately it still doesn't work.

**Comment by joshuamio** [comment]
Is there any way to completely hide the temperature information?

**Comment by Twisi** [comment]
I didn't solve it, so I don't know. I control via the original Tuya application

**Comment by joshuamio** [comment]
ok, I'll create automation with dummy buttons to start/stop only. Thanks!
