### ISSUE TITLE
Plugin requires a trial license that has a duration of 1 months. License costs >$50,000

### ISSUE THREAD

**Issue by lox** [tuya/tuya-homebridge#359]
As best as I can tell, this plugin needs a license for the IoT Core package. The trial runs for 1 months and it requires manual renewal / extension.

The only way get an ongoing license seems to be to pay 50K USD?

**Comment by lisandro** [comment]
@lox I see that the only way is join the beta https://pages.tuya.com/develop/Homebridgebetainvitation?_source=ea61b9486f59eb89a3ee74b43140b9f3#form

**Comment by afit** [comment]
As far as I can tell, you can't join the beta if you already have Tuya IoT account — at least, not without creating another Tuya IoT account using the link above.

**Comment by lisandro** [comment]
@afit What do you think of control locally with something like https://github.com/iRayanKhan/homebridge-tuya ?

**Comment by jat80** [comment]
is this going to be sorted at all?  I can't run 3.4 devices without having to renew license which Kinda defeats the purpose of this plugin alltogether.

**Comment by jat80** [comment]
> @afit What do you think of control locally with something like https://github.com/iRayanKhan/homebridge-tuya ?

I've tried but this hasn't been updated to run 3.4 devices unfortunately.

**Comment by lox** [comment]
Lame.

**Comment by jat80** [comment]
> Lame.

I guess no one really looked into it from tuya side.  Im guessing they will move tuya products going forward to integrate with matter instead.
