### ISSUE TITLE
Add Support for Anytek P22 BLE Smart Padlock

### ISSUE THREAD

**Issue by ahmadnazirafiq** [tuya/tuya-homebridge#36]
Hi,

It’s great to see more device types added to this official plugin. I just bought a Tuya/Smart Life-enabled fingerprint padlock that runs on Bluetooth but none of the plugins can expose it to HomeKit.

Is this due to the device running on Bluetooth? It would be great if I could contribute to add support for this; as this is the most affordable smart padlock on the market.

Brand: Anytek
Model name: P22+
Pairs with: Smart Life app
Runs on: Bluetooth Low Energy

![C27FB080-24E7-4972-976E-1C96B7826A66](https://user-images.githubusercontent.com/66505845/121871662-f0fd6b00-cd36-11eb-90f3-6f7290293b3e.jpeg)

**Comment by Hanh94** [comment]
Hi @ahmadnazirafiq ,Thank you for your feedback.
This device is not in the Tuya standard instruction set list, please provide the **category** and **status** of this device, so that we can judge whether this category can be supported.
