### ISSUE TITLE
Child Bridge restarting - TypeError: status is not iterable

### ISSUE THREAD

**Issue by mynameisbrendan** [tuya/tuya-homebridge#362]
Child bridge is in a restart loop.  No new devices or other changes were performed.

This started at some point in the last week.

[6/21/2023, 3:14:25 PM] [TuyaPlatform] Restarting Process...
[6/21/2023, 3:14:26 PM] [TuyaPlatform] Launched child bridge with PID 19441
[6/21/2023, 3:14:26 PM] Registering platform 'homebridge-tuya-platform.TuyaPlatform'
[6/21/2023, 3:14:26 PM] [TuyaPlatform] Loaded homebridge-tuya-platform v1.5.0 child bridge successfully
[6/21/2023, 3:14:26 PM] Loaded 3 cached accessories from cachedAccessories.0E7A5689099B.
Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":61,"username":"--REMOVED--","password":"--REMOVED--","schema":"tuyaSmart"}, headers = {"t":"1687324466347","client_id":"--REMOVED--","nonce":"7dcc7e40-0ff2-11ee-84a2-cd2f23f8df57","Signature-Headers":"client_id","sign":"2D0EA092CC87FAFF715AEC95F27358509A13B6CD92D318668FC3F8442743110E","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
[6/21/2023, 3:14:26 PM] Homebridge v1.6.1 (HAP v0.11.1) (TuyaPlatform) is running on port 52430.
TuyaOpenAPI response: {"result":{"access_token":"--REMOVED--","expire_time":7200,"platform_url":"https://openapi.tuyaeu.com","refresh_token":"4366fb824a838592e621f4c8fef94c78","uid":"eu1598575686922ZhVj1"},"success":true,"t":1687324467718,"tid":"7ea8f4720ff211ee9b65f25b5112df17"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1687324467260","client_id":"--REMOVED--","nonce":"7dcc7e40-0ff2-11ee-84a2-cd2f23f8df57","Signature-Headers":"client_id","sign":"26FDD365B866C270E0FFCB58B271EE9E4868F9A00E1501469159CD5512C7489D","sign_method":"HMAC-SHA256","access_token":"--REMOVED--","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1662250058,"biz_type":0,"category":"cz","create_time":1662250058,"icon":"smart/icon/ay1556838860681oKmdO/a475d09a86f87279a5fb63d3e8bcba84.png","id":"bf738ddd34019838ca4cjt","ip":"","lat":"-38.3222","local_key":"88105f9148b08800","lon":"144.3100","model":"EmateSocket","name":"Irrigation Hub","node_id":"2FB","online":true,"owner_id":"15387441","product_id":"hzsl8cxxtpd0x56b","product_name":"Wi-Fi Socket","status":[{"code":"switch_1","value":false}],"sub":true,"time_zone":"+10:00","uid":"eu1598575686922ZhVj1","update_time":1687320780,"uuid":"bf738ddd34019838ca4cjt"},{"active_time":1662250061,"biz_type":0,"category":"kg","create_time":1662250061,"icon":"smart/icon/ay1556838860681oKmdO/ab17f6e4e677bba7d3868a7a57cfe5b7.png","id":"bf701b8169db998d1dvyaq","ip":"","lat":"-38.3222","local_key":"88105f9148b08800","lon":"144.3100","model":"EMateWTT","name":"Back Garden Water","node_id":"2F1","online":true,"owner_id":"15387441","product_id":"zrsgzc8jktsricjj","product_name":"WX1 Tap Timer","sub":true,"time_zone":"+10:00","uid":"eu1598575686922ZhVj1","update_time":1687177786,"uuid":"bf701b8169db998d1dvyaq"},{"active_time":1662191588,"biz_type":0,"category":"wg2","create_time":1662191588,"icon":"smart/icon/ay1556838860681oKmdO/1746f926ee7e6541d8188bf6ec32801f.png","id":"bf2c9d3b916ec8297fiujb","ip":"218.215.120.105","lat":"-38.3222","local_key":"88105f9148b08800","lon":"144.3100","model":"Emate gateway","name":"Wi-Fi Hub","online":true,"owner_id":"15387441","product_id":"v9vxvkwqa48ayhlr","product_name":"Wi-Fi Hub","status":[{"code":"factory_reset","value":false},{"code":"night_light_color","value":"light_white"}],"sub":false,"time_zone":"+10:00","uid":"eu1598575686922ZhVj1","update_time":1687177782,"uuid":"18cb48773b8c3657"},{"active_time":1661733940,"biz_type":0,"category":"cs","create_time":1592802607,"icon":"smart/icon/ay15253387844269Sg99/7ec0da9bc2c1cbb719a5a04977f55097.png","id":"73050322500291bdd1b3","ip":"218.215.120.105","lat":"-38.3222","local_key":"181ffc8b1feba6b9","lon":"144.3100","model":"KAWFSMDEHUA","name":"Dehumidifier","online":true,"owner_id":"15387441","product_id":"jhpmwtl30x7i3sts","product_name":"Dehumidifier","status":[{"code":"switch","value":false}],"sub":false,"time_zone":"+10:00","uid":"eu1598575686922ZhVj1","update_time":1687091271,"uuid":"73050322500291bdd1b3"},{"active_time":1661730238,"biz_type":0,"category":"dd","create_time":1661070177,"icon":"smart/icon/ay1556838860681oKmdO/3539166640e41017d0d500dc7e38bba2.png","id":"bfda6c027f8d9aea87tium","ip":"218.215.120.105","lat":"-38.3222","local_key":"1ee194f73cae245b","lon":"144.3100","model":"CLXW60","name":"WW Garden Light","online":true,"owner_id":"15387441","product_id":"ynxvgxqggwz5rqvs","product_name":"Holman WW WiFi Light Controller","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"white"},{"code":"bright_value","value":455},{"code":"temp_value","value":952},{"code":"scene_data","value":"{\"scene_num\":4,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":500,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":0}]}"},{"code":"countdown","value":0}],"sub":false,"time_zone":"+10:00","uid":"eu1598575686922ZhVj1","update_time":1687052181,"uuid":"3cbbec87435b0e66"}],"hsa_more":false,"last_row_key":"9914AC12470EE1EE4084ACB3B5160C85","total":5},"success":true,"t":1687324468845,"tid":"7f5137b50ff211ee9b65f25b5112df17"} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/functions, params = {"device_ids":"bf738ddd34019838ca4cjt,bf701b8169db998d1dvyaq,bf2c9d3b916ec8297fiujb,73050322500291bdd1b3,bfda6c027f8d9aea87tium"}, body = null, headers = {"t":"1687324468385","client_id":"--REMOVED--","nonce":"7dcc7e40-0ff2-11ee-84a2-cd2f23f8df57","Signature-Headers":"client_id","sign":"3639A6A74FBAA653B5FAE495A03AD8CC07517C957DCB81EC7BE19D8FF4F3116C","sign_method":"HMAC-SHA256","access_token":"--REMOVED--","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":[{"category":"cs","devices":["73050322500291bdd1b3"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"}],"product_id":"jhpmwtl30x7i3sts"},{"category":"dd","devices":["bfda6c027f8d9aea87tium"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value","desc":"bright value","name":"bright value","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value","desc":"temp value","name":"temp value","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"scene_data","desc":"scene data","name":"scene data","type":"Json","values":"{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Integer","values":"{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"Json","values":"{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"}],"product_id":"ynxvgxqggwz5rqvs"},{"category":"wg2","devices":["bf2c9d3b916ec8297fiujb"],"functions":[{"code":"factory_reset","desc":"factory reset","name":"factory reset","type":"Boolean","values":"{}"},{"code":"night_light_color","desc":"night light color","name":"night light color","type":"Enum","values":"{\"range\":[\"light_white\",\"light_warm_yellow\"]}"}],"product_id":"v9vxvkwqa48ayhlr"},{"category":"cz","devices":["bf738ddd34019838ca4cjt"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"}],"product_id":"hzsl8cxxtpd0x56b"}],"success":true,"t":1687324469952,"tid":"7ff85a550ff211ee877ea657e9038830"} path = /v1.0/devices/functions
Adding: Irrigation Hub (cz / bf738ddd34019838ca4cjt)
Existing Accessory found Irrigation Hub  bf738ddd34019838ca4cjt f259f289-ad2e-4133-97b9-4cb51b7a39a5
Adding: Back Garden Water (kg / bf701b8169db998d1dvyaq)

**/homebridge/node_modules/homebridge-tuya-platform/util/datautil.js:6
        for (var map of status) {
                        ^
TypeError: status is not iterable
    at DataUtil.getSubService (/homebridge/node_modules/homebridge-tuya-platform/util/datautil.js:6:25)
    at TuyaPlatform.addAccessory (/homebridge/node_modules/homebridge-tuya-platform/index.js:144:41)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:99:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/21/2023, 3:14:29 PM] [TuyaPlatform] Child bridge process ended
[6/21/2023, 3:14:29 PM] [TuyaPlatform] Process Ended. Code: 1, Signal: null**

**Comment by Claywd** [comment]
I've got the same problem. It happened after I added the fingerbot and gateway to the app.

**Comment by mynameisbrendan** [comment]
I moved to '_homebridge-tuya-platform_' plugin.  Resolved the issue and added a lot more options.
