### ISSUE TITLE
Plugin all of a sudden extremely unresponsive 

### ISSUE THREAD

**Issue by asander85** [tuya/tuya-homebridge#365]
**Describe the bug**
Plugin was working fine for over a year, all of a sudden it started being unresponsive and EXTREMELY slow. Restarting homebrigde resolves for around 30 minutes, then starts having issues again. Getting error in the logs: “this plugin slows down homebridge”.

**Comment by cappsu77** [comment]
Have the same issue.  Devices have been unresponsive using the Tuya Platform plug-in for the past 6-8 weeks.  Is there an update/fix coming soon?

**Comment by asander85** [comment]
There was no update to the plugin nor a response on the issues. This is a stale unresolved issue on the part of the developer, not the users. Would appreciate this issue remaining open until it is addressed versus just closing is due to age without being looked at. 
Thanks.

**Comment by asander85** [comment]
Again, no action or update provided, issue continues to persist, not a stale issue. Would appreciate actually addressing these issues instead of just closing them after months of inactivity.
