### ISSUE TITLE
Plugin not displaying Outlet names in Homekit

### ISSUE THREAD

**Issue by Fastasabadger** [tuya/tuya-homebridge#37]
I have the issue where most of my devices are just displaying as switch_1 in the Apple Home app.

![IMG_1763](https://user-images.githubusercontent.com/86151869/122640694-d6414280-d0f8-11eb-8461-73773d28df04.PNG)

They are however named in the Tuya App and appear correctly on the IoT.   I can see that the Tuya Plugin is aware of the name of the device, but displays it as switch_1 

It appears that the bulbs I use appear to populate their names correctly but none of the outlets or switches do.

LOG EXAMPLE FOR AN ACCESSORY DISPLAYING AS SWITCH_1

`"model":"MK11","name":"Immersion Heater","online":true,"owner_id":"489372","product_id":"qCY4YFq02AP0i1Uu","product_name":"海贝通用定时器MK11","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"+01:00","uid":"eu1510862576411uv6Ld","update_time":1624098269,"uuid":"02200434dc4f221a50ed"},`

`Adding: Immersion Heater (cz / 02200434dc4f221a50ed)
Existing Accessory found Immersion Heater  02200434dc4f221a50ed 5c27c49f-377a-4309-9413-bf521d06453c`

**Comment by Hanh94** [comment]
Hi @Fastasabadger ,Thank you for your feedback.
We are aware of this issue with the plugin and will fix it soon in the next release.

**Comment by unike** [comment]
Hello, I have the same issue and I’m on version 1.1.9, just removed the cached accessories but the issue remains.

**Comment by Hanh94** [comment]
> Hello, I have the same issue and I’m on version 1.1.9, just removed the cached accessories but the issue remains.

Hi @unike ,
The correct **deviceconfig.name** is assigned to **accessory.displayName** when you create an accessory object, and you can also set the name of the accessory when you reconfigure it to the Home app.
