### ISSUE TITLE
No Devices Appear

### ISSUE THREAD

**Issue by markandersonus** [tuya/tuya-homebridge#377]
I have created an iOT project and linked to Tuya app. I see the device in the cloud project.

The plugin-loads and says it found the device, but it doesn't show as an accessory:

TuyaOpenAPI response: {"result":[{"category":"zndsj","devices”:[“xxxxxxxxxxxxxxxxx”],”functions":[{"code":"up_down","desc":"up down","name":"up down","type":"Enum","values":"{\"range\":[\"up\",\"down\",\"stop\",\"continue\"]}"},{"code":"level","desc":"level","name":"level","type":"Enum","values":"{\"range\":[\"level_1\",\"level_2\",\"level_3\"]}"},{"code":"percent_control","desc":"percent control","name":"percent control","type":"Integer","values":"{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"},{"code":"child_lock","desc":"child lock","name":"child lock","type":"Boolean","values":"{}"},{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"}],"product_id":"8qfqlfvwyx3wcji6"}],"success":true,"t":1705888272597,"tid”:”xxxxxxxxxxxxxxxxxxxx”} path = /v1.0/devices/functions
**Adding: TV Lift (zndsj / xxxxxxxxxxxxxxxxxxxx)**
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/iot-03/open-hub/access-config, params = null, body = {"uid":"az17057694925024xhYh","link_id":"b5cd3a80-b8c8-11ee-a9bc-9b5d9986191d","link_type":"mqtt","topics":"device","msg_encrypted_version":"1.0"}, headers = {"t":"1705888272690","client_id”:”xxxxxxxxxxxxxx”,”nonce”:”xxxxxxxxxxxxxxxxxxx”,”Signature-Headers":"client_id","sign”:”xxxxxxxxxxxxxx”,”sign_method":"HMAC-SHA256","access_token”:”xxxxxxxxxxxxxx”,”lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}

**Comment by romeolazar** [comment]
I have the same issue, kinda. I am using homebridge-tuya. I connect the plugin to IoT account/project. I have extended the subscription for another 6 month, but the devices are not shown in HB.
