### ISSUE TITLE
Heater is not showing up/working properly.

### ISSUE THREAD

**Issue by eastrockdev** [tuya/tuya-homebridge#378]
I am trying to connect a heater to this plugin with 0 success. The heater connects, and I am able to turn it on/off via HomeKit. The issues are: 

**1) The temperature is super inaccurate. (Referenced in screenshot)**
**2) I cannot set or adjust the temperature in HomeKit, opening the accessory shows a blank screen. (Referenced in screenshot)**

It should display like a thermostat with the CORRECT current temperature. It appears that it is sending the temperature as Celsius and then homekit is converting Celsius to Fahrenheit which is why the temperature in the image is so high. This plugin with the only accessory I want to connect currently 100% unusable. 

![IMG_2417](https://github.com/tuya/tuya-homebridge/assets/87349597/9bdae72e-a5b4-41d4-af73-140797bbdac5)
![IMG_2418](https://github.com/tuya/tuya-homebridge/assets/87349597/a636c4ec-2181-4e6f-bfad-b93054474764)

**Comment by eastrockdev** [comment]
> Thank you for your feedback, we will solve this issue soon

Doubtful.

**Comment by benjamin-sydney** [comment]
I am having the same issue a year and a half later.
