### ISSUE TITLE
Tuya not working anymore 

### ISSUE THREAD

**Issue by NebuNC2** [tuya/tuya-homebridge#379]
Hello,
since Friday Tuya don’t work anymore.
All devices show up in HomeKit but don’t work.

so I restarted Homebridge on my Pi3 but still nothing works. Then I checked the log and was quit confused because there are no logs of the Tuya Plugin. Just that it gets loaded. Nothing else. No errors, anything.

So I tried to check the Cloud project on Tuya IOT.
Login was successful but I am not able to go to the projects.

is there something wrong? Can somebody help?

I also installed the beta plugin of Tuya. Still didn’t work so I uninstalled it again and now no device is shown in HomeKit. Again no errors.

thanks in advance

**Comment by tonyqiu1019** [comment]
I am affected by this issue as well. I also use Homebridge to connect Tuya devices to Apple Home. The symptoms have been similar to what @NebuNC2 described. Please let me know if there's any further information I can provide, and hope we could resolve this issue soon!

**Comment by mpen01** [comment]
Same issue for me as well.  Stopped working yesterday.

**Comment by NebuNC2** [comment]
Got a solution.
My Tuya IOT core  service / free trial was expired.
I don’t know since when, but you need to refresh every 6 months if selected.

**Comment by NebuNC2** [comment]
Go to https://iot.tuya.com/cloud/products? productType=all.
This shows a list of their cloud services.
When I went there after receiving the
"contract expiring" email from Tuya, it showed the services that were expiring,
provided links to renew.

**Comment by tonyqiu1019** [comment]
> Go to https://iot.tuya.com/cloud/products? productType=all. This shows a list of their cloud services. When I went there after receiving the "contract expiring" email from Tuya, it showed the services that were expiring, provided links to renew.

Can confirm renewing the "IoT core" service and restarting HB solved the issue for me. The renewal form seemed to be automatically approved after ~3 minutes.

Fixing extra space in link: https://iot.tuya.com/cloud/products?productType=all
