### ISSUE TITLE
Add Support for Duux Whisper Flex Fan

### ISSUE THREAD

**Issue by appletrapz** [tuya/tuya-homebridge#38]
Hi, 
I own a Duux Whisper Flex Fan and i can toggle the fan On/Off in HomeKit but I cannot control the fan speeds or modes (standard/nature/sleep) or oscillating modes (horizontal/vertical swing).

These fan modes and oscillating modes do show up and are controllable from the Tuya Smart App, but are not available in HomeKit.

**Comment by Hanh94** [comment]
Hi @appletrapz , Thank you for your feedback.
Under normal circumstances, **Fanv2Accessory** supports the following functions through access to **deviceConfig.status**:  **Active**, **targetFANState**, **LockPhysicalControls**, **RotationDirection**, **RotationSpeed**, and **SwingMode**
Please provide detailed status information of the device so that we can help you resolve this issue.

**Comment by appletrapz** [comment]
@Hanh94 this is the log if it helps? 

``` TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/functions, params = {"device_ids":"42176013e868e7833640"}, body = null, headers = {"t":"1624248706519","client_id":"xxx","sign":"xxx","sign_method":"HMAC-SHA256","access_token":"xxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.1.9"} ```

``` TuyaOpenAPI response: {"result":[{"category":"fs","devices":["42176013e868e7833640"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"fan_speed","desc":"fan speed","name":"fan speed","type":"Enum","values":"{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\"]}"}],"product_id":"dune79w7bsu6dg3e"}],"success":true,"t":1624248706957} path = /v1.0/devices/functions ```

**Comment by Hanh94** [comment]
Hi @appletrapz ,Thank you for your feedback.
From the device information you provided, this device only supports **switch** and **fan_speed**. We have already supported the **fan_speed** attribute of the old version of the fan device in the new version v1.2.0, you can update and try again.

**Comment by appletrapz** [comment]
Hi, my device supports **fan_horizontal,** **fan_vertical,** **mode,** and **switch** 
this is my schema from a different plugin **homebridge-tuya-lan**
```
Intercepted config from Tuya

Found 1 device:
[
  {
    name: 'Whisper Flex',
    id: '42176013e868e7833640',
    key: 'xxx',
    def: {
      schema: '[{"mode":"rw","code":"switch","name":"\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-power","id":1,"type":"obj","desc":"1\\u5f00;\\n0\\u5173;"},{"mode":"rw","code":"mode","name":"\\u5de5\\u4f5c\\u6a21\\u5f0f","property":{"range":["0","1","2"],"type":"enum"},"iconname":"icon-fengli","id":2,"type":"obj","desc":"0\\u6b63\\u5e38\\u98ce;\\n1\\u81ea\\u7136\\u98ce;\\n2\\u7761\\u7720\\u98ce;"},{"mode":"rw","code":"fan_speed","name":"\\u98ce\\u901f","property":{"range":["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26"],"type":"enum"},"iconname":"icon-a_fan_low","id":3,"type":"obj","desc":"\\u3010\\u5fc5\\u9009\\u3011\\u53ef\\u6839\\u636e\\u5b9e\\u9645\\u6863\\u4f4d\\u9700\\u6c42\\u6269\\u5c55"},{"mode":"rw","code":"fan_horizontal","name":"\\u5de6\\u53f3\\u6446\\u98ce","property":{"range":["0","1"],"type":"enum"},"iconname":"icon-tcl_function_vs1","id":4,"type":"obj","desc":"1\\u5f00;\\n0\\u5173"},{"mode":"rw","code":"fan_vertical","name":"\\u4e0a\\u4e0b\\u6446\\u98ce","property":{"range":["0","1"],"type":"enum"},"iconname":"icon-dp_shake","id":5,"type":"obj","desc":"1\\u5f00;\\n0\\u5173"},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6","property":{"range":["0","1","2","3","4","5","6","7","8","9","10","11","12"],"type":"enum"},"iconname":"icon-dp_time2","id":6,"type":"obj","desc":"0\\uff1a\\u53d6\\u6d88\\n\\u5355\\u4f4d\\u5c0f\\u65f6"},{"mode":"ro","code":"countdown_left","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"unit":"\\u5c0f\\u65f6","min":0,"max":12,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time3","id":7,"type":"obj","desc":""}]',
    },
  },
]
```

**Comment by appletrapz** [comment]
Hi, @Hanh94  I just updated the plugin to v1.2.0 and it now gives me the option in HomeKit to change the fan speed but nothing happens when i adjust the speed. 

log
```
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/42176013e868e7833640/commands, params = null, body = {"commands":[{"code":"fan_speed","value":4}]}, headers = {"t":"1624379115462","client_id":"xxx","sign":"xxx","sign_method":"HMAC-SHA256","access_token":"xxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.0"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/42176013e868e7833640/commands, params = null, body = {"commands":[{"code":"switch","value":true}]}, headers = {"t":"1624379115484","client_id":"xxx","sign":"xxx","sign_method":"HMAC-SHA256","access_token":"xxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.0"}
TuyaOpenAPI response: {"code":1104,"msg":"type is incorrect","success":false,"t":1624379115778} path = /v1.0/devices/42176013e868e7833640/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1624379115814} path = /v1.0/devices/42176013e868e7833640/commands
```

**Comment by appletrapz** [comment]
Hi, @Hanh94 

quick update after updating to v1.2.0 I've noticed the plugin now shows the correct functions but like I said before changing the fan speed inside of HomeKit doesn't do anything.

``` TuyaOpenAPI response: {"result":[{"category":"fs","devices":["42176013e868e7833640"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"fan_speed","desc":"fan speed","name":"fan speed","type":"Enum","values":"{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\"]}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"nature\",\"sleep\",\"smart\"]}"},{"code":"switch_horizontal","desc":"switch horizontal","name":"switch horizontal","type":"Boolean","values":"{}"},{"code":"switch_vertical","desc":"switch vertical","name":"switch vertical","type":"Boolean","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Enum","values":"{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"]}"}],"product_id":"dune79w7bsu6dg3e"}],"success":true,"t":1624461550586} path = /v1.0/devices/functions ```

**Comment by Hanh94** [comment]
Hi @appletrapz ,We have modified your device information in the latest version, please update and try again, if you have any questions, please contact us

**Comment by appletrapz** [comment]
Hi @Hanh94, I can confirm v1.2.1 fixes the fan speed, the only thing I've noticed is when turning Oscillate **OFF** it doesn't stay in the **OFF** position it always defaults back to the **ON** position inside of HomeKit. so in order to turn Oscillate **ON** I first have to toggle it **OFF** and then back **ON** but apart from that everything works fine

**Comment by Hanh94** [comment]
> Hi @Hanh94, I can confirm v1.2.1 fixes the fan speed, the only thing I've noticed is when turning Oscillate **OFF** it doesn't stay in the **OFF** position it always defaults back to the **ON** position inside of HomeKit. so in order to turn Oscillate **ON** I first have to toggle it **OFF** and then back **ON** but apart from that everything works fine

Hi @appletrapz , Sorry for taking so long to reply.
Please provide the **TuyaOpenAPI response** log returned by the `/v1.0/iot-01/associated-users/devices`

**Comment by Hanh94** [comment]
Hi @appletrapz , Since we haven't received your reply for a long time, we think our latest version should have solved your problem. We will close this issue first. If there is any problem, you can contact us at any time.
