### ISSUE TITLE
Tuya Platform 1.5.0 - no connection to tuya

### ISSUE THREAD

**Issue by Matze-smart** [tuya/tuya-homebridge#381]
Hello everybody,

i have installed Hoobs 4.3.1 on an Orange Pi (Athome Bridge) and using the Tuya Platform Plugin (1.5.0 • Published November 3rd, 2021).

Everything worked great and all my devices were transferred. Devices that were added later were also transferred to HomeKit.

Unfortunately, the control of the devices has stopped working for a week. The devices are displayed in HomeKit and can also be controlled in Hoobs. 
However, nothing happens. Logins etc. have not been changed. Tuya loT is also online (?).
Does anyone have the same problem and have been able to solve it?

Thank you so much.😊

![image](https://github.com/tuya/tuya-homebridge/assets/159235766/7e0782e7-4e20-4220-a385-9356cc4e7e9b)

**Comment by BonRm** [comment]
@Matze-smart all of your device are unresponsive on HomeKit? mine are not controllable also on hoobs platform on the accessories section..

**Comment by Matze-smart** [comment]
@BonRm 
In HomeKit and Hoobs all the devices are shown. I can control them in HomeKit and this is shown in Hoobs. It also works the other way (Hoobs > HomeKit). 
But no matter what I do, the devices do not respond to any input. I have not yet tested deleting and reinstalling the bridge including the plugin. The devices will probably no longer be displayed at all. I wanted to avoid that too, otherwise I would have to recreate all my automations in HomeKit. 
Besides, everything worked once. Has Tuya changed anything? Additional authentication for IoT cloud or could it be due to my network (IP addresses/firewall/etc)?

Thank you 🙏🏻

**Comment by BonRm** [comment]
@Matze-smart now that you mentioned I noticed the same exact behavior with my home app and hoobs. The device status is updated between HomeKit and hoobs but the real device is not changing the status and cannot be controlled. 

I tried to remove the iot authorization of the iot cloud platform on smart life app and added it again but this didn’t solve the problem. 

I don’t think is your network unless you didn’t change settings. I didn’t change anything on my network and device but they just stopped working.

And I also didn’t try to reinstall the bridge.

Anyone else with the same problem?

**Comment by BonRm** [comment]
@Matze-smart just found the solution 
Follow what they said here https://github.com/tuya/tuya-homebridge/issues/379

You need to submit a request to renew the trial of the iot core service for 6 months. It will be approved in few mins.  I just did it and now the device are working again after a reboot of hoobs

**Comment by Matze-smart** [comment]
@BonRm 

Thank you very much! I hope it works to get new 6 month test period.😊
