### ISSUE TITLE
Smart Life compatibility

### ISSUE THREAD

**Issue by Stetocasa** [tuya/tuya-homebridge#4]
Hello Tuya team. 
The plug-in works also for Smart Life user?

**Comment by zlinoliver** [comment]
@Stetocasa we are planning to support "Smart Home" type of Cloud project in [Tuya IoT Platform](https://iot.tuya.com/cloud/) in May,2021. If this works, you can use Smart Life app to pair Tuya devices to HomeKit directly.

**Comment by zlinoliver** [comment]
Hi @Stetocasa we have updated the plugin to support Smart Life user two days ago, please check our [Integrating Home Assistant & HomeKit](https://developer.tuya.com/en/docs/iot/HA_HB_Bestpractice?id=Kamfbszoffjmw) tutorials and try it, let us know if it works for you. Thanks!
