### ISSUE TITLE
Please add support for Curtains

### ISSUE THREAD

**Issue by a7mad3bdullah** [tuya/tuya-homebridge#44]
Daer Tuya Team, 

Thank you for creating this plug-in, I was eager to have it, really appreciate that. 

It would be great if you add support for [Tuya supported Curtains](https://www.aliexpress.com/wholesale?catId=0&initiative_id=AS_20210624133132&SearchText=tuya+curtain+motor).

Thank you

**Comment by Hanh94** [comment]
Hi @a7mad3bdullah ,Sorry for taking so long to reply.
This category has been planned, Please stay tuned.

**Comment by notorioustubze** [comment]
Commenting for the update once this is published.

**Comment by Hanh94** [comment]
Hi @a7mad3bdullah @notorioustubze , sorry about that.
Each time we update the version, we will indicate the update in the [release](https://github.com/tuya/tuya-homebridge/releases).
Please update the latest version and try again.

**Comment by a7mad3bdullah** [comment]
Thank you team, updated and works great now.
![IMG_20210807_092615_648](https://user-images.githubusercontent.com/44746139/128590689-f9775c68-2a45-476c-a14c-1bcf8d274e8d.jpg)
![IMG_20210807_092618_293](https://user-images.githubusercontent.com/44746139/128590693-0fd03907-578d-41c4-81fa-75d2fb4e63fc.jpg)
