### ISSUE TITLE
2406 error

### ISSUE THREAD

**Issue by gjs12** [tuya/tuya-homebridge#45]
I get the 2406 error but the access id and key are correct, the project and tuya account have been created on 24 June and I've updated the plugin today to the latest version 1.2.1.

![image](https://user-images.githubusercontent.com/45442322/123343780-cc568e00-d595-11eb-8554-3d52a616a5c7.png)

**Comment by shamanskyh** [comment]
I also get this error and I'm not sure how to proceed -- I created my project/key yesterday and have confirmed that the values are exactly correct in my config.

**Comment by shamanskyh** [comment]
@gjs12 your screenshot above includes your password in the debug output -- you probably want to redact that

**Comment by gjs12** [comment]
No, it is some  replacement code. The logs don't show the actual passwords and secret keys

**Comment by Hanh94** [comment]
Hi @gjs12 @shamanskyh , logs already protect important information.
We observed a problem with the data in Australia, which has now been fixed. If your configuration is correct, you can restart the plugin and try again

**Comment by Hanh94** [comment]
> Hi @gjs12 @shamanskyh , logs already protect important information.
> We observed a problem with the data in Australia, which has now been fixed.And your cloud project **Availability Zone** needs to be located in Europe , If your configuration is correct, you can restart the plugin and try again

**Comment by gjs12** [comment]
Hi Hanh94, still the same issue unfortunately.

**Comment by zlinoliver** [comment]
@gjs12 could you check if your IoT cloud project is created after May 25th, 2021? Your cloud project's Availability Zone needs to be Europe, as your region is Australia (country code 61).

**Comment by zlinoliver** [comment]
The error code is 2406, please check the last faq of the doc: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt

Troubleshoot:
1. Your cloud project on the [Tuya IoT Platform](https://iot.tuya.com/cloud/) should be created after May 25, 2021. Otherwise, you need to create a new project or migrate data to a new project. For more information, see [Operation on the Tuya IoT Platform](https://developer.tuya.com/en/docs/iot/migrate-from-an-older-version?id=Kamee9wtbd00b#title-3-Operation%20on%20the%20Tuya%20IoT%20Platform).
2. On the [Tuya IoT Platform](https://iot.tuya.com/cloud/), you have linked devices by using Tuya Smart or Smart Life app in your cloud project.

**Comment by gjs12** [comment]
Yes, my cloud project was created on 24 June 2021 and I used the Tuya smart app to link my devices in the app and they do show up in the Europe zone in my project's devices list, a power plug and a motion sensor. I'm also using the correct username and password, I've checked it multiple times.

**Comment by shamanskyh** [comment]
Hey folks -- I think I've resolved this issue for myself and thought I'd share what I learned here in case it's helpful.

In my cloud project, the only availability zone I had selected was "America" and I set my country code my config.json to 1. Adding "Eastern America" to my availability zones seems to have solved the authentication issue for me.

**Comment by Hanh94** [comment]
Hi @shamanskyh @gjs12 ,Sorry for the late reply.

Recently, our team has been sorting out interface issues such as code 2406. 
The same country code for Tuya SmartLife apps on different phones may correspond to different **Availability zones**.
Therefore, we recommend that you select all available **Availability Zones** in the cloud project, and we will improve the plugin login experience as soon as possible.
Hope this doc has been helpful: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt. Any questions, please contact us.

**Comment by gjs12** [comment]
Hi @Hanh94, I've added all zones to the availability zones but so far hasn't made a difference.

**Comment by Hanh94** [comment]
> Hi @Hanh94, I've added all zones to the availability zones but so far hasn't made a difference.

Hi @gjs12 ,Sorry for the late reply.
The login error code 2406 only has two cases:
1.Use accessID and accessKey that were created before May 25, 2021.
2.The project created is after May 25, 2021, but there is no associated Tuya smart or Smart Life APP account.

Please check your configuration and contact us if you have any questions.

**Comment by gjs12** [comment]
Hi @Hanh94, something must have changed at the back end as it is working now. The power plug is showing up, not the motion sensor but that might be because it is not supported (yet).

**Comment by Hanh94** [comment]
> Hi @Hanh94, something must have changed at the back end as it is working now. The power plug is showing up, not the motion sensor but that might be because it is not supported (yet).

Hi @gjs12 , The [categories](https://github.com/tuya/tuya-homebridge/wiki/Supported-Tuya-Device-Types) we currently support.

**Comment by Hanh94** [comment]
> Hi @Hanh94, something must have changed at the back end as it is working now. The power plug is showing up, not the motion sensor but that might be because it is not supported (yet).

Hi @gjs12 , Regarding Device Support, please submit a **New Device Support** issue. 

If there are no problems with error code 2406 for login, the issue will be closed. Thank you for your contribution.
