### ISSUE TITLE
1106 Error

### ISSUE THREAD

**Issue by geekseanlin** [tuya/tuya-homebridge#46]
Hi,

I still have 1106 error no matter how many times I check and re-check the configs, all seems to be ok. My access ID was created in June 2021. My devices are already linked and online in Tyua IoT Platform as well.

Can it be because my login is also linked to Apple ID login?

```
TuyaOpenAPI response: {"code":1106,"msg":"權限拒絕","success":false,"t":1624701623779} path = /v1.0/iot-01/associated-users/actions/authorized-login
Please confirm that the Access ID and Access Secret of the Smart Home PaaS project you are using were created after May 25, 2021.
Please linked devices by using Tuya Smart or Smart Life app in your cloud project.
Failed to get device information. Please check if the config.json is correct.
```

**Comment by Hanh94** [comment]
Hi @geekseanlin ,Sorry for the late reply.
Recently, our team has been sorting out interface issues such as code 2406, code 1106. 
The same country code for Tuya SmartLife apps on different phones may correspond to different **Availability zones**.
Therefore, we recommend that you select all available **Availability Zones** in the cloud project, and we will improve the plugin login experience as soon as possible.

Hope this doc has been helpful: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt

**Comment by geekseanlin** [comment]
I have selected everything in Availability Zones but still showing the same error.

**Comment by Hanh94** [comment]
What's **CountryCode** that you set？

**Comment by geekseanlin** [comment]
95

**Comment by Hanh94** [comment]
Hi @geekseanlin , Try the **endPoint** : **https://openapi.tuyaus.com** Or **https://openapi-ueaz.tuyaus.com**

**Comment by geekseanlin** [comment]
@Hanh94 Hi, still having the same error

**Comment by Hanh94** [comment]
Hi @geekseanlin , Please show us the log information of **TuyaOpenAPI request:** And The APP associated with the cloud project is  tuyaSmart APP or  smartLife APP?

**Comment by Hanh94** [comment]
Another option: Cloud project -> device list 
To see which region has your device, use that region's endpoint

**Comment by geekseanlin** [comment]
This is the request

Initializing TuyaPlatform...
`TuyaOpenAPI request: method = post, endpoint = https://openapi-ueaz.tuyaus.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":95,"username":"USERNAME","password":"PASS","schema":"smartlife"}, headers = {"t":"1625154108330","client_id":"w7nhwaxkaos16sbujscs","nonce":"d89f1500-da82-11eb-901c-fd4fe6f5bf7a","Signature-Headers":"client_id","sign":"73C793E7CE288B70FA72435F0BBA6264AE3CE367581FE632ACE635371FB51151","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}`

My region is US in the device list and using Smartlife app

**Comment by pngo** [comment]
Could it be due to the config of "schema":"smartlife"  ? 
But the documentation says to use smart**L**ife with a uppercase L (https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt#title-2-Edit%20the%20configuration%20file)

Is it case sensitive ?

**Comment by ElphaX** [comment]
If there is any inkling of causation some fellow users may be able to assist in diagnosing?

**Comment by geekseanlin** [comment]
I tried to change the schema to smartLife but the same result. The only difference I have is - I have also linked to sign in with Apple ID on my smartlife app.

**Comment by enjoymj** [comment]
Similar issue here

Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":86,"username":"USERNAME","password":"PWD","schema":"tuyaSmart"}, headers = {"t":"1625394028565","client_id":"ACCESSKEY","nonce":"744a7190-dcb1-11eb-8422-d7681144925c","Signature-Headers":"client_id","sign":"FEB5A33D6D227E6011FEC02E9CD3EE79F033F8C048AC02D9C07B2D4B5E2386B6","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}
Starting to advertise 'TuyaPlatform 7C96' using bonjour-hap backend!
[7/4/2021, 6:20:28 PM] Homebridge v1.3.4 (TuyaPlatform) is running on port 52242.
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1625394029009} path = /v1.0/iot-01/associated-users/actions/authorized-login

**Comment by Hanh94** [comment]
Hi @geekseanlin @pngo @ElphaX , Sorry for the late reply.


> Similar issue here
> 
> Initializing TuyaPlatform...
> TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":86,"username":"USERNAME","password":"PWD","schema":"tuyaSmart"}, headers = {"t":"1625394028565","client_id":"ACCESSKEY","nonce":"744a7190-dcb1-11eb-8422-d7681144925c","Signature-Headers":"client_id","sign":"FEB5A33D6D227E6011FEC02E9CD3EE79F033F8C048AC02D9C07B2D4B5E2386B6","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}
> Starting to advertise 'TuyaPlatform 7C96' using bonjour-hap backend!
> [7/4/2021, 6:20:28 PM] Homebridge v1.3.4 (TuyaPlatform) is running on port 52242.
> TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1625394029009} path = /v1.0/iot-01/associated-users/actions/authorized-login

Hi @enjoymj , We have found that you failed to log into the TuyaSmart App with this account. Please make sure that your user name and password are correct.

**Comment by Hanh94** [comment]
Hi guys, Please check the [error code](https://github.com/tuya/tuya-homebridge#tuya-openapi-login-error-code) for **code 1106**.

**Comment by geekseanlin** [comment]
I signed in with SmartLife app and I have both AppleID linked as well as email. You think this is the issue? I will try to create another account just with email and try.

**Comment by Hanh94** [comment]
> I signed in with SmartLife app and I have both AppleID linked as well as email. You think this is the issue? I will try to create another account just with email and try.

Yes @geekseanlin , Google or Apple ID email need to link your phone number and use the linked phone number as username to login. Because of this login situation, OpenAPI only verifies the phone number, and our OpenAPI team will optimize it as soon as possible.

**Comment by enjoymj** [comment]
> > Similar issue here
> > Initializing TuyaPlatform...
> > TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":86,"username":"USERNAME","password":"PWD","schema":"tuyaSmart"}, headers = {"t":"1625394028565","client_id":"ACCESSKEY","nonce":"744a7190-dcb1-11eb-8422-d7681144925c","Signature-Headers":"client_id","sign":"FEB5A33D6D227E6011FEC02E9CD3EE79F033F8C048AC02D9C07B2D4B5E2386B6","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}
> > Starting to advertise 'TuyaPlatform 7C96' using bonjour-hap backend!
> > [7/4/2021, 6:20:28 PM] Homebridge v1.3.4 (TuyaPlatform) is running on port 52242.
> > TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1625394029009} path = /v1.0/iot-01/associated-users/actions/authorized-login
> 
> Hi @enjoymj , We note that you failed to log into the TuyaSmart App with this account. Please make sure that your user name and password are correct.

Resolved. It seems that I would only need to wait for Tuya admins to grant perms. (which took three days/one working day in my case.)

**Comment by Hanh94** [comment]
> > > Similar issue here
> > > Initializing TuyaPlatform...
> > > TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":86,"username":"USERNAME","password":"PWD","schema":"tuyaSmart"}, headers = {"t":"1625394028565","client_id":"ACCESSKEY","nonce":"744a7190-dcb1-11eb-8422-d7681144925c","Signature-Headers":"client_id","sign":"FEB5A33D6D227E6011FEC02E9CD3EE79F033F8C048AC02D9C07B2D4B5E2386B6","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}
> > > Starting to advertise 'TuyaPlatform 7C96' using bonjour-hap backend!
> > > [7/4/2021, 6:20:28 PM] Homebridge v1.3.4 (TuyaPlatform) is running on port 52242.
> > > TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1625394029009} path = /v1.0/iot-01/associated-users/actions/authorized-login
> > 
> > 
> > Hi @enjoymj , We note that you failed to log into the TuyaSmart App with this account. Please make sure that your user name and password are correct.
> 
> Resolved. It seems that I would only need to wait for Tuya admins to grant perms. (which took three days/one working day in my case.)

ok

**Comment by Hanh94** [comment]
Hi gays,  In version 1.3.0, the login interface is published in all regions. Therefore, you can use the endPoint of any region to log in. After a successful login, the endPoint of the region where the account resides is returned to obtain device information.
Any questions, please contact us.

**Comment by Hanh94** [comment]
Hi guys, Since we haven't received your reply for a long time, we think our latest version should have solved your problem. We will close this issue first. If there is any problem, you can contact us at any time.
