### ISSUE TITLE
Add support for lights within fans

### ISSUE THREAD

**Issue by zacharylimjx** [tuya/tuya-homebridge#47]
Please add lights support for fans! I can only control fan speed and rotation direction but not the lights. Thank you.

**Comment by Hanh94** [comment]
Hi @zacharylimjx ,Sorry for taking so long to reply.
This category has been planned, Please stay tuned.

**Comment by Hanh94** [comment]
Hi @zacharylimjx ,Regret that we cannot support this requirement, Please refer to this [submission](https://github.com/tuya/tuya-homebridge/pull/51#issuecomment-870438219)

**Comment by qthatswho** [comment]
(pulling over my question/comment from the linked post, which was already merged)

@Hanh94 Can you not add a new device type? In [this other plugin](https://github.com/iRayanKhan/homebridge-tuya), they have defined a "[fanlight](https://github.com/iRayanKhan/homebridge-tuya/blob/main/lib/SimpleFanLightAccessory.js)" device category, to support switches like the [Treatlife DS03](https://www.treatlife.tech/products/smart-ceiling-fan-control-and-light-dimmer-switch-neutral-wire-needed-treatlife-single-pole-wi-fi-light-switch-fan-speed-control-works-with-alexa-google-assistant-schedule-remote-control), which is a Tuya supported device.

**Comment by Hanh94** [comment]
Hi @qthatswho ,Sorry for the late reply.
we had support it in version 1.4.0. Please see https://github.com/tuya/tuya-homebridge/discussions/89
