### ISSUE TITLE
Access config error

### ISSUE THREAD

**Issue by kevinrivers** [tuya/tuya-homebridge#53]
With debug logging enabled the following error appears consistently.

`TuyaOpenAPI response: {"code":28841101,"msg":"No permissions. This API is not subscribed.","success":false,"t":1624754292738} path = /v1.0/iot-03/open-hub/access-config`

Do I need to add an additional API Product?

**Comment by Garth18** [comment]
After a few weeks of things going well I'm constantly getting this error also - have confirmed web/app username/password correct and the API public/private also good.  What gives?

**Comment by Hanh94** [comment]
Hi @kevinrivers @Garth18, Sorry for the late reply.
Recently, our team has been sorting out interface codeNumber issues.
Hope this doc has been helpful: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt

**Comment by kevinrivers** [comment]
Thank you. Adding `device status notifications cleared this up for me.
