### ISSUE TITLE
Device not showing in the Homebridge and Home app

### ISSUE THREAD

**Issue by alierhan** [tuya/tuya-homebridge#54]
I've been using HomeBridge mainly to expose the OpenHAB devices to Home app for a while now.

I now have a Tuya device which cannot be flashed with Tasmota (my preferred method) I have started using this plug-in.

I now have a project in the IoT platform, with "Device status notification" API. Linked my device and it is showing as on-line, as in the attached picture. However, I cannot see anything in the HomeBridge. I can only control this device with Tuya Smart app on my iPhone. Obviously device doesn't show on Home app either.

I am very new at you IoT developer portal and may be I am missing something. 
1) I'd like to delete the projects I have and start over and I was unable to do
2) how can view the logs? to debug what is going on
3) Do I need to setup an MQTT access for this to work? If so, I need help with setting up the parameters

Thank you

![Tuya1](https://user-images.githubusercontent.com/43734541/123572506-b05e2100-d80f-11eb-870d-85a569b086ba.JPG)

**Comment by alierhan** [comment]
I've not got this working correctly.

**Comment by Hanh94** [comment]
Hi @alierhan , Sorry for the late reply.
Please set **'debug'** to true in the **'options'** in the **'config.json'** file. Give us more log information, Thank you.

Recently, our team has been sorting out interface issues such as **code 2406**. The same country code for Tuya SmartLife apps on different phones may correspond to different **Availability zones**.
Therefore, we recommend that you select all available **Availability Zones** in the cloud project, and we will improve the plugin login experience as soon as possible.

**Comment by Hanh94** [comment]
Hope this doc has been helpful: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt

**Comment by alierhan** [comment]
> 
> 
> Hope this doc has been helpful: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt

I have used this as my guide to install. As I progress, I am now more confident how it all works. Thank you
