### ISSUE TITLE
Authentication in 1.2.1

### ISSUE THREAD

**Issue by Garth18** [tuya/tuya-homebridge#55]
When I upgraded to v1.2.1 my accessories/devices disappeared.  I checked my config over and over and all appeared good.  I rebuild by Raspberry PI and re-installed HomeBridge and the Tuya plugin, manually configured, only to have the same error:

[28/06/2021, 22:30:38] Loaded 0 cached accessories from cachedAccessories.0E6940212586.
Preparing Advertiser for 'TuyaPlatform C4A3' using bonjour-hap backend!
Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":61,"username":"XXXXX@gmail.com","password":"XXXXX","schema":"tuyaSmart"}, headers = {"t":"XXXXX","client_id":"XXXXX","nonce":"XXXXX","Signature-Headers":"client_id","sign":"XXXXX","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}
Starting to advertise 'TuyaPlatform C4A3' using bonjour-hap backend!
[28/06/2021, 22:30:38] Homebridge v1.3.4 (TuyaPlatform) is running on port 56345.
TuyaOpenAPI response: {"code":1004,"msg":"sign invalid","success":false,"t":1624883439708} path = /v1.0/iot-01/associated-users/actions/authorized-login
Please confirm that the Access ID and Access Secret of the Smart Home PaaS project you are using were created after May 25, 2021.
Please linked devices by using Tuya Smart or Smart Life app in your cloud project.
Failed to get device information. Please check if the config.json is correct.

So I decided to downgrade to v1.2.0 which was the last know config that worked without issue.  

Using the same config parameters no issue - suggestive there is a bug in v1.2.1 around authentication.

**Comment by Hanh94** [comment]
Hi @Garth18 ,Sorry for the late reply.
Recently, our team has been sorting out interface codeNumber issues. 
Hope this doc has been helpful: https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt

**Comment by Daveblanche** [comment]
I had exactly the same issue so rolled back to 1.2.1.  Thanks for the update on things @Hanh94 !

**Comment by Hanh94** [comment]
Hi @Garth18 @Daveblanche , Thanks for your feedback. We have adopted a new signature method in 1.2.1.
Please provide the latest error log for version 1.2.1, Thanks

**Comment by Hanh94** [comment]
Hi @Daveblanche @Garth18 , Please try again.

**Comment by Daveblanche** [comment]
Done. Seems ok so far. I have lights!
Thanks guys.
