### ISSUE TITLE
Plugin Intention

### ISSUE THREAD

**Issue by rcoletti116** [tuya/tuya-homebridge#6]
Hello! The Homebridge community is a curious one and as a result there's been some talk of your plugin already. I am wondering if you can clarify what the intended goal of your plugin is. Do you aim to have an official supported plugin that regular homebridge users can download and use directly? Or are you designing this for your OEM partners?

**Comment by zlinoliver** [comment]
Hi @rcoletti116, sorry for the late reply! Glad that the homebridge community is interested in the new official tuya homebridge plugin!  This plugin is definitely not designed for Tuya's OEM partners, we're going to provide official support for the community. While we wish the homebridge users can use this plugin as Tuya developers, and the intended goal of this new plugin is mainly for Tuya developers to try our Tuya IoT Cloud and App SDK products to build SaaS solutions, like Smart Home SaaS. For more info, please check the [API Products Doc](https://developer.tuya.com/en/docs/cloud)。

The new plugin is built on top of the Tuya's [Open API](https://developer.tuya.com/en/docs/cloud) capabilities. And it requires connecting to Tuya Cloud for device control. We will support two types of Cloud projects in Tuya IoT Platform: **Smart Home** and **Industry Solution**.

1. Using the **Smart Home** type, developers can use Tuya Smart/Smart Life app to pair your PBT devices directly to homebridge. It's more friendly to the existing Tuya homebridge users. We will support this project type in **late May,2021.** This type is mainly for the smart home customers/end users/individual developers/geek.

2. Using the **Industry Solution** type, developers need to use our new [Device Manager app](https://github.com/tuya/tuya-android-iot-app-sdk-sample/releases/tag/v1.0) (Only provide Android version for now, iOS version will be released soon) to do device network pairing to homebridge. For existing devices linked in the Tuya Smart/Smart Life app, you need to relink them using this new app for now as it's in different account system. This type is mainly for Individual Service Vendor(ISV), software companies/startups who want to build SaaS solutions for smart hotel, apartment, retail, etc. And it's now available in this github repo!

As this new plugin is developed using Tuya's Open API, all the exiting device drivers for homebridge in the market are not adaptable. We need to rebuild all the drivers using Tuya's [Standard Instruction Set](https://developer.tuya.com/en/docs/iot/standarddescription?id=K9i5ql6waswzq), which can support much wider product types compared to the existing ones in the market.

If the homebridge community is interested to help build these new drivers as Tuya developers for the new plugin together, support much more PBT products, please let us know. Any help is appreciated!  Here is the tutorial for building the new Tuya homebridge drivers: <https://developer.tuya.com/en/demo/tuyahomebrigeplugin>

Tuya developer email: developer@tuya.com
