### ISSUE TITLE
Led Strip

### ISSUE THREAD

**Issue by Mathmxp** [tuya/tuya-homebridge#60]
I have installed the plugin successfully. I have two devices installed in smart life app, both devices show up in the cloud project.
When I run the plugin in Homebridge with debug I see the following: 

_Adding: TV Led (dd / bf7cfcb4d61b9a80fexknv)
Adding: Entrance Lamp (dj / bf8364dae520a89e98mhmz)
Existing Accessory found Entrance Lamp  bf8364dae520a89e98mhmz bf87eccb-295c-4cc5-9f1a-ccdd93573c02_

In homebridge accessory list and HomeKit only one device shows up. (Entrance Lamp) wifi lightbulb, the led strip (TV Led) doesn't show up at all.

Thanks

**Comment by Hanh94** [comment]
Hi @Mathmxp , Thank you for your feedback.
Category **"dd"** is not in the Tuya standard instruction set. So Plugin don't have support yet.
Please open the log and provide device details. And try submitting a PR.

**Comment by Mathmxp** [comment]
{"category":"dd","devices":["bf7cfcb4d61b9a80fexknv"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value","desc":"bright value","name":"bright value","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value","desc":"temp value","name":"temp value","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"colour_data","desc":"colour data","name":"colour data","type":"Json","values":"{}"},{"code":"scene_data","desc":"scene data","name":"scene data","type":"Json","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"music_data","desc":"music data","name":"music data","type":"Json","values":"{}"},{"code":"control_data","desc":"control data","name":"control data","type":"Json","values":"{}"}],"product_id":"imhcpay5gohtqjys"}

**Comment by Mathmxp** [comment]
This is the log of the device, I have no idea how to create a PR sorry!

**Comment by Hanh94** [comment]
Hi @Mathmxp , Category **"dd"** will be supported in the next version.

**Comment by Hanh94** [comment]
Hi @Mathmxp , We already support Category "dd "in version 1.3.0, please update and try again.

**Comment by Hanh94** [comment]
Hi @Mathmxp , Since we haven't received your reply for a long time, we think our latest version should have solved your problem. We will close this issue first. If there is any problem, you can contact us at any time.
