### ISSUE TITLE
Support for 'Socket' type accessories?

### ISSUE THREAD

**Issue by x5nder** [tuya/tuya-homebridge#61]
I'm curious if it's possible to use this plugin with 'Socket' type accessories, which are somewhat similar to outlets or switches. I'm currently running a QIACHIP Smart Switch, but tuya-homebridge gives me
`Failed to get device information. Please check if the config.json is correct.`
I assume that's because this device type is not yet supported?

**Comment by Hanh94** [comment]
Hi @x5nder ,The [categories](https://github.com/tuya/tuya-homebridge/wiki/Supported-Tuya-Device-Types) we currently support.
Please try submitting a PR And Thank you.
