### ISSUE TITLE
add support for dimmer switch

### ISSUE THREAD

**Issue by adorabletechguy** [tuya/tuya-homebridge#63]
Smart Dimmer Switch, TESSAN WiFi Light Switch
---
name: New Device Support
about: New device that wants to be supported
title: ''Smart Dimmer Switch, TESSAN WiFi Light Switch"
labels: enhancement, help wanted
assignees: ''

---
{"active_time":1614289067,"biz_type":0,"category":"tgkg","create_time":1614288716,"icon":"smart/icon/ay1536047723331OpdLN/de9484c22e590e3a0d55a150aea76082.png","id":"eb7093013e4c564ce5az9w","ip":"99.62.188.197","lat":"26.13265833402834","local_key":"7a2612dd0e28ac8b","lon":"-80.40450293441359","name":"Kitchen light","online":true,"owner_id":"33646384","product_id":"zcn1sye3spbycifv","product_name":"智能双控调光器 (Wi-Fi) plus","status":[{"code":"switch_led_1","value":false},{"code":"bright_value_1","value":710},{"code":"brightness_min_1","value":10},{"code":"led_type_1","value":"led"},{"code":"work_mode","value":"light_white"},{"code":"light_mode","value":"pos"}],"sub":false,"time_zone":"-05:00","uid":"az1611536221746t4iLR","update_time":1626788331,"uuid":"5161ae6ec6c0c99c"}],

**Comment by Hanh94** [comment]
Hi @adorabletechguy ,Sorry for taking so long to reply.
Please submit an Issue in the Issue Template format so that we can better help you solve the issue.

**Comment by adorabletechguy** [comment]
---
name: New Device Support
about: New device that wants to be supported
title: ''
labels: enhancement, help wanted
assignees: ''

---

{"active_time":1614289067,"biz_type":0,"category":"tgkg","create_time":1614288716,"icon":"smart/icon/ay1536047723331OpdLN/de9484c22e590e3a0d55a150aea76082.png","id":"eb7093013e4c564ce5az9w","ip":"99.62.188.197","lat":"26.13265833402834","local_key":"7a2612dd0e28ac8b","lon":"-80.40450293441359","name":"Kitchen light","online":true,"owner_id":"33646384","product_id":"zcn1sye3spbycifv","product_name":"智能双控调光器 (Wi-Fi) plus","status":[{"code":"switch_led_1","value":false},{"code":"bright_value_1","value":710},{"code":"brightness_min_1","value":10},{"code":"led_type_1","value":"led"},{"code":"work_mode","value":"light_white"},{"code":"light_mode","value":"pos"}],"sub":false,"time_zone":"-05:00","uid":"az1611536221746t4iLR","update_time":1626788331,"uuid":"5161ae6ec6c0c99c"}],

**Comment by adorabletechguy** [comment]
Any plans to add support?

**Comment by Hanh94** [comment]
Hi @adorabletechguy , Details of the device have been received and we will support category "tgkg" in the next version.

**Comment by paqpaqpaq** [comment]
Awesome!!!
This finally fixes the issue with MOES dimmers too!

Seems to be working flawlessly.
