### ISSUE TITLE
I get error 1106, from the "new signature algorithm" for projects created after June30, 2021

### ISSUE THREAD

**Issue by alvarolg1981** [tuya/tuya-homebridge#64]
Hello, I was configuring the Plug-In and during the project creation steps on IOT.Tuya.com I received the information that the signature algorithm had security modifications and now I can't connect to the account.
![Captura de Tela 2021-07-11 às 01 24 15](https://user-images.githubusercontent.com/73044391/125182740-f8ede500-e1e6-11eb-942a-de5098b08f84.png)

**Comment by Hanh94** [comment]
Hi @alvarolg1981 , We have upgraded the signature algorithm in version 1.2.1.
Please provide the log according to the **Error Code** in the **Issue template**.

**Comment by alvarolg1981** [comment]
would this be?

[13/07/2021, 22:55:07] 
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1626227707795} path = /v1.0/iot-01/associated-users/actions/authorized-login
Please confirm that the Access ID and Access Secret of the Smart Home PaaS project you are using were created after May 25, 2021.
Please linked devices by using Tuya Smart or Smart Life app in your cloud project.
Failed to get device information. Please check if the config.json is correct.


The ID and Access Secret are correct...

**Comment by Hanh94** [comment]
Hi @alvarolg1981 ,Sorry for the bad experience.
Have explained it in the [Error code](https://github.com/tuya/tuya-homebridge#tuya-openapi-login-error-code), and will fix the email login issue of the Google account soon.

**Comment by alvarolg1981** [comment]
tanks!

**Comment by alvarolg1981** [comment]
> Hi @alvarolg1981 ,Sorry for the bad experience.
> Have explained it in the [Error code](https://github.com/tuya/tuya-homebridge#tuya-openapi-login-error-code), and will fix the email login issue of the Google account soon.

it working now!!!! tanks!!!!
