### ISSUE TITLE
Switches in Home app do not indicate offline status

### ISSUE THREAD

**Issue by jeremyhiggs** [tuya/tuya-homebridge#65]
If there is a connectivity issue with Homebridge, the tuya-Homebridge plugin does not handle it well.

For example:
1. In the Home app, tap the switch to turn it on/off
2. The switch status updates, but the physical one does not

What should happen is that the tile in the home app should reflect that the switch is offline (which results in a “!” Icon appearing).

**Comment by Hanh94** [comment]
Hi @jeremyhiggs ,Thank you for your feedback.
This is a known issue and we will fix it as soon as possible to improve the plugin experience.

**Comment by codydalerodgers** [comment]
@Hanh94 Moreso, is there a way for the plugin to try and "reset" if the accessories become unresponsive?

I, almost daily, have to restart my raspberry pi (4) / home bridge ONLY because my Tuya accessory tiles in Home.app become unresponsive. I will touch a light and the tile will "turn on" but nothing happens to the actual, physical light switch. After restarting Homebridge, they work fine. But I have to do this several times a week, which makes it completely frustrating.

**Comment by nchbuser** [comment]
I'm still experiencing the issue reported by @jeremyhiggs. I'll add that the Homebridge logs shows devices are offline when this is happening.

TuyaOpenAPI response: {"code":2001,"msg":"device is offline","success":false,...

**Comment by nchbuser** [comment]
This issue is NOT resolved. When you tap a switch on light in Homekit, and the device is offline, Homekit continues to update according to the command you just gave it, giving no indication that the device is offline. It should, as @jeremyhiggs described, show the "!" to indicate it is offline.

**Comment by sasimpson** [comment]
I am having the same issue, homekit will let me toggle the plug, but the tuya api in homebridge says 2001:device is offline.  the cloud api indicates the same, but i can toggle with the tuya smart app just fine.

**Comment by nchbuser** [comment]
This issue is still not fixed.

**Comment by nchbuser** [comment]
This still does not appear to be fixed.

**Comment by nchbuser** [comment]
So I guess the strategy is to do nothing, then after a period of time close it, and hope nobody notices?

**Comment by michalw2-alt** [comment]
This issue is still not resolved
