### ISSUE TITLE
Add support for ‘kt’ devices (air conditioner)

### ISSUE THREAD

**Issue by ASKendrew** [tuya/tuya-homebridge#68]
Hey! Would it be possible please to add support for kt devices? Here’s the log information:

Device Info

[{"active_time":1626738267,"biz_type":0,"category":"kt","create_time":1626715978,"icon":"smart/product_icon2/kt_1.png","id":"XXXX","ip":"XXXX","lat":"XXXX","local_key":"XXXX","lon":"-XXXX","name":"Office AC","online":true,"owner_id":"34270606","product_id":"hw50w7qvxluhslkk","product_name":"TCL外销分体机","status":[{"code":"switch","value":false},{"code":"temp_set","value":220},{"code":"temp_current","value":23},{"code":"mode","value":"cold"},{"code":"humidity_current","value":0},{"code":"temp_set_f","value":61}],"sub":false,"time_zone":"+00:00","uid":"XXXX","update_time":1626738300,"uuid":"XXXX"}]

Device Functions

{"category":"kt","devices":["XXXX"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"temp_set","desc":"temp set","name":"temp set","type":"Integer","values":"{\"unit\":\"℃\",\"min\":160,\"max\":880,\"scale\":1,\"step\":5}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"},{"code":"temp_set_f","desc":"temp set f","name":"temp set f","type":"Integer","values":"{\"unit\":\"℉\",\"min\":61,\"max\":88,\"scale\":0,\"step\":1}"}],"product_id":"hw50w7qvxluhslkk"}

**Comment by diazabdulm** [comment]
Any updates on the timeline for this category of devices? I'm also looking for a solution.
