### ISSUE TITLE
endPoint doesn't respect the plugin setting but keeps pointing to TuyaCN

### ISSUE THREAD

**Issue by Aekung** [tuya/tuya-homebridge#71]
**Describe the bug**
The plugin won't change the endPoint to "https://openapi.tuyaus.com" but keeps on pointing to tuyacn so it causes error authentication in the latest version of the plugin even with config file setting and endPoint parameter to tuyaus.

**Expected behavior**
The endPoint should be pointing to TuyaUS so the authentication is not failed.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Hanh94** [comment]
Hi @Aekung , In version 1.3.0, the login interface is published in all regions. Therefore, you can use the endPoint of any region to log in. After a successful login, the endPoint of the region where the account resides is returned to obtain device information.
If you failed to log in, please provide more log information.

**Comment by Aekung** [comment]
I can't login. It returns this error.

```
[27/07/2021, 09:26:17] Homebridge v1.3.4 (TuyaPlatform) is running on port 33812.
TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1627352779287} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:88:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.
```

I subscribed to these service and already authorized the app for the permission

Smart Home Devices Management 
Authorization 
Smart Home Family Management 
Smart Home Scene Linkage 
Smart Home Data Service
Device status notification

Do you know what's the problem is?

**Comment by Aekung** [comment]
I reread the document and found that it's the error stating my project created before May 25, 2021, which is true since I have created this for tuya wizard cli. However, I tried to create new project few times yesterday but it return 'Captcha Error' in both Safari and Chrome and I couldn't get the new project set up. Is it possible that there's a problem on your site that prevents the new project to be created successfully?

This is the return error message

`会员过期`

Thank you.

**Comment by Aekung** [comment]
Oh, I could finally create the project now. I found that I have to upgrade my membership from trial period to 'Basic (TRIAL EDITION)' in order to be able to create the project. I will see if the setup goes well and will update.

Thank you.

**Comment by Aekung** [comment]
Installation and configuration is done and I can see the supported devices in Homekit. However, the curtains (cl category) are not controllable at all. The status is incorrect and it won't control the curtain for a simple on and off command.

Not sure if I have to create another ticket for the problem but let me know if I have to.

**Comment by Hanh94** [comment]
Hi @Aekung ,Please provide details log of the curtain device.

**Comment by olibuijr** [comment]
Hi, i seem to get this error when i use: 
"projectType": "2",

When i use:
"projectType": "1".

It respects the endPoint and I get a login failed: 

TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-03/users/login, params = null, body = {"username":"olibuijr@olibuijr.com","password":"29a0bbbf7d480ef942dedce1dcd44ad1e5f413ed587090b3a1e6a2b941064742"}, headers = {"t":"1628097191858","client_id":"y5ewe4g7a6igkf520ufy","nonce":"3f378b60-f547-11eb-8b83-2d70034f5a04","Signature-Headers":"client_id","sign":"D89ED68DB1727937BFEF35DCDBFB1341BBC196B1FA14FB65812344856F5A282B","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.1"}

TuyaOpenAPI response: {"code":2401,"msg":"username or password wrong","success":false,"t":1628097192306} path = /v1.0/iot-03/users/login
(node:40211) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaOpenAPI.login (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyaopenapi.js:57:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaPlatform.initTuyaSDK (/usr/lib/node_modules/homebridge-tuya-platform/index.js:66:7)

**Comment by olibuijr** [comment]
Here is my config

            "options": {
                "username": "XXXXX",
                "password": "XXXXX",
                "accessId": "XXXXX",
                "accessKey": "XXXXX",
                "lang": "en",
                "projectType": "2",
                "endPoint": "https://openapi.tuyaeu.com",
                "appSchema": "tuyaSmart",
                "countryCode": "354",
                "debug": true
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform"

**Comment by Hanh94** [comment]
Hi @olibuijr ,Please use **"projectType": "2"** to log in, And update to the latest version.
If the plugin has any errors, please provide the relevant log information.

**Comment by olibuijr** [comment]
> Hi @olibuijr ,Please use **"projectType": "2"** to log in, And update to the latest version.
> If the plugin has any errors, please provide the relevant log information.

Like OP said. When using projectType 2 the config is locked on tuyacn. but not if i use 1

**Comment by Hanh94** [comment]
> > Hi @olibuijr ,Please use **"projectType": "2"** to log in, And update to the latest version.
> > If the plugin has any errors, please provide the relevant log information.
> 
> Like OP said. When using projectType 2 the config is locked on tuyacn. but not if i use 1

Please read [preparation](https://github.com/tuya/tuya-homebridge#preparation) , If there are any problems, please provide the log.

**Comment by Aekung** [comment]
> Hi @Aekung ,Please provide details log of the curtain device.

Hello Hanh,

Sorry for the late reply. I switched back to the tuya plugin that works for me so I didn't have time to retest it up until now.

To answer your question, I have 4 Tuya Motorized Curtains in my house. All of them are in CL category. However, 2 curtains seem to work, or at least controllable but another 2 are not.

Checking on Tuya Device Debugging Screen, the curtains that I can control are having the same standard instruction set, which is

```
Code | Type | Values
-- | -- | --
control | Enum | {   "range": [     "open",     "stop",     "close"   ] }
```
Other 2 that are not working at all are having this standard instruction set,

```
Code | Type | Values
-- | -- | --
mach_operate | Enum | {   "range": [     "ZZ",     "FZ",     "STOP"   ] }
```

As you can see, the type in the standard instruction set of these 2 is different. The one that works is 'Control', while the one that doesn't work is 'Mach_operate' and the range of both standard instruction sets are different as well.

Regarding the log in Homebridge (even with debuggin enabled on both homebridge and plugin), there's nothing displayed when trying to control the 2 curtains that is using the second standard instruction set. However, when trying to control the 2 curtains that is using the first standard instruction set, the API returns and shows in Homebridge log just fine.

Hope this helps.

**Comment by Hanh94** [comment]
Hi @Aekung , According to your description, we have a general understanding, because the standard instruction set used by different devices may be different. I hope you can provide the latest log, we can query the specific information of your device according to the log, and then adapt it to the plug-in. As for how to provide the log, please refer to the issue template

**Comment by Aekung** [comment]
> Hi @Aekung , According to your description, we have a general understanding, because the standard instruction set used by different devices may be different. I hope you can provide the latest log, we can query the specific information of your device according to the log, and then adapt it to the plug-in. As for how to provide the log, please refer to the issue template

Hi @Hanh94 

Thanks for the reply.

I think this is what you are looking for.

{"category":"cl","devices":["10670875bcddc2b0e398","52003233ecfabca9fdce"],"functions":[{"code":"mach_operate","desc":"mach operate","name":"mach operate","type":"Enum","values":"{\"range\":[\"ZZ\",\"FZ\",\"STOP\"]}"},{"code":"opposite","desc":"opposite","name":"opposite","type":"Boolean","values":"{}"},{"code":"position","desc":"position","name":"position","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"}],"product_id":"XS76BY5Q1uKO6gjC"}

Thanks for pointing me out to how to collect the log. Hope it's the thing you are looking for.

Let me know if I can still be any help.

Thank you.

**Comment by Aekung** [comment]
Or perhaps it's this one that you are looking for

{"active_time":1593148709,"biz_type":18,"category":"cl","create_time":1593148709,"icon":"smart/product_icon/cl.png","id":"10670875bcddc2b0e398","ip":"124.120.XX.XXX","lat":"13.99627978XXXXXX","local_key":"f1d0e7e02aXXXXXX","lon":"100.5574729XXXXXX","model":"BCM700D WiFi","name":"Window Covers Main","online":true,"owner_id":"657XXXX","product_id":"XS76BY5Q1uKO6gjC","product_name":"窗帘电动轨道","status":[{"code":"position","value":0},{"code":"mach_operate","value":"STOP"},{"code":"opposite","value":true}],"sub":false,"time_zone":"+07:00","uid":"az1556662956734lhmLi","update_time":1628186274,"uuid":"10670875bcddc2b0e398"}

Please let me know if it's the right log.

**Comment by Hanh94** [comment]
Hi @Aekung ,Thank you for your feedback.
We will support **"position"** dp code control in the next release.

**Comment by Aekung** [comment]
> Hi @Aekung ,Thank you for your feedback.
> We will support **"position"** dp code control in the next release to support older devices.

Thanks @Hanh94

Looking forward to that.

**Comment by Aekung** [comment]
> Hi @Aekung ,Thank you for your feedback.
> We will support **"position"** dp code control in the next release to support older devices.

Updated to the latest version but these 2 curtains are still not working. I'm not sure if it's fixed in the latest version that just released hours ago or it will be coming in the next version?

By the way, the motor rotating of the 2 working curtains are now reported correctly in the latest update though. Thanks for that.

**Comment by Hanh94** [comment]
Hi @Aekung ,We already support the "position" control in version 1.4.0.
Regarding the dp "position" control, if you control through the Home App, whether the real device behaves properly or just the Home App status update is incorrect?

**Comment by cgarrovillo** [comment]
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/6688713/132039973-42304504-c549-4c73-a5b6-4b0fc46466e5.png">

Same issue on the same configs as everyone else in this thread and account made June 2021.

**Comment by 0ldF0x** [comment]
v1.4.1 fixed this
