### ISSUE TITLE
Error Initializing Homebridge plugin due to Ceiling Fan Switch

### ISSUE THREAD

**Issue by codydalerodgers** [tuya/tuya-homebridge#72]
**Describe the bug**
When starting Homebridge, I get the following error which prevents any of my Tuya accessories from loading/showing up in HomeKit:

Adding: Ceiling Fan Switch (fskg / eb2519fa123816e90clnjp)
Creating New Accessory eb2519fa123816e90clnjp
Register Platform Accessory Ceiling Fan Switch
(node:24795) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Fanv2Accessory.getSpeedFunctionLevel (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/fanv2_accessory.js:226:57)
    at new Fanv2Accessory (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/fanv2_accessory.js:28:29)
    at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:148:27)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:97:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Expected behavior**
Tuya accessories show up correctly

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1620963612,"biz_type":0,"category":"fskg","create_time":1617076902,"icon":"smart/icon/ay14906729310721fNjn/a92553379c09ef865681d1c62eb04190.jpg","id":"eb2519fa123816e90clnjp","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"b31e7de97fdbb1e9","lon":"-94.44372367466038","model":"DS02F(WiFi+Ble)","name":"Ceiling Fan Switch","online":true,"owner_id":"37584837","product_id":"tqas5nfwomvgvvhf","product_name":"Smart Ceiling Fan Switch-DS02F","status":[{"code":"switch_fan","value":false},{"code":"countdown_fan","value":0},{"code":"fan_speed_enum","value":"level_3"},{"code":"fan_speed","value":0}],"sub":false,"time_zone":"-05:00","uid":"az16163776461937QCzi","update_time":1627341634,"uuid":"08911298e06c509a"},{"active_time":1617069503,"biz_type":0,"category":"kg","create_time":1617069503,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"180010218cce4ec11de4","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"2b774df566d370f2","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Front Porch Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341634,"uuid":"180010218cce4ec11de4"},{"active_time":1625531391,"biz_type":0,"category":"kg","create_time":1625531391,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dd16c5","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"c09b722c4865b472","lon":"-94.44372367466038","name":"Garage Lights","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341634,"uuid":"607470768caab5dd16c5"},{"active_time":1625531550,"biz_type":0,"category":"kg","create_time":1625531550,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"60747076e09806055861","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"d3abc39d1a18b046","lon":"-94.44372367466038","name":"Exterior Lights","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341634,"uuid":"60747076e09806055861"},{"active_time":1617066243,"biz_type":0,"category":"kg","create_time":1617066243,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"180010218cce4ec05516","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"eb5397505be3e606","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Kitchen Pendant Lights","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341633,"uuid":"180010218cce4ec05516"},{"active_time":1616952580,"biz_type":0,"category":"kg","create_time":1616952580,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"60747076e0980604baaf","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"170bbc8edf125792","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Master Bedroom Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341633,"uuid":"60747076e0980604baaf"},{"active_time":1617066163,"biz_type":0,"category":"kg","create_time":1617066163,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dda198","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"e2f97fd9a096cc7d","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Kitchen Ceiling Lights","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341633,"uuid":"607470768caab5dda198"},{"active_time":1617066116,"biz_type":0,"category":"kg","create_time":1617066116,"icon":"smart/icon/ay14906729310721fNjn/aad73a9cc554ca2c684339431d2a411b.jpg","id":"318214378caab5e5b071","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"af23cdc41f8ad41c","lon":"-94.44372367466038","model":"SS02(量产)","name":"Living Room Lights","online":true,"owner_id":"37584837","product_id":"pqhecszou3n95wpa","product_name":"SS02 3-Way Smart Wi-Fi Light Switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341632,"uuid":"318214378caab5e5b071"},{"active_time":1617066314,"biz_type":0,"category":"kg","create_time":1617066314,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dd0f51","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"d994916295f13ead","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Deck Fan Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341632,"uuid":"607470768caab5dd0f51"},{"active_time":1616606886,"biz_type":0,"category":"kg","create_time":1616606886,"icon":"smart/icon/ay14906729310721fNjn/aad73a9cc554ca2c684339431d2a411b.jpg","id":"318214378caab5e48225","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"fd35131697fc7ee7","lon":"-94.44372367466038","model":"SS02(量产)","name":"Foyer","online":true,"owner_id":"37584837","product_id":"pqhecszou3n95wpa","product_name":"SS02 3-Way Smart Wi-Fi Light Switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341631,"uuid":"318214378caab5e48225"},{"active_time":1618885677,"biz_type":0,"category":"kg","create_time":1618885677,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"180010218cce4ec407de","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"7f426e3e18ec6b9a","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Loft","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341631,"uuid":"180010218cce4ec407de"},{"active_time":1617066472,"biz_type":0,"category":"kg","create_time":1617066390,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dd4ba7","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"f57d77d1d3a20abc","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Deck Fan","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341631,"uuid":"607470768caab5dd4ba7"},{"active_time":1616607304,"biz_type":0,"category":"kg","create_time":1616607304,"icon":"smart/icon/ay14906729310721fNjn/aad73a9cc554ca2c684339431d2a411b.jpg","id":"318214378caab5de438f","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"26dd76ca050e224e","lon":"-94.44372367466038","model":"SS02(量产)","name":"Upstairs Hall","online":true,"owner_id":"37584837","product_id":"pqhecszou3n95wpa","product_name":"SS02 3-Way Smart Wi-Fi Light Switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341631,"uuid":"318214378caab5de438f"},{"active_time":1616979476,"biz_type":0,"category":"kg","create_time":1616979476,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"60747076e0980604c325","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"13d269c61eb00443","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Office Ceiling Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341630,"uuid":"60747076e0980604c325"},{"active_time":1625531310,"biz_type":0,"category":"kg","create_time":1625531310,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"8648408624a1602688c0","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"54bd18413fe7d314","lon":"-94.44372367466038","name":"Dining Room Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341630,"uuid":"8648408624a1602688c0"},{"active_time":1617066378,"biz_type":0,"category":"kg","create_time":1617066378,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"180010218cce4ec2c71d","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"0710209c0b2cfb80","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Breakfast Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341630,"uuid":"180010218cce4ec2c71d"},{"active_time":1616607215,"biz_type":0,"category":"kg","create_time":1616607215,"icon":"smart/icon/ay14906729310721fNjn/aad73a9cc554ca2c684339431d2a411b.jpg","id":"31821437e098060533b2","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"6f328c358ad09633","lon":"-94.44372367466038","model":"SS02(量产)","name":"Upstairs Light","online":true,"owner_id":"37584837","product_id":"pqhecszou3n95wpa","product_name":"SS02 3-Way Smart Wi-Fi Light Switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341630,"uuid":"31821437e098060533b2"},{"active_time":1616952576,"biz_type":0,"category":"kg","create_time":1616952576,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5de09c5","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"9156a723e5e69284","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Spare Room Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341630,"uuid":"607470768caab5de09c5"},{"active_time":1616979368,"biz_type":0,"category":"kg","create_time":1616979368,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dda10d","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"f2f51a5ba5e5e933","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Creative Room Light","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341630,"uuid":"607470768caab5dda10d"},{"active_time":1617066589,"biz_type":0,"category":"kg","create_time":1617066391,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dd16ca","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"bf44d50611d5b4ba","lon":"-94.44372367466038","model":"SS02S(不分负载)乐鑫","name":"Deck Lights","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341629,"uuid":"607470768caab5dd16ca"},{"active_time":1616606886,"biz_type":0,"category":"kg","create_time":1616606886,"icon":"smart/icon/ay14906729310721fNjn/aad73a9cc554ca2c684339431d2a411b.jpg","id":"31821437e0980604b88c","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"a3acdb1a1cd9e2ce","lon":"-94.44372367466038","model":"SS02(量产)","name":"Foyer 2","online":true,"owner_id":"37584837","product_id":"pqhecszou3n95wpa","product_name":"SS02 3-Way Smart Wi-Fi Light Switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341629,"uuid":"31821437e0980604b88c"},{"active_time":1625531484,"biz_type":0,"category":"kg","create_time":1625531484,"icon":"smart/icon/ay14906729310721fNjn/1568861668b73fbe9c073.jpg","id":"607470768caab5dda0f5","ip":"107.202.82.177","lat":"38.90713572353337","local_key":"d7463f4d9bc847ec","lon":"-94.44372367466038","name":"Guest Bedroom","online":true,"owner_id":"37584837","product_id":"girtolmb5bb5va39","product_name":"SS02S smart light switch","status":[{"code":"switch_1","value":false},{"code":"countdown_1","value":0}],"sub":false,"time_zone":"-06:00","uid":"az16163776461937QCzi","update_time":1627341629,"uuid":"607470768caab5dda0f5"}],"has_more":false,"last_row_key":"D53448B1D0FBE800497BB42FE6274C8E","total":22},"success":true,"t":1627342199700} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/functions, params = {"device_ids":"eb2519fa123816e90clnjp,180010218cce4ec11de4,607470768caab5dd16c5,60747076e09806055861,180010218cce4ec05516,60747076e0980604baaf,607470768caab5dda198,318214378caab5e5b071,607470768caab5dd0f51,318214378caab5e48225,180010218cce4ec407de,607470768caab5dd4ba7,318214378caab5de438f,60747076e0980604c325,8648408624a1602688c0,180010218cce4ec2c71d,31821437e098060533b2,607470768caab5de09c5,607470768caab5dda10d,607470768caab5dd16ca"}, body = null, headers = {"t":"1627342199737","client_id":"vt5jew5easbulmbke1q3","nonce":"60c82bc0-ee69-11eb-a15b-83a22d498f2a","Signature-Headers":"client_id","sign":"D72F136F97BEAE43C87FB20380DDE27248D2F62593AA8AC1519710B1ED2353F6","sign_method":"HMAC-SHA256","access_token":"719a36970df36b0bcd925cfc642be422","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.0"}
TuyaOpenAPI response: {"result":[{"category":"kg","devices":["318214378caab5e5b071","318214378caab5e48225","318214378caab5de438f","31821437e098060533b2"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"秒\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"pqhecszou3n95wpa"},{"category":"fskg","devices":["eb2519fa123816e90clnjp"],"functions":[{"code":"switch_fan","desc":"switch fan","name":"switch fan","type":"Boolean","values":"{}"},{"code":"countdown_fan","desc":"countdown fan","name":"countdown fan","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"fan_speed_enum","desc":"fan speed enum","name":"fan speed enum","type":"Enum","values":"{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\"]}"},{"code":"fan_speed","desc":"fan speed","name":"fan speed","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"}],"product_id":"tqas5nfwomvgvvhf"},{"category":"kg","devices":["180010218cce4ec11de4","607470768caab5dd16c5","60747076e09806055861","180010218cce4ec05516","60747076e0980604baaf","607470768caab5dda198","607470768caab5dd0f51","180010218cce4ec407de","607470768caab5dd4ba7","60747076e0980604c325","8648408624a1602688c0","180010218cce4ec2c71d","607470768caab5de09c5","607470768caab5dda10d","607470768caab5dd16ca"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"girtolmb5bb5va39"}],"success":true,"t":1627342200090} path = /v1.0/devices/functions
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/functions, params = {"device_ids":"31821437e0980604b88c,607470768caab5dda0f5"}, body = null, headers = {"t":"1627342200126","client_id":"vt5jew5easbulmbke1q3","nonce":"60c82bc0-ee69-11eb-a15b-83a22d498f2a","Signature-Headers":"client_id","sign":"E5F9F0474E4CACF0E901DA513026F6B59F3E85202EC4B663D3C8251172EE05D0","sign_method":"HMAC-SHA256","access_token":"719a36970df36b0bcd925cfc642be422","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.0"}
TuyaOpenAPI response: {"result":[{"category":"kg","devices":["31821437e0980604b88c"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"秒\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"pqhecszou3n95wpa"},{"category":"kg","devices":["607470768caab5dda0f5"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"girtolmb5bb5va39"}],"success":true,"t":1627342200402} path = /v1.0/devices/functions
Adding: Ceiling Fan Switch (fskg / eb2519fa123816e90clnjp)
Creating New Accessory eb2519fa123816e90clnjp
Register Platform Accessory Ceiling Fan Switch
(node:24795) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Fanv2Accessory.getSpeedFunctionLevel (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/fanv2_accessory.js:226:57)
    at new Fanv2Accessory (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/fanv2_accessory.js:28:29)
    at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:148:27)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:97:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Device functions (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
Device Information

Product Name
Smart Ceiling Fan Switch-DS02F
Device ID
eb2519fa123816e90clnjp
Product Category
fskg
Device Status
Online
Activated At
2021-05-13 22:40:12

**Comment by Hanh94** [comment]
Hi @codydalerodgers ,Sorry for the late reply.
We should have fixed this in version 1.3.1, please update and try again.
