### ISSUE TITLE
Silvercrest smart ceramic fan heater

### ISSUE THREAD

**Issue by jackwburger** [tuya/tuya-homebridge#74]
Hi,

I have a Silvercrest smart ceramic fan heater which has heating HIGH, LOW and COOL. Also has swing horizontal and vertical. There is NO Temperature setting or reading.

Can this be supported?
https://www.independent.co.uk/extras/indybest/house-garden/household-appliances/lidl-silvercrest-fan-heater-b1804724.html

From the logs:
Query:

TuyaOpenAPI response: {"result":{"devices":...
"lon":"5.992497679047818","model":"346979","name":"Smart Ceramic Heater","online":true,"owner_id":"28102895","product_id":"30433rqaco1yfzli","product_name":"Smart Ceramic fan heater","status":[{"code":"switch","value":false},{"code":"shake","value":false},{"code":"countdown_set","value":"cancel"},{"code":"countdown_left","value":0}],"sub":false,"time_zone":"+02:00"...

Turn on:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"afaab6c7-5b74-45d8-a2d3-7fa2e2b1593f","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"11":"on"}]},"protocol":4,"pv":"2.0","sign":"eafc02c2c9c7cf288b29eba19f95639f","t":1627476338}

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"782a293e-8159-4215-987a-e61aa57d3b1d","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"1":true,"code":"switch","t":"1627476338","value":true}]},"protocol":4,"pv":"2.0","sign":"e50410ad3291718534ee8c65c5101dbd","t":1627476338}

HEATING TYPE :

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"103d4a8a-5d84-4e3e-979f-d3ec585eccc1","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"5":"low"}]},"protocol":4,"pv":"2.0","sign":"f4f95456c29f06e29af33d2295ec3916","t":1627476345}

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"e130b502-dff2-40d0-ade4-6252365a909e","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"5":"wind"}]},"protocol":4,"pv":"2.0","sign":"7558c34c8fc946233fc7ecb236b56785","t":1627476351}

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"f3ed95df-7cb9-4b55-b11b-29962d10db41","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"5":"high"}]},"protocol":4,"pv":"2.0","sign":"ac07e0c7eea6969c6a7eb4c10d4c38dd","t":1627476355}

SHAKE UP-DOWN:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"623a17f7-4467-4859-932b-fa35d807c507","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"8":true,"code":"shake","t":"1627476360","value":true}]},"protocol":4,"pv":"2.0","sign":"80820263f4330423841a772c2477a226","t":1627476360}

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"8c4f2f9e-161f-4d4f-a603-4d8bc571f570","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"8":false,"code":"shake","t":"1627476375","value":false}]},"protocol":4,"pv":"2.0","sign":"e460423784a9aaf17f82919cb90c4862","t":1627476375}

SHAKE LEFT-RIGHT:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"f2f0f0f2-56a6-445c-984b-650de14d4d14","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"101":true}]},"protocol":4,"pv":"2.0","sign":"4259ae0918b8146809bbaeac77bed676","t":1627476369}

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"e226d394-e3f8-47ed-a80f-3edf48c9687f","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"101":false}]},"protocol":4,"pv":"2.0","sign":"0fa407a0b417b534fb01f6812db322c4","t":1627476372}

TIMER

2 hour:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"cd1f7e43-d219-4ab2-9e0e-9d131e404ebe","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"20":120,"code":"countdown_left","t":"1627477909","value":120}]},"protocol":4,"pv":"2.0","sign":"794807949755360d882d137bf1822a92","t":1627477909}
TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"9b19f2b2-92c3-4644-b42a-a27ff5e915bb","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"19":"2h","code":"countdown_set","t":"1627477909","value":"2h"}]},"protocol":4,"pv":"2.0","sign":"4e38405c91c784b2f9bde426edb089ff","t":1627477909}

4 hour:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"c2b6535a-8afb-416c-8d23-76ab6fd9df29","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"20":240,"code":"countdown_left","t":"1627477913","value":240}]},"protocol":4,"pv":"2.0","sign":"835c28303b768c54531fa3814cf3df1d","t":1627477913}
TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"2b95f292-54a7-4e39-b193-36ebeac34eb1","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"19":"4h","code":"countdown_set","t":"1627477913","value":"4h"}]},"protocol":4,"pv":"2.0","sign":"e539ff3eb2bdcc30bc2d5fde31a90304","t":1627477913}

8 hour:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"b38552db-916e-49a7-8738-0c6704248ae6","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"20":480,"code":"countdown_left","t":"1627477917","value":480}]},"protocol":4,"pv":"2.0","sign":"caf49b2963785e05358cdc4135680631","t":1627477917}
TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"18fa8159-4303-472f-94c6-4f4855569712","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"19":"8h","code":"countdown_set","t":"1627477917","value":"8h"}]},"protocol":4,"pv":"2.0","sign":"ac372ef928dbf20787b530c76bdffeef","t":1627477917}

cancel:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"5790e35f-7088-40a7-9e79-e6e7afb12d19","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"20":0,"code":"countdown_left","t":"1627477920","value":0}]},"protocol":4,"pv":"2.0","sign":"d0227a32076679a9713bf61a3383ead0","t":1627477920}
TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"2fb85e6b-54da-4a6a-b223-d17c664d6a02","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"19":"cancel","code":"countdown_set","t":"1627477920","value":"cancel"}]},"protocol":4,"pv":"2.0","sign":"16d4c1875eb5c5016a64ea979691dc49","t":1627477920}

Turn off:

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"27c90871-7b3e-4ab6-b78f-bb2febb9023d","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"11":"off"}]},"protocol":4,"pv":"2.0","sign":"7b93c726565a113d2946d4408cfb91f6","t":1627476378}

TuyaOpenMQ onMessage: topic = cloud/token/in/2bf2d6176534990a473c46737a79c176, message = {"data":{"dataId":"dc3b8c7e-9dc3-45d0-8c3e-0c8c72288ec4","devId":"bf14060ab620daf6cch8fm","productKey":"30433rqaco1yfzli","status":[{"1":false,"code":"switch","t":"1627476378","value":false}]},"protocol":4,"pv":"2.0","sign":"3784600e46c81aa4b5e8178361d2f12b","t":1627476378}

**Comment by Hanh94** [comment]
Hi @jackwburger , This device does not support setting and reading temperatures. Here is the **dp code** supported by this device:
![](https://images.tuyacn.com/app/Hanh/heater.png)

**Comment by jackwburger** [comment]
Hi @Hanh94 

How do I use the dp code?

**Comment by Hanh94** [comment]
Hi @jackwburger ,**dp code** is the key in  Tuya plugin for device instruction control, The current plugin heater supports **switch**, **temp_current**, **temp_current_f**, **lock**, **level**, **shake**, **temp_set**, and **temp_set_f**, You can see the picture above that there is no key for setting and reading temperature, indicating that your device was not designed to support setting and reading temperature.
