### ISSUE TITLE
Homebridge Error while changing color of newly added lightstrip type 'dd'

### ISSUE THREAD

**Issue by kirit1193** [tuya/tuya-homebridge#75]
**Describe the bug**
Homebridge Error while changing color of newly added lightstrip type 'dd'

**Expected behavior**
Color should change based on color selected in the HomeKit App.

**Screenshots**

**Logs**
Adding: Smart LED Strip (dd / d76189faf2ce75243163ks)
Existing Accessory found Smart LED Strip  d76189faf2ce75243163ks 7e87b51b-8ce0-4211-9a81-7de2040c403e

[29/7/2021, 7:40:19 am] [homebridge-tuya-platform] This plugin threw an error from the characteristic 'Hue': Unhandled error thrown inside write handler for characteristic: Cannot read property 'max' of undefined. See https://git.io/JtMGR for more info.
[29/7/2021, 7:42:08 am] [homebridge-tuya-platform] This plugin threw an error from the characteristic 'Hue': Unhandled error thrown inside write handler for characteristic: Cannot read property 'max' of undefined. See https://git.io/JtMGR for more info.

**Comment by Hanh94** [comment]
Hi @kirit1193 , Thank you for your feedback, We are aware of this issue and will fix it in the next release.

**Comment by Hanh94** [comment]
Please update the plugin to version 1.3.1 and try again

**Comment by kirit1193** [comment]
Hi @Hanh94, looks like the color control works now, however, the brightness control doesn't work or is missing.

Changing the color automatically sets the brightness to 49% and there is no way to change that from the HomeKit setup. If I set brightness from the Tuya app and change the color in HomeKit it auto-sets brightness back to 49%.

**Comment by Hanh94** [comment]
Hi @kirit1193 , Do we know what's causing it and will we try to fix it in the next release.

**Comment by kirit1193** [comment]
There doesn't seem to be a brightness parameter, just a Hue / Saturation / Value parameter being sent to the API:

`TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyain.com, path = /v1.0/devices/d76189faf2ce75243163ks/commands, params = null, body = {"commands":[{"code":"switch_led","value":true}]}, headers = {"t":"1629077775879","client_id":"redacted","nonce":"redacted","Signature-Headers":"client_id","sign":"redacted","sign_method":"HMAC-SHA256","access_token":"redacted","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.1"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyain.com, path = /v1.0/devices/redacted/commands, params = null, body = {"commands":[{"code":"colour_data","value":{"h":120,"s":1000,"v":475}}]}, headers = {"t":"1629077775879","client_id":"redacted","nonce":"redacted","Signature-Headers":"client_id","sign":"redacted","sign_method":"HMAC-SHA256","access_token":"redacted","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.1"}`

Perhaps if the brightness value is sent as well. This also explains why there is no brightness control for the 'dd' LED strip.

Does that help?

**Comment by kirit1193** [comment]
Looks like this is closed in 1.4.0 with a brightness control. Cheers!
