### ISSUE TITLE
Homebridge tuya app no longer connecting

### ISSUE THREAD

**Issue by codydalerodgers** [tuya/tuya-homebridge#76]
**Describe the bug**
No changes were made to my configuration or to my Tuya setup, but Homebridge is throwing the following error and none of my accessories will respond through Homebridge or the Home.app on iOS. The accessories work fine through the Tuya app directly.

**Screenshots**

Error: connect ETIMEDOUT 42.192.35.206:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '42.192.35.206',
  port: 443,
  config: {
    url: '/v1.0/iot-01/associated-users/actions/authorized-login',
    method: 'post',
    data: '{"country_code":1,"username":"codyrodgers92@icloud.com","password":"{removed_by_me}","schema":"tuyaSmart"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      t: '1627525853426',
      client_id: 'vt5jew5easbulmbke1q3',
      nonce: 'fd889150-f014-11eb-a1f1-8f16c7fb1f11',
      'Signature-Headers': 'client_id',
      sign: '6E5B4C6C82520F40F7CDCD78804E232250E56C904E613F36114143F73D4BFE2A',
      sign_method: 'HMAC-SHA256',
      access_token: '',
      lang: 'en',
      dev_lang: 'javascript',
      dev_channel: 'homebridge',
      devVersion: '1.3.0',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 123
    },
    params: null,
    baseURL: 'https://openapi.tuyacn.com',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v1.0/iot-01/associated-users/actions/authorized-login',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'openapi.tuyacn.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1.0/iot-01/associated-users/actions/authorized-login'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 123,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /v1.0/iot-01/associated-users/actions/authorized-login HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        't: 1627525853426\r\n' +
        'client_id: vt5jew5easbulmbke1q3\r\n' +
        'nonce: fd889150-f014-11eb-a1f1-8f16c7fb1f11\r\n' +
        'Signature-Headers: client_id\r\n' +
        'sign: 6E5B4C6C82520F40F7CDCD78804E232250E56C904E613F36114143F73D4BFE2A\r\n' +
        'sign_method: HMAC-SHA256\r\n' +
        'access_token: \r\n' +
        'lang: en\r\n' +
        'dev_lang: javascript\r\n' +
        'dev_channel: homebridge\r\n' +
        'devVersion: 1.3.0\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 123\r\n' +
        'Host: openapi.tuyacn.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1.0/iot-01/associated-users/actions/authorized-login',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'openapi.tuyacn.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://openapi.tuyacn.com/v1.0/iot-01/associated-users/actions/authorized-login',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by chrise86** [comment]
@codydalerodgers how did you resolve this? Mine has started having issues
