### ISSUE TITLE
Add Support For Speed on Beville the Smart Air

### ISSUE THREAD

**Issue by shanemca** [tuya/tuya-homebridge#78]
Hello,

I have succesfully added the Beville Smart Air to the plugin and it shows in HomeKit. I can toggle it on and off, and set manual/automatic mode. When in manual mode however, there is not actually an option to change the speed (Low/Medium/High/Turbo). Can this please be added?

This is the debug log for the device:

TuyaOpenAPI response: {"result":{"devices":[{"active_time":1627644796,"biz_type":0,"category":"kj","create_time":1619929853,"icon":"smart/icon/ay157353776524912KIV/855b08e5fb39edd2a90bf9ce4630c1ad.jpg","id":"bf1e0bb75c64b3fb8783qe","ip":"x.x.x.x","lat":"-32.0632821464752","local_key":"xxxxx","lon":"115.9874818585292","model":"LAP308","name":"the Breville Smart Air™","online":true,"owner_id":"xxxxx","product_id":"tltdxtehttjbkjni","product_name":"the Breville Smart Air™","status":[{"code":"switch","value":true},{"code":"pm25","value":10},{"code":"mode","value":"manual"},{"code":"light","value":false},{"code":"uv","value":true},{"code":"filter_reset","value":false},{"code":"filter_days","value":159},{"code":"countdown_set","value":"cancle"},{"code":"countdown_left","value":0},{"code":"air_quality","value":"great"}],"sub":false,"time_zone":"+08:00","uid":"eu1627644183640WsiNm","update_time":1627645268,"uuid":"8cc1b51438332190"}],"has_more":false,"last_row_key":"3C258436E3A224961C43F48B27240B53","total":1},"success":true,"t":1627645995417} path = /v1.0/iot-01/associated-users/devices

TuyaOpenAPI response: {"result":[{"category":"kj","devices":["bf1e0bb75c64b3fb8783qe"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"manual\",\"auto\"]}"},{"code":"light","desc":"light","name":"light","type":"Boolean","values":"{}"},{"code":"uv","desc":"uv","name":"uv","type":"Boolean","values":"{}"},{"code":"filter_reset","desc":"filter reset","name":"filter reset","type":"Boolean","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Enum","values":"{\"range\":[\"2\",\"4\"]}"}],"product_id":"tltdxtehttjbkjni"}],"success":true,"t":1627645996390} path = /v1.0/devices/functions
Adding: the Breville Smart Air™ (kj / bf1e0bb75c64b3fb8783qe)

When I change the speed in the Tuya app, the following appears:

LOW
TuyaOpenMQ onMessage: topic = cloud/token/in/e69994feccca129bda1f6c2e32d1ae4b, message = {"data":{"dataId":"7e07e72b-a8b9-4094-9692-34ac578576d7","devId":"bf1e0bb75c64b3fb8783qe","productKey":"tltdxtehttjbkjni","status":[{"4":"low"}]},"protocol":4,"pv":"2.0","sign":"db2b8671c7259e4f6ee18caac63c461c","t":1627646193}

MEDIUM
TuyaOpenMQ onMessage: topic = cloud/token/in/e69994feccca129bda1f6c2e32d1ae4b, message = {"data":{"dataId":"b3f0f79e-90bc-4656-a7f1-2e546bf0af3f","devId":"bf1e0bb75c64b3fb8783qe","productKey":"tltdxtehttjbkjni","status":[{"4":"mid"}]},"protocol":4,"pv":"2.0","sign":"9063c5f880395c9d26693049fccca44d","t":1627646222}

HIGH
TuyaOpenMQ onMessage: topic = cloud/token/in/e69994feccca129bda1f6c2e32d1ae4b, message = {"data":{"dataId":"51fa0f0a-a617-4e55-9f72-b47a521f0e6e","devId":"bf1e0bb75c64b3fb8783qe","productKey":"tltdxtehttjbkjni","status":[{"4":"high"}]},"protocol":4,"pv":"2.0","sign":"b9ac88767ffa4bcfdfb028eee6a7ee19","t":1627646237}

TURBO
TuyaOpenMQ onMessage: topic = cloud/token/in/e69994feccca129bda1f6c2e32d1ae4b, message = {"data":{"dataId":"a9a8c921-e2c5-4ca2-b813-b9b6a07f3c7e","devId":"bf1e0bb75c64b3fb8783qe","productKey":"tltdxtehttjbkjni","status":[{"4":"turbo"}]},"protocol":4,"pv":"2.0","sign":"e901cad7641d0c925db5fe43962a5f89","t":1627646251}

Let me know if any more information is needed.

**Comment by Hanh94** [comment]
Hi @shanemca , The OpenAPI service has a cache, please try again.

**Comment by NickCotter01** [comment]
Hi - I'm having a similar issue where I'm unable to change the settings for my Neville air purifier in app. 

4/10/21, 5:53:27 pmHomebridgeTuyaOpenAPI response: {"result":[{"category":"cz","devices":["3870256584f3eb655453"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"XQ5aarOn6XArwoS8"},{"category":"kj","devices":["bf627e3c296a8e77aave2s"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"light","desc":"light","name":"light","type":"Boolean","values":"{}"},{"code":"uv","desc":"uv","name":"uv","type":"Boolean","values":"{}"},{"code":"filter_reset","desc":"filter reset","name":"filter reset","type":"Boolean","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Enum","values":"{\"range\":[\"2\",\"4\"]}"}],"product_id":"k2mlahbu9v4xxdlb"}],"success":true,"t":1634198007480} path = /v1.0/devices/functions
14/10/21, 5:53:27 pmHomebridgeAdding: the Breville Easy Air™ (kj / bf627e3c296a8e77aave2s)
14/10/21, 5:53:27 pmHomebridgeCreating New Accessory bf627e3c296a8e77aave2s
14/10/21, 5:53:27 pmHomebridgeRegister Platform Accessory the Breville Easy Air™

Please let me know if any further info is needed.
