### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by dfizzo** [tuya/tuya-homebridge#79]
**Describe the bug**

I am receiving the following "TypeError: Cannot read property 'length' of undefined". Product is Treatlife Smart Fam Control. Thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/83602323/127790534-d3d7b1c3-b36e-42bd-93e3-156337d44d3b.jpeg)If applicable, add screenshots to help explain your problem.

**Login request (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/iot-01/associated-users/actions/authorized-login**

like this:

TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":86,"username":"XXXXXXXXXXXXX","password":"c44755c3379313db173e53c3e8fb6701","schema":"tuyaSmart"}, headers = {"t":"1626082406842","client_id":"XXXXXXXXXXXXX","nonce":"33341140-e2f4-11eb-abd9-491eaffd7d33","Signature-Headers":"client_id","sign":"2E250AB9256B14F6EAD94DEA9EE0EA8413E7939E7DEAB0B60D8D786B296A7AF8","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.2.1"}

**Login response (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)):**
**request path = /v1.0/devices/functions**
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1626082407259} path = /v1.0/iot-01/associated-users/actions/authorized-login

**Comment by Hanh94** [comment]
Hi @dfizzo , The screenshot indicates that you have logged in successfully, but the log in the back shows that you failed to log in, and I did not see your request log in **cn**, please provide the latest log.

**Comment by dfizzo** [comment]
I think my issue was that I added the Tuya plug-in directly through the Homebridge UI, rather than following your unique steps to add plugin via Raspberry pi Terminal and modifying the config.json file. I have just tried that approach, and successfully added the Tuya Homebridge bridge, but my devices are not showing up in HomeKit 

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Aug 2, 2021, at 8:14 AM, Hanh94 ***@***.***> wrote:

﻿
Hi @dfizzo , The screenshot indicates that you have logged in successfully, but the log in the back shows that you failed to log in, and I did not see your request log in cn, please provide the latest log.

**Comment by dfizzo** [comment]
I installed Tuya Homebridge per the instructions provided (via Rasperberry Pi terminal). I successfully added the new bridge to HomeKit but still not working Here is message I am getting:

Starting to advertise 'homebridge-tuya-platform 9D3A' using bonjour-hap backend!
[8/2/2021, 1:45:04 PM] Homebridge v1.3.4 (homebridge-tuya-platform) is running on port 8081.
TuyaOpenAPI response: {"result":{"access_token":"ef6cc96f3a2afe393292edac39afe40e","expire_time":7200,"platform_url":"https://openapi.tuyaus.com","refresh_token":"a67232dfda9b2d373ee995c6c3b2b72d","uid":"az1620392484030RFO4t"},"success":true,"t":1627926306118} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaus.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1627926306231","client_id":"j5y9gjwwasxb33d179de","nonce":"5dc40980-f3b9-11eb-a4c9-55181902cc08","Signature-Headers":"client_id","sign":"95263485D1A1B85011BC0B8F785894E02E5DB7F9747318FF3EF081F7D4590676","sign_method":"HMAC-SHA256","access_token":"ef6cc96f3a2afe393292edac39afe40e","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.0"}
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1620400815,"biz_type":0,"category":"fskg","create_time":1620400815,"icon":"smart/icon/ay14906729310721fNjn/a92553379c09ef865681d1c62eb04190.jpg","id":"eb157ba5d7348d8944epbz","ip":"73.139.191.91","lat":"25.67839493407654","local_key":"466aadd3cdc36a11","lon":"-80.28515804087839","name":"Master Bedroom Ceiling Fan","online":true,"owner_id":"40682502","product_id":"tqas5nfwomvgvvhf","product_name":"Smart Ceiling Fan Switch-DS02F","status":[{"code":"switch_fan","value":false},{"code":"countdown_fan","value":0},{"code":"fan_speed_enum","value":"level_4"},{"code":"fan_speed","value":0}],"sub":false,"time_zone":"-04:00","uid":"az1620392484030RFO4t","update_time":1627904182,"uuid":"a8e9f5c95b3d1bbe"}],"has_more":false,"last_row_key":"4AE2E4BE41A66CCB4D5E15C9D788F7BB","total":1},"success":true,"t":1627926306581} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/functions, params = {"device_ids":"eb157ba5d7348d8944epbz"}, body = null, headers = {"t":"1627926306625","client_id":"j5y9gjwwasxb33d179de","nonce":"5dc40980-f3b9-11eb-a4c9-55181902cc08","Signature-Headers":"client_id","sign":"FC4CA0D7B7B0637EB462D33899D78942C9F66E91D23C05F98B9C66E5DF1C20D8","sign_method":"HMAC-SHA256","access_token":"ef6cc96f3a2afe393292edac39afe40e","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.0"}
TuyaOpenAPI response: {"result":[{"category":"fskg","devices":["eb157ba5d7348d8944epbz"],"functions":[{"code":"switch_fan","desc":"switch fan","name":"switch fan","type":"Boolean","values":"{}"},{"code":"countdown_fan","desc":"countdown fan","name":"countdown fan","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"fan_speed_enum","desc":"fan speed enum","name":"fan speed enum","type":"Enum","values":"{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\"]}"},{"code":"fan_speed","desc":"fan speed","name":"fan speed","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"}],"product_id":"tqas5nfwomvgvvhf"}],"success":true,"t":1627926306925} path = /v1.0/devices/functions
Adding: Master Bedroom Ceiling Fan (fskg / eb157ba5d7348d8944epbz)
Creating New Accessory eb157ba5d7348d8944epbz
Register Platform Accessory Master Bedroom Ceiling Fan
[8/2/2021, 1:45:06 PM] TypeError: Cannot read property 'length' of undefined
    at Fanv2Accessory.getSpeedFunctionLevel (/home/pi/node_modules/homebridge-tuya-platform/lib/fanv2_accessory.js:226:57)
    at new Fanv2Accessory (/home/pi/node_modules/homebridge-tuya-platform/lib/fanv2_accessory.js:28:29)
    at TuyaPlatform.addAccessory (/home/pi/node_modules/homebridge-tuya-platform/index.js:148:27)
    at TuyaPlatform.initTuyaSDK (/home/pi/node_modules/homebridge-tuya-platform/index.js:97:12)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[8/2/2021, 1:45:06 PM] Got SIGTERM, shutting down Homebridge...

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Aug 2, 2021, at 8:14 AM, Hanh94 ***@***.***> wrote:

﻿
Hi @dfizzo , The screenshot indicates that you have logged in successfully, but the log in the back shows that you failed to log in, and I did not see your request log in cn, please provide the latest log.

**Comment by Hanh94** [comment]
Hi @dfizzo ,Thanks for your accurate log, we found that **"fan_speed"** has not been well adapted to various Fan device, we will fix this problem in the next version.

**Comment by dfizzo** [comment]
Thank you!!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Aug 3, 2021, at 12:02 AM, Hanh94 ***@***.***> wrote:

﻿
Hi @dfizzo ,Thanks for your accurate log, we found that "fan_speed" has not been well adapted to various Fan device, we will fix this problem in the next version.

**Comment by Hanh94** [comment]
Please update the plugin to version 1.3.1 and try again.

**Comment by dfizzo** [comment]
Thanks again, @Hanh94! This works perfectly now!!!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Aug 5, 2021, at 2:51 AM, Hanh94 ***@***.***> wrote:

﻿
Please update the plugin to version 1.3.1 and try again.
