### ISSUE TITLE
iOS Device Manager

### ISSUE THREAD

**Issue by cgarrovillo** [tuya/tuya-homebridge#8]
How should iOS Users continue following the configuration guide: https://github.com/tuya/tuya-android-iot-app-sdk-sample/blob/activator_tool/Tuya_IoT_Platform_Configuration_Guide.md if the App is android only? I assume this is because of apple's security restrictions?

But still, how should users continue without using an Android device?

**Comment by zlinoliver** [comment]
Hi @cgarrovillo ，thanks for the feedbacks, we will provide the iOS version of Device Manager app soon.

**Comment by cgarrovillo** [comment]
Has this been resolved?

**Comment by zlinoliver** [comment]
@cgarrovillo we have updated the homebridge plugin to support "Smart Home PaaS" project type, which you can use Tuya Smart/ Tuya SmartLife app for device pairing directly. For more information, you can check this tutorial: [Tuya IoT Platform Configuration Guide Using Smart Home PaaS](https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx) and [How to Use Tuya Homebridge Plugin](https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt).

**Comment by Dizzle9** [comment]
I have the plugin running and config set with accessID and accessKey in. for some reason none of my devices show in the accessories or the HomeKit? Unsure of what I'm missing any help would be much appreciated.

**Comment by cgarrovillo** [comment]
> I have the plugin running and config set with accessID and accessKey in. for some reason none of my devices show in the accessories or the HomeKit? Unsure of what I'm missing any help would be much appreciated.

Change your config and set `debug` to true. You might be getting the same error here #29

**Comment by Hanh94** [comment]
Hi @cgarrovillo @Dizzle9 , For account permissions, please refer to [this comment](https://github.com/tuya/tuya-homebridge/issues/29#issuecomment-855552880).

**Comment by Dizzle9** [comment]
I have done that for some reason it's giving me a yellow config.Json not found I've rebuilt the config in homebridge about a dozen times it shows as good but the terminal gives the config error. I've fried my brain trying this and it's probably something supper simple. 🤯😠😶‍🌫️

**Comment by Hanh94** [comment]
> I have done that for some reason it's giving me a yellow config.Json not found I've rebuilt the config in homebridge about a dozen times it shows as good but the terminal gives the config error. I've fried my brain trying this and it's probably something supper simple. 🤯😠😶‍🌫️

Hi @Dizzle9 ,Sorry for the bad experience.
Account configuration is not complicated:
1.Create a Smart Home PaaS project
2.In Configuration Wizard, select Device status notification API.(Smart Home PaaS API has been selected as default.)
3.Get authorization key
4.Link devices by app account

Common account permissions issues:
1.Your cloud project on the [Tuya IoT Platform](https://iot.tuya.com/cloud/) was created after May 25, 2021.
2.On the [Tuya IoT Platform](https://iot.tuya.com/cloud/), you have linked devices by using Tuya Smart or Smart Life app in your cloud project.
3.You entered the correct account and password of the Tuya Smart or Smart Life app in the **Account** and **Password** fields.

Please show us the error info and the desensitized config.json file , we will try to help you solve this issue

**Comment by Hanh94** [comment]
Hi guys, Since we haven't received your reply for a long time, we think our latest version should have solved your problem. We will close this issue first. If there is any problem, you can contact us at any time.

**Comment by Dizzle9** [comment]
It’s still not running or showing accessories. I haven’t seen a error message I am unsure of where to find it. Sorry   
  
  
  
    
  

  
  
>

**Comment by Hanh94** [comment]
Hi @Dizzle9 ,Please refer to the issue template for more log information. How to obtain the log please refer to [How-To-Get-Logs](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)

**Comment by Dizzle9** [comment]
Okay that’s what’s weird! I have all that debug checked and yet it never shows Tuya or magic light plug-ins but I can see and operate magic lights. Can’t see or operate any Tuya devices.   
  
  
  
    
  

  
  
>

**Comment by Dizzle9** [comment]
I figured it out and it's an error on Tuya's side. Which is what I told them front the get and for that I know they see it as it's the only missing piece. Not gonna so they should fix it for others to not have an issue. No I won't tell them how either. Well over a month or two of back and forth. Oh you need to follow this and that. Incorrect and misleading all so the don't have admit fault.
