### ISSUE TITLE
Dimming Function Missing, everything else works great

### ISSUE THREAD

**Issue by rice3253** [tuya/tuya-homebridge#81]
I successfully added my light strip to Tuya, and I can control it from within the Home app on iPhone, but the function to dim the strip is missing. I can only switch the strip on and off, and I cannot dim the strip. See below for logs.

Thank you :) 

TuyaOpenMQ onMessage: topic = cloud/token/in/ef3d183f2ec4fa55e07c296e90f8d29f, message = {"data":{"dataId":"73026ed9-463c-4445-aa56-7b25a81c06ea","devId":"eb584f62a1eec180d9aqda","productKey":"xoezqlk2fizh51qw","status":[{"20":true,"code":"switch_led","t":"1628139291","value":true}]},"protocol":4,"pv":"2.0","sign":"7d381a7e7ea799fc21d8f0f7f9608202","t":1628139291}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/eb584f62a1eec180d9aqda/commands, params = null, body = {"commands":[{"code":"switch_led","value":true}]}, headers = {"t":"1628139443852","client_id":"a5jxnyeuat7ua14ewr9k","nonce":"c10f0530-f5a8-11eb-804d-83b0d3d8ae55","Signature-Headers":"client_id","sign":"6C66E5B0130DFAF44F5C0F8E9A07BD6B3321F7340D18E37F45A573E47469229D","sign_method":"HMAC-SHA256","access_token":"099369762016b99917fe159382b2bcb2","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.1"}
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/eb584f62a1eec180d9aqda/commands, params = null, body = {"commands":[{"code":"colour_data_v2","value":{"h":0,"s":1000,"v":1000}}]}, headers = {"t":"1628139443854","client_id":"a5jxnyeuat7ua14ewr9k","nonce":"c10f0530-f5a8-11eb-804d-83b0d3d8ae55","Signature-Headers":"client_id","sign":"36714A1080A7FF13E9BF3290EE1FDC8C871D0312B6D208ACE991118358FF7265","sign_method":"HMAC-SHA256","access_token":"099369762016b99917fe159382b2bcb2","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.3.1"}
TuyaOpenAPI response: {"result":true,"success":true,"t":1628139444082} path = /v1.0/devices/eb584f62a1eec180d9aqda/commands
TuyaOpenAPI response: {"result":true,"success":true,"t":1628139444084} path = /v1.0/devices/eb584f62a1eec180d9aqda/commands
TuyaOpenMQ onMessage: topic = cloud/token/in/ef3d183f2ec4fa55e07c296e90f8d29f, message = {"data":{"dataId":"45e6dbb0-d992-418c-9d35-77c97937be7c","devId":"eb584f62a1eec180d9aqda","productKey":"xoezqlk2fizh51qw","status":[{"24":"000003e803e8","code":"colour_data_v2","t":"1628139444","value":"{\"h\":0,\"s\":1000,\"v\":1000}"}]},"protocol":4,"pv":"2.0","sign":"122f7a8a561ef12a9cc78a237781e367","t":1628139444}
TuyaOpenMQ onMessage: topic = cloud/token/in/ef3d183f2ec4fa55e07c296e90f8d29f, message = {"data":{"dataId":"e7751eb3-45bc-40cb-a4c4-b17f3102cd19","devId":"eb584f62a1eec180d9aqda","productKey":"xoezqlk2fizh51qw","status":[{"20":true,"code":"switch_led","t":"1628139444","value":true}]},"protocol":4,"pv":"2.0","sign":"ea22d903d595643f951edeef208cd534","t":1628139444}

**Comment by Hanh94** [comment]
Hi @rice3253 , Your device **TC0318_TW03_STRIP3_RGB_P20**, is an RGB color light, does not support brightness adjustment.

```
{
    "devices":[
        {
            "active_time":1628129370,
            "biz_type":0,
            "category":"dj",
            "create_time":1628129370,
            "icon":"smart/icon/001460162698766TR4v1/9e75aac9d4b8aa99d78b7efb739bf2ae.png",
            "id":"eb584f62a1eec180d9aqda",
            "ip":"216.106.148.70",
            "lat":"44.97348068064117",
            "local_key":"e068d63beef115a3",
            "lon":"-93.2297924088333",
            "model":"",
            "name":"Neon",
            "online":true,
            "owner_id":"47154558",
            "product_id":"xoezqlk2fizh51qw",
            "product_name":"TC0318_TW03_STRIP3_RGB_P20",
            "status":[
                {
                    "code":"switch_led",
                    "value":true
                },
                {
                    "code":"work_mode",
                    "value":"colour"
                },
                {
                    "code":"colour_data_v2",
                    "value":"{\"h\":0,\"s\":1000,\"v\":487}"
                },
                {
                    "code":"scene_data_v2",
                    "value":"{\"scene_num\":4,\"scene_units\":[{\"bright\":0,\"h\":221,\"s\":1000,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":1000}]}"
                },
                {
                    "code":"countdown_1",
                    "value":0
                },
                {
                    "code":"music_data",
                    "value":""
                },
                {
                    "code":"control_data",
                    "value":""
                }
            ],
            "sub":false,
            "time_zone":"-05:00",
            "uid":"az1628114369602ReI7S",
            "update_time":1628137611,
            "uuid":"60034824286dcd085617"
        }
    ],
    "has_more":false,
    "last_row_key":"4DF2214F82B914F5362E2181E32F936C",
    "total":1
}
```

**Comment by rice3253** [comment]
Ahhh, thank you for that explanation. I can control the strips brightness through the Tuya Smart App, but I guess the strip isn't correctly exposing its capabilities correctly to Homebridge. Thank you for the help :)
