### ISSUE TITLE
Garage Door Opener not getting detected in Homekit

### ISSUE THREAD

**Issue by singhrajtomar** [tuya/tuya-homebridge#82]
I have a garage door opener paired on Smart Life. The tutorial mentions that the homebridge plugin supports garage door openers. I followed all the steps properly according to the tutorial. The homebridge starts and when I pair it with my iPhone, the homekit app does pair with the bridge but does not show my garage door opener. In the development page, my device is added and is showing online. In homebridge, there is no error related to plugin or device getting detected. But the strange issue i found in the logs is that the plugin is loaded but is not detecting any devices. I am new to all of this so kindly help.

Thank You

**Comment by Hanh94** [comment]
Hi @singhrajtomar , Thank you for your feedback.
Please provide more log information according to the issue template.

**Comment by singhrajtomar** [comment]
> Hi @singhrajtomar , Thank you for your feedback.
> Please provide more log information according to the issue template.

Sure. I have reset the Homebridge. Will configure it again and share it with you.

**Comment by Hanh94** [comment]
Hi @singhrajtomar ,Please refer to the issue template for more log information. How to obtain the log please refer to [How-To-Get-Logs](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)

**Comment by Hanh94** [comment]
Hi @singhrajtomar , sorry for the late reply.
Please check the [error code](https://github.com/tuya/tuya-homebridge#tuya-openapi-login-error-code)
