### ISSUE TITLE
Plugin stopped connecting to Tuya API (CN)

### ISSUE THREAD

**Issue by slavvka** [tuya/tuya-homebridge#91]
**Describe the bug**
Some time ago I found that my installation stopped working since it cannot connect to the Tuya API. I think it may be related to the APi domain used to connect https://github.com/tuya/tuya-homebridge/blob/master/lib/tuyashopenapi.js#L5 which is `https://openapi.tuyacn.com`. I tried to connect to it and it fails. Whereas I can connect to `https://openapi.tuyaus.com`. The logs are:
```
Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":1,"username":"***","password":"****","schema":"smartlife"}, headers = {"t":"1629211919936","client_id":"****","nonce":"****","Signature-Headers":"client_id","sign":"***","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.0"}
Error: connect ETIMEDOUT 42.192.35.206:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```
When I changed the domain locally  `https://openapi.tuyaus.com` the plugin started working for me.

**Expected behavior**
It should connect to the API. Probably it should use different domains depending on a region.

**Comment by slavvka** [comment]
@Hanh94 It is a blocker

**Comment by ankushg** [comment]
Also running into this. Definitely a blocker.

I had to manually override the `DEFAULT_ENDPOINT` to use the US server and it's working now, there should be a way to override this value from config.

 https://github.com/tuya/tuya-homebridge/blob/master/lib/tuyashopenapi.js#L5
