### ISSUE TITLE
Temperature and Humidity Sensor not loading on hombridge

### ISSUE THREAD

**Issue by Mendelyeev** [tuya/tuya-homebridge#92]
Hello there,

I've recently added a temperature and humidity sensor on Smart Life/tuya hub. On app, the sensor showed up and worked well, but not loaded on homebridge plugin. Any ideas how to solve it?

**Comment by Hanh94** [comment]
Hi @Mendelyeev ,This is the [category](https://github.com/tuya/tuya-homebridge/wiki/Supported-Tuya-Device-Types?_source=6a1b8046224626e798190c06532c8be2) currently supported.

**Comment by macecchi** [comment]
Hi @Mendelyeev @Hanh94, I'm working on this and plan on opening a pull request soon :) 

I'm adding support to device type `wsdcg`. [This](https://www.amazon.com/Temperature-Humidity-Compatible-Assistant-Smart-Things/dp/B095KBZGMN) is the sensor I own and I'm using for the tests.

**Comment by Mendelyeev** [comment]
> Hi @Mendelyeev @Hanh94, I'm working on this and plan on opening a pull request soon :)
> 
> I'm adding support to device type `wsdcg`. [This](https://www.amazon.com/Temperature-Humidity-Compatible-Assistant-Smart-Things/dp/B095KBZGMN) is the sensor I own and I'm using for the tests.

HI @macecchi , this sensor is the same of mine!

**Comment by robberburn** [comment]
This would be great
