### ISSUE TITLE
Reversed temperature in home app

### ISSUE THREAD

**Issue by josemmc95** [tuya/tuya-homebridge#94]
When changing temperature of white color in home app, the warmer side puts cold white and the colder side of the selector puts warm white.

Furthermore, the majority of the color selector don’t match with the result.

I attach you the selector I mean.

Is it a bug with Home app or with the plug-in? 

Thank you in advanced.

![A71A168D-6673-4DEE-9A8C-3CF07B1680BD](https://user-images.githubusercontent.com/62221854/130325636-3fe21c29-6435-4030-a32a-1ccba48dd5af.png)
![7F2D8C96-9528-4281-AE99-BB71C7498416](https://user-images.githubusercontent.com/62221854/130325637-cfe10f0b-7616-4ddb-82a0-f1e3f98f09f3.png)

**Comment by kclejeune** [comment]
I have this issue as well, but this is likely a duplicate of #90

**Comment by josemmc95** [comment]
> I have this issue as well, but this is likely a duplicate of #90

That's the same issue, I'll close the issue and follow that issue.

Thanks!
