### ISSUE TITLE
Smart Button type:'wxkg' not loading

### ISSUE THREAD

**Issue by Mendelyeev** [tuya/tuya-homebridge#99]
Hello there,

I've bought a smart switch (YSB22无线智能开关-升级版) and configured on Tuya iOS app. Despite of shown on Tuya ios APP that swithc isn't shown on tuya plugin on HB.

I've noticied that the current product category is shown as 'wxkg' and the supported switch type is 'kg'. Is there any way to change that Category?

**Comment by Hanh94** [comment]
Hi @Mendelyeev , Sorry for the late reply.
Please turn on the log, and Check the **category wxkg** device information returned by this interface **/V1.0 / iot-01 /associated- Users/Devices**
Please see [How-To-Get-Logs](https://github.com/tuya/tuya-homebridge/wiki/How-To-Get-Logs)

**Comment by Mendelyeev** [comment]
@Hanh94 That's fine! Chill out! Following is the log:

**I removed sensitive items**

`TuyaOpenAPI response: {"result":{"devices":[{"active_time":1630003576,"biz_type":0,"category":"wxkg","create_time":1630003576,"icon":"smart/icon/ay1567583669199Igy1S/5ede16802caf3dd72f43dfbc140b337b.jpg","id":"xxxxxxxxxxxxxxxxxx","ip":"","lat":"-8.1162","local_key":"xxxxxxxx","lon":"-34.8990","model":"YSB22","name":"Interruptor Closet","node_id":"xxxxxxxx","online":true,"owner_id":"xxxxxxxx","product_id":"f97vq5mn","product_name":"YSB22无线智能开关-升级版","status":[{"code":"switch1_value","value":"single_click"}],"sub":true,"time_zone":"-03:00","uid":"xxxxxxxx","update_time":xxxxxxxx,"uuid":"xxxxxxxx"},{"active_time":1630002598,"biz_type":0,"category":"wfcon","create_time":1630002598,"icon":"smart/icon/ay1534490862266NApJD/58c8ee48c9227b51417ac6b76d9f410b.jpg","id":"xxxxxxx","ip":"xxxxxx0","lat":"-8.1160","local_key":"xxxxxxxx","lon":"-34.8993","model":"ZXGWZ-02","name":"Smart Gateway","online":true,"owner_id":"xxxxxxxx","product_id":"xxxxxxxx","product_name":"智能网关（TYGWZ-02N）","status":[],"sub":false,"time_zone":"-03:00","uid":"xxxxxxxx","update_time":xxxxxxxx,"uuid":"xxxxxx"},{"active_time":1630002648,"biz_type":0,"category":"wsdcg","create_time":1630002648,"icon":"smart/icon/ay1503986080106Gppjy/04b538bf5c86c8394ed187d0941ae8af.png","id":"ebe38cac9fded1d23fnrm7","ip":"","lat":"-8.1162","local_key":"xxxxxxxx","lon":"-34.8990","model":"","name":"Sensor temperatura Suíte","node_id":"b4e3f9fffe0c4ae8","online":true,"owner_id":"xxxxxxxx","product_id":"qaaysllp","product_name":"Zigbee温湿度 NEO","status":[{"code":"va_temperature","value":269},{"code":"va_humidity","value":776},{"code":"battery_percentage","value":86},{"code":"temp_unit_convert","value":"c"},{"code":"maxtemp_set","value":40},{"code":"minitemp_set","value":10},{"code":"maxhum_set","value":90},{"code":"minihum_set","value":20},{"code":"temp_alarm","value":"cancel"},{"code":"hum_alarm","value":"cancel"},{"code":"bright_value","value":107},{"code":"switch","value":false}],"sub":true,"time_zone":"-03:00","uid":"xxxxxxxx","update_time":xxxxxxxx,"uuid":"b4e3f9fffe0c4ae8"},{"active_time":1630003229,"biz_type":0,"category":"mcs","create_time":1629997111,"icon":"smart/icon/ay1525749833414yotNt/92722d1b64636ed1dfe3107187643324.jpg","id":"36426202a4e57c8a3de5","ip":"xxxxxxx","lat":"-8.1163","local_key":"57d9c52ef3a5d315","lon":"-34.8991","model":"D06 TYWE3S","name":"Sensor porta entrada","online":true,"owner_id":"xxxxxxxx","product_id":"ikfjwqdbpnh154b9","product_name":"门磁","status":[{"code":"doorcontact_state","value":false},{"code":"battery_state","value":"high"}],"sub":false,"time_zone":"-03:00","uid":"xxxxxxxx","update_time":1635940305,"uuid":"36426202a4e57c8a3de5"},{"active_time":1633105425,"biz_type":0,"category":"mcs","create_time":1633105425,"icon":"smart/icon/ay1525749833414yotNt/b732ec58420c793ffb6f6136089970ab.jpg","id":"eba65ae673d98f9fefzjpz","ip":"186.214.135.173","lat":"-8.1160","local_key":"xxxxxxx","lon":"-34.8992","model":"D06CB3S","name":"Porta Cozinha","online":true,"owner_id":"xxxxxxxx","product_id":"e7dny8zvmiyhqerw","product_name":"D06CB3S门磁","status":[{"code":"doorcontact_state","value":false}],"sub":false,"time_zone":"-03:00","uid":"xxxxxxxx","update_time":1635885614,"uuid":"xxxxxxxxx"}],"has_more":false,"last_row_key":"A9B70FCFBD6B36729C222061136EE461","total":5},"success":true,"t":1635948376037} path = /v1.0/iot-01/associated-users/devices
`
